// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs
    (actor_user_id, action, entity_type, entity_id, before, after, ip, user_agent, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditLogParams struct {
	ActorUserID *int64
	Action      string
	EntityType  string
	EntityID    string
	Before      []byte
	After       []byte
	Ip          *netip.Addr
	UserAgent   string
	RequestID   string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.Ip,
		arg.UserAgent,
		arg.RequestID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_user_id, action, entity_type, entity_id, before, after, ip, user_agent, request_id, created_at FROM audit_logs
WHERE ($1::text IS NULL OR entity_type = $1::text)
  AND ($2::text   IS NULL OR entity_id   = $2::text)
  AND ($3::bigint     IS NULL OR actor_user_id = $3::bigint)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListAuditLogsParams struct {
	EntityType *string
	EntityID   *string
	Actor      *int64
	Off        int32
	Lim        int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.EntityType,
		arg.EntityID,
		arg.Actor,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.UserAgent,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
