// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package db

import (
	"context"
	"time"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :one
UPDATE auth_tokens
SET used_at = now()
WHERE token_hash = $1
  AND purpose = $2
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, token_hash, purpose, expires_at, used_at, created_at
`

type ConsumeAuthTokenParams struct {
	TokenHash []byte
	Purpose   TokenPurpose
}

// Tek kullanımlıktır: UPDATE ... RETURNING ile atomik olarak tüketilir.
// Ayrı SELECT + UPDATE yapılsaydı iki eşzamanlı istek aynı token'ı kullanabilirdi.
func (q *Queries) ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, consumeAuthToken, arg.TokenHash, arg.Purpose)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (user_id, token_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, purpose, expires_at, used_at, created_at
`

type CreateAuthTokenParams struct {
	UserID    int64
	TokenHash []byte
	Purpose   TokenPurpose
	ExpiresAt time.Time
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, createAuthToken,
		arg.UserID,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :execrows
DELETE FROM auth_tokens WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const invalidateUserTokens = `-- name: InvalidateUserTokens :exec
UPDATE auth_tokens SET used_at = now()
WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL
`

type InvalidateUserTokensParams struct {
	UserID  int64
	Purpose TokenPurpose
}

func (q *Queries) InvalidateUserTokens(ctx context.Context, arg InvalidateUserTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateUserTokens, arg.UserID, arg.Purpose)
	return err
}
