// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDimensionMaps = `-- name: CountDimensionMaps :one
SELECT count(*) FROM provider_dimension_maps WHERE provider_id = $1 AND dimension = $2
`

type CountDimensionMapsParams struct {
	ProviderID int64
	Dimension  string
}

func (q *Queries) CountDimensionMaps(ctx context.Context, arg CountDimensionMapsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDimensionMaps, arg.ProviderID, arg.Dimension)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (name, protocol, base_url, api_key_enc, is_active, priority, cost_multiplier, capabilities)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, name, protocol, base_url, api_key_enc, is_active, priority, cost_multiplier, account_balance_micro, account_synced_at, capabilities, created_at, updated_at
`

type CreateProviderParams struct {
	Name           string
	Protocol       ProviderProtocol
	BaseUrl        string
	ApiKeyEnc      []byte
	IsActive       bool
	Priority       int32
	CostMultiplier pgtype.Numeric
	Capabilities   []byte
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Protocol,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.IsActive,
		arg.Priority,
		arg.CostMultiplier,
		arg.Capabilities,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.IsActive,
		&i.Priority,
		&i.CostMultiplier,
		&i.AccountBalanceMicro,
		&i.AccountSyncedAt,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCountryByISO = `-- name: GetCountryByISO :one
SELECT id, iso2, name, name_tr, phone_code, is_visible, supports_rent, created_at, updated_at FROM countries WHERE iso2 = $1
`

func (q *Queries) GetCountryByISO(ctx context.Context, iso2 string) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByISO, iso2)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Iso2,
		&i.Name,
		&i.NameTr,
		&i.PhoneCode,
		&i.IsVisible,
		&i.SupportsRent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, kind, service_id, country_id, operator_id, verification_type, duration_minutes, dimension_a_id, attributes, is_active, created_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ServiceID,
		&i.CountryID,
		&i.OperatorID,
		&i.VerificationType,
		&i.DurationMinutes,
		&i.DimensionAID,
		&i.Attributes,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getProductForActivation = `-- name: GetProductForActivation :one
SELECT p.id, p.kind, p.service_id, p.country_id, p.operator_id, p.verification_type, p.duration_minutes, p.dimension_a_id, p.attributes, p.is_active, p.created_at FROM products p
WHERE p.kind = 'SMS_ACTIVATION'
  AND p.service_id = $1 AND p.country_id = $2
  AND p.verification_type = $3
  AND p.operator_id IS NULL AND p.duration_minutes IS NULL
  AND p.is_active
`

type GetProductForActivationParams struct {
	ServiceID        *int64
	CountryID        *int64
	VerificationType VerificationType
}

func (q *Queries) GetProductForActivation(ctx context.Context, arg GetProductForActivationParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForActivation, arg.ServiceID, arg.CountryID, arg.VerificationType)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ServiceID,
		&i.CountryID,
		&i.OperatorID,
		&i.VerificationType,
		&i.DurationMinutes,
		&i.DimensionAID,
		&i.Attributes,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getProductForRental = `-- name: GetProductForRental :one
SELECT p.id, p.kind, p.service_id, p.country_id, p.operator_id, p.verification_type, p.duration_minutes, p.dimension_a_id, p.attributes, p.is_active, p.created_at FROM products p
WHERE p.kind = 'SMS_RENTAL'
  AND p.service_id = $1 AND p.country_id = $2
  AND p.duration_minutes = $3
  AND p.operator_id IS NULL
  AND p.is_active
`

type GetProductForRentalParams struct {
	ServiceID       *int64
	CountryID       *int64
	DurationMinutes *int32
}

func (q *Queries) GetProductForRental(ctx context.Context, arg GetProductForRentalParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForRental, arg.ServiceID, arg.CountryID, arg.DurationMinutes)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ServiceID,
		&i.CountryID,
		&i.OperatorID,
		&i.VerificationType,
		&i.DurationMinutes,
		&i.DimensionAID,
		&i.Attributes,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, protocol, base_url, api_key_enc, is_active, priority, cost_multiplier, account_balance_micro, account_synced_at, capabilities, created_at, updated_at FROM providers WHERE id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.IsActive,
		&i.Priority,
		&i.CostMultiplier,
		&i.AccountBalanceMicro,
		&i.AccountSyncedAt,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
SELECT id, name, protocol, base_url, api_key_enc, is_active, priority, cost_multiplier, account_balance_micro, account_synced_at, capabilities, created_at, updated_at FROM providers WHERE name = $1
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByName, name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.IsActive,
		&i.Priority,
		&i.CostMultiplier,
		&i.AccountBalanceMicro,
		&i.AccountSyncedAt,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderRemoteCodes = `-- name: GetProviderRemoteCodes :one
SELECT
    ms.remote_code AS service_remote_code,
    mc.remote_code AS country_remote_code
FROM products p
JOIN provider_dimension_maps ms
     ON ms.provider_id = $1 AND ms.dimension = 'service' AND ms.local_id = p.service_id
JOIN provider_dimension_maps mc
     ON mc.provider_id = $1 AND mc.dimension = 'country' AND mc.local_id = p.country_id
WHERE p.id = $2
`

type GetProviderRemoteCodesParams struct {
	ProviderID int64
	ProductID  int64
}

type GetProviderRemoteCodesRow struct {
	ServiceRemoteCode string
	CountryRemoteCode string
}

// Bir ürünün, BELİRLİ BİR SAĞLAYICIDAKİ karşılıklarını verir.
//
// Sağlayıcıya istek atarken BİZİM kodlarımız (services.code, countries.iso2)
// KULLANILAMAZ. HeroSMS ülkeyi "62" bilir, biz "TR" biliriz. Çeviri burada
// yapılır; yapılmazsa sağlayıcı "böyle bir ülke yok" der ve teklif düşer.
// test: internal/service/pricing/remote_codes_integration_test.go#TestProviderReceivesItsOwnCodes
func (q *Queries) GetProviderRemoteCodes(ctx context.Context, arg GetProviderRemoteCodesParams) (GetProviderRemoteCodesRow, error) {
	row := q.db.QueryRow(ctx, getProviderRemoteCodes, arg.ProviderID, arg.ProductID)
	var i GetProviderRemoteCodesRow
	err := row.Scan(&i.ServiceRemoteCode, &i.CountryRemoteCode)
	return i, err
}

const getRemoteCode = `-- name: GetRemoteCode :one
SELECT remote_code FROM provider_dimension_maps
WHERE provider_id = $1 AND dimension = $2 AND local_id = $3
`

type GetRemoteCodeParams struct {
	ProviderID int64
	Dimension  string
	LocalID    int64
}

func (q *Queries) GetRemoteCode(ctx context.Context, arg GetRemoteCodeParams) (string, error) {
	row := q.db.QueryRow(ctx, getRemoteCode, arg.ProviderID, arg.Dimension, arg.LocalID)
	var remote_code string
	err := row.Scan(&remote_code)
	return remote_code, err
}

const getServiceByCode = `-- name: GetServiceByCode :one
SELECT id, code, name, name_tr, icon_url, is_visible, sort_order, created_at, updated_at FROM services WHERE code = $1
`

func (q *Queries) GetServiceByCode(ctx context.Context, code string) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByCode, code)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NameTr,
		&i.IconUrl,
		&i.IsVisible,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProviders = `-- name: ListActiveProviders :many

SELECT id, name, protocol, base_url, api_key_enc, is_active, priority, cost_multiplier, account_balance_micro, account_synced_at, capabilities, created_at, updated_at FROM providers WHERE is_active ORDER BY priority, id
`

// ─────────────────────── Sağlayıcı ───────────────────────
func (q *Queries) ListActiveProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listActiveProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Protocol,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.IsActive,
			&i.Priority,
			&i.CostMultiplier,
			&i.AccountBalanceMicro,
			&i.AccountSyncedAt,
			&i.Capabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableProductsForCatalog = `-- name: ListAvailableProductsForCatalog :many
SELECT
    p.id            AS product_id,
    s.code          AS service_code,
    s.name          AS service_name,
    s.name_tr       AS service_name_tr,
    s.icon_url,
    c.iso2          AS country_iso2,
    c.name_tr       AS country_name_tr,
    c.phone_code,
    min(o.cost_micro)::bigint AS min_cost_micro,
    sum(o.stock)::bigint      AS total_stock
FROM products p
JOIN services  s ON s.id = p.service_id
JOIN countries c ON c.id = p.country_id
JOIN provider_offers o ON o.product_id = p.id
JOIN providers pr ON pr.id = o.provider_id AND pr.is_active
WHERE p.is_active AND p.kind = 'SMS_ACTIVATION'
  AND p.verification_type = 'sms'
  AND s.is_visible AND c.is_visible
  -- STOKSUZ SATIRLAR NORMALDE GİZLENİR (FR-306): kullanıcıyı parasının
  -- çekileceği ama numara gelmeyeceği bir akışa sokmamak için.
  --
  -- TEK İSTİSNA: kullanıcının KENDİ ÜLKESİ. Türkiye'yi listeden tamamen
  -- çıkarmak, Türkiye'den bakan kullanıcıya "bu site Türk numarası satmıyor"
  -- dedirtiyor — oysa doğrusu "şu an stok yok". Satır GÖRÜNÜR ama
  -- ` + "`" + `inStock: false` + "`" + ` gelir ve arayüz onu SEÇİLEMEZ gösterir.
  AND ((o.is_available AND o.stock > 0) OR c.iso2 = 'TR')
  AND ($1::text IS NULL OR s.code = $1::text)
  AND ($2::text  IS NULL OR c.iso2 = $2::text)
GROUP BY p.id, s.code, s.name, s.name_tr, s.icon_url, c.iso2, c.name_tr, c.phone_code
ORDER BY s.code, (c.iso2 = 'TR') DESC, c.name_tr
`

type ListAvailableProductsForCatalogParams struct {
	ServiceCode *string
	CountryIso  *string
}

type ListAvailableProductsForCatalogRow struct {
	ProductID     int64
	ServiceCode   string
	ServiceName   string
	ServiceNameTr string
	IconUrl       string
	CountryIso2   string
	CountryNameTr string
	PhoneCode     string
	MinCostMicro  int64
	TotalStock    int64
}

// Kullanıcıya gösterilecek katalog: en az bir sağlayıcıda stoklu ürünler.
// TÜRKİYE HER ZAMAN ÖNCE.
//
// Kullanıcıların çoğu Türkiye'den ve en çok aradıkları ülke bu. Alfabetik
// sırada "Türkiye" 190 ülkenin sonlarında kalıyor ve kullanıcı her seferinde
// listeyi sonuna kadar kaydırıyor. Sıralama SUNUCUDA yapılır: istemcide
// yapılsaydı her istemci kendi kuralını uygular, mobil ve masaüstü farklı
// sıralanırdı.
func (q *Queries) ListAvailableProductsForCatalog(ctx context.Context, arg ListAvailableProductsForCatalogParams) ([]ListAvailableProductsForCatalogRow, error) {
	rows, err := q.db.Query(ctx, listAvailableProductsForCatalog, arg.ServiceCode, arg.CountryIso)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableProductsForCatalogRow{}
	for rows.Next() {
		var i ListAvailableProductsForCatalogRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ServiceCode,
			&i.ServiceName,
			&i.ServiceNameTr,
			&i.IconUrl,
			&i.CountryIso2,
			&i.CountryNameTr,
			&i.PhoneCode,
			&i.MinCostMicro,
			&i.TotalStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDimensionMaps = `-- name: ListDimensionMaps :many
SELECT provider_id, dimension, local_id, remote_code, synced_at FROM provider_dimension_maps
WHERE provider_id = $1 AND dimension = $2
ORDER BY local_id
`

type ListDimensionMapsParams struct {
	ProviderID int64
	Dimension  string
}

func (q *Queries) ListDimensionMaps(ctx context.Context, arg ListDimensionMapsParams) ([]ProviderDimensionMap, error) {
	rows, err := q.db.Query(ctx, listDimensionMaps, arg.ProviderID, arg.Dimension)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderDimensionMap{}
	for rows.Next() {
		var i ProviderDimensionMap
		if err := rows.Scan(
			&i.ProviderID,
			&i.Dimension,
			&i.LocalID,
			&i.RemoteCode,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffersForProduct = `-- name: ListOffersForProduct :many
SELECT o.provider_id, o.product_id, o.cost_micro, o.cost_currency, o.stock, o.is_available, o.synced_at, pr.name AS provider_name, pr.protocol, pr.priority, pr.cost_multiplier
FROM provider_offers o
JOIN providers pr ON pr.id = o.provider_id
WHERE o.product_id = $1 AND o.is_available AND o.stock > 0 AND pr.is_active
ORDER BY o.cost_micro, pr.priority
`

type ListOffersForProductRow struct {
	ProviderID     int64
	ProductID      int64
	CostMicro      int64
	CostCurrency   CurrencyCode
	Stock          int32
	IsAvailable    bool
	SyncedAt       time.Time
	ProviderName   string
	Protocol       ProviderProtocol
	Priority       int32
	CostMultiplier pgtype.Numeric
}

// Bir ürün için sağlayıcı teklifleri; en ucuz önce.
func (q *Queries) ListOffersForProduct(ctx context.Context, productID int64) ([]ListOffersForProductRow, error) {
	rows, err := q.db.Query(ctx, listOffersForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOffersForProductRow{}
	for rows.Next() {
		var i ListOffersForProductRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProductID,
			&i.CostMicro,
			&i.CostCurrency,
			&i.Stock,
			&i.IsAvailable,
			&i.SyncedAt,
			&i.ProviderName,
			&i.Protocol,
			&i.Priority,
			&i.CostMultiplier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersForAdmin = `-- name: ListProvidersForAdmin :many
SELECT
    p.id, p.name, p.protocol, p.base_url, p.is_active, p.priority,
    p.cost_multiplier, p.capabilities,
    -- COALESCE ZORUNLU: api_key_enc NULL ise length() de NULL döner ve
    -- ` + "`" + `bool` + "`" + ` alana tarama "cannot scan NULL into *bool" ile ÇÖKER — yani
    -- anahtarı henüz kurulmamış TEK bir sağlayıcı, tüm listeyi 500 yapardı.
    -- test: internal/transport/http/handler/admin_integration_test.go#TestListProvidersNeverReturnsAPIKey
    COALESCE(length(p.api_key_enc) > 0, false)::bool AS has_api_key,
    p.account_balance_micro, p.account_synced_at,
    p.created_at, p.updated_at
FROM providers p
ORDER BY p.priority, p.name
`

type ListProvidersForAdminRow struct {
	ID                  int64
	Name                string
	Protocol            ProviderProtocol
	BaseUrl             string
	IsActive            bool
	Priority            int32
	CostMultiplier      pgtype.Numeric
	Capabilities        []byte
	HasApiKey           bool
	AccountBalanceMicro int64
	AccountSyncedAt     *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Yönetim sağlayıcı listesi.
//
// 🔴 api_key_enc SEÇİLMEZ. Şifreli hâli bile dışarı verilmez: panelde
// gösterilecek bir şey değil ve varlığı/uzunluğu bilgi sızdırır.
// Anahtarın TANIMLI OLUP OLMADIĞI yeterli bilgidir.
func (q *Queries) ListProvidersForAdmin(ctx context.Context) ([]ListProvidersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listProvidersForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProvidersForAdminRow{}
	for rows.Next() {
		var i ListProvidersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Protocol,
			&i.BaseUrl,
			&i.IsActive,
			&i.Priority,
			&i.CostMultiplier,
			&i.Capabilities,
			&i.HasApiKey,
			&i.AccountBalanceMicro,
			&i.AccountSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRentalCountriesForService = `-- name: ListRentalCountriesForService :many
SELECT DISTINCT
    c.iso2 AS country_iso2, c.name AS country_name, c.name_tr AS country_name_tr,
    c.phone_code,
    -- DISTINCT ile ORDER BY ifadeleri seçim listesinde OLMAK ZORUNDA.
    -- Bu iki sütun yalnız sıralama içindir; DTO'ya taşınmaz.
    (c.iso2 = 'TR') AS is_home,
    coalesce(nullif(c.name_tr, ''), c.name) AS sort_name
FROM products p
JOIN services  s ON s.id = p.service_id
JOIN countries c ON c.id = p.country_id
JOIN provider_offers o ON o.product_id = p.id AND o.is_available AND o.stock > 0
JOIN providers pr ON pr.id = o.provider_id AND pr.is_active
WHERE p.kind = 'SMS_RENTAL' AND p.is_active
  AND s.code = $1 AND s.is_visible AND c.is_visible
ORDER BY is_home DESC, sort_name
`

type ListRentalCountriesForServiceRow struct {
	CountryIso2   string
	CountryName   string
	CountryNameTr string
	PhoneCode     string
	IsHome        bool
	SortName      string
}

func (q *Queries) ListRentalCountriesForService(ctx context.Context, serviceCode string) ([]ListRentalCountriesForServiceRow, error) {
	rows, err := q.db.Query(ctx, listRentalCountriesForService, serviceCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRentalCountriesForServiceRow{}
	for rows.Next() {
		var i ListRentalCountriesForServiceRow
		if err := rows.Scan(
			&i.CountryIso2,
			&i.CountryName,
			&i.CountryNameTr,
			&i.PhoneCode,
			&i.IsHome,
			&i.SortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRentalDurationsForCatalog = `-- name: ListRentalDurationsForCatalog :many
SELECT
    p.duration_minutes,
    min(o.cost_micro)::bigint AS min_cost_micro,
    sum(o.stock)::bigint      AS total_stock
FROM products p
JOIN provider_offers o ON o.product_id = p.id AND o.is_available AND o.stock > 0
JOIN providers pr ON pr.id = o.provider_id AND pr.is_active
JOIN services s ON s.id = p.service_id
JOIN countries c ON c.id = p.country_id
WHERE p.kind = 'SMS_RENTAL' AND p.is_active
  AND s.code = $1 AND c.iso2 = $2
GROUP BY p.duration_minutes
ORDER BY p.duration_minutes
`

type ListRentalDurationsForCatalogParams struct {
	ServiceCode string
	CountryIso  string
}

type ListRentalDurationsForCatalogRow struct {
	DurationMinutes *int32
	MinCostMicro    int64
	TotalStock      int64
}

// Bir servis × ülke için kiralanabilir süreler ve en düşük maliyet.
//
// Fiyat BURADA DÖNMEZ: kullanıcıya gösterilen fiyat teklif (quote) ile
// verilir. Buradaki maliyet yalnız SIRALAMA içindir ve dışa açılmaz.
func (q *Queries) ListRentalDurationsForCatalog(ctx context.Context, arg ListRentalDurationsForCatalogParams) ([]ListRentalDurationsForCatalogRow, error) {
	rows, err := q.db.Query(ctx, listRentalDurationsForCatalog, arg.ServiceCode, arg.CountryIso)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRentalDurationsForCatalogRow{}
	for rows.Next() {
		var i ListRentalDurationsForCatalogRow
		if err := rows.Scan(&i.DurationMinutes, &i.MinCostMicro, &i.TotalStock); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRentalServicesWithStock = `-- name: ListRentalServicesWithStock :many
SELECT
    s.code AS service_code, s.name AS service_name, s.name_tr AS service_name_tr,
    s.icon_url,
    count(DISTINCT c.id)::bigint AS country_count,
    count(DISTINCT p.duration_minutes)::bigint AS duration_count
FROM products p
JOIN services  s ON s.id = p.service_id
JOIN countries c ON c.id = p.country_id
JOIN provider_offers o ON o.product_id = p.id AND o.is_available AND o.stock > 0
JOIN providers pr ON pr.id = o.provider_id AND pr.is_active
WHERE p.kind = 'SMS_RENTAL' AND p.is_active
  AND s.is_visible AND c.is_visible
GROUP BY s.code, s.name, s.name_tr, s.icon_url
ORDER BY s.name
`

type ListRentalServicesWithStockRow struct {
	ServiceCode   string
	ServiceName   string
	ServiceNameTr string
	IconUrl       string
	CountryCount  int64
	DurationCount int64
}

// Kiralık ızgarası: en az bir ülke×sürede stoklu servisler.
func (q *Queries) ListRentalServicesWithStock(ctx context.Context) ([]ListRentalServicesWithStockRow, error) {
	rows, err := q.db.Query(ctx, listRentalServicesWithStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRentalServicesWithStockRow{}
	for rows.Next() {
		var i ListRentalServicesWithStockRow
		if err := rows.Scan(
			&i.ServiceCode,
			&i.ServiceName,
			&i.ServiceNameTr,
			&i.IconUrl,
			&i.CountryCount,
			&i.DurationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesWithStock = `-- name: ListServicesWithStock :many
SELECT
    s.code          AS service_code,
    s.name          AS service_name,
    s.name_tr       AS service_name_tr,
    s.icon_url,
    count(DISTINCT c.id)::bigint AS country_count,
    min(o.cost_micro)::bigint    AS min_cost_micro
FROM products p
JOIN services  s ON s.id = p.service_id
JOIN countries c ON c.id = p.country_id
JOIN provider_offers o ON o.product_id = p.id AND o.is_available AND o.stock > 0
JOIN providers pr ON pr.id = o.provider_id AND pr.is_active
WHERE p.is_active AND p.kind = 'SMS_ACTIVATION'
  AND p.verification_type = 'sms'
  AND s.is_visible AND c.is_visible
GROUP BY s.code, s.name, s.name_tr, s.icon_url
ORDER BY s.name
`

type ListServicesWithStockRow struct {
	ServiceCode   string
	ServiceName   string
	ServiceNameTr string
	IconUrl       string
	CountryCount  int64
	MinCostMicro  int64
}

// Servis IZGARASI için özet: yalnız en az bir ülkede STOKLU olan servisler,
// her biri için stoklu ülke sayısı.
//
// NEDEN AYRI BİR SORGU: gerçek katalogda 9768 stoklu servis×ülke kombinasyonu
// var ve hepsini tek yanıtta göndermek 1,09 MB ediyordu. Mobilde 4G'de bu
// kabul edilemez (docs/frontend-contract.md §8). Izgara yalnız servisleri
// gösterir; ülkeler servis seçilince ayrıca çekilir (~6 KB).
func (q *Queries) ListServicesWithStock(ctx context.Context) ([]ListServicesWithStockRow, error) {
	rows, err := q.db.Query(ctx, listServicesWithStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesWithStockRow{}
	for rows.Next() {
		var i ListServicesWithStockRow
		if err := rows.Scan(
			&i.ServiceCode,
			&i.ServiceName,
			&i.ServiceNameTr,
			&i.IconUrl,
			&i.CountryCount,
			&i.MinCostMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleCountries = `-- name: ListVisibleCountries :many
SELECT id, iso2, name, name_tr, phone_code, is_visible, supports_rent, created_at, updated_at FROM countries WHERE is_visible
ORDER BY (iso2 = 'TR') DESC, coalesce(nullif(name_tr, ''), name)
`

func (q *Queries) ListVisibleCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listVisibleCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Iso2,
			&i.Name,
			&i.NameTr,
			&i.PhoneCode,
			&i.IsVisible,
			&i.SupportsRent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleServices = `-- name: ListVisibleServices :many
SELECT id, code, name, name_tr, icon_url, is_visible, sort_order, created_at, updated_at FROM services WHERE is_visible ORDER BY sort_order, name
`

func (q *Queries) ListVisibleServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listVisibleServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.NameTr,
			&i.IconUrl,
			&i.IsVisible,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleOffersUnavailable = `-- name: MarkStaleOffersUnavailable :execrows
UPDATE provider_offers SET is_available = false, stock = 0
WHERE provider_id = $1 AND synced_at < $2 AND is_available
`

type MarkStaleOffersUnavailableParams struct {
	ProviderID int64
	SyncedAt   time.Time
}

// Senkron turunda görülmeyen teklifler "yok" sayılır. Aksi halde sağlayıcının
// listeden çıkardığı bir kombinasyon sonsuza kadar stokta görünürdü.
func (q *Queries) MarkStaleOffersUnavailable(ctx context.Context, arg MarkStaleOffersUnavailableParams) (int64, error) {
	result, err := q.db.Exec(ctx, markStaleOffersUnavailable, arg.ProviderID, arg.SyncedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveCountryRef = `-- name: ResolveCountryRef :one
SELECT iso2, name_tr, phone_code FROM country_reference WHERE name_key = lower($1)
`

type ResolveCountryRefRow struct {
	Iso2      string
	NameTr    string
	PhoneCode string
}

// Sağlayıcının İngilizce ülke adını ISO2 + Türkçe ad + telefon koduna çevirir.
func (q *Queries) ResolveCountryRef(ctx context.Context, nameKey string) (ResolveCountryRefRow, error) {
	row := q.db.QueryRow(ctx, resolveCountryRef, nameKey)
	var i ResolveCountryRefRow
	err := row.Scan(&i.Iso2, &i.NameTr, &i.PhoneCode)
	return i, err
}

const resolveDimensionLocal = `-- name: ResolveDimensionLocal :one
SELECT local_id FROM provider_dimension_maps
WHERE provider_id = $1 AND dimension = $2 AND remote_code = $3
`

type ResolveDimensionLocalParams struct {
	ProviderID int64
	Dimension  string
	RemoteCode string
}

// Sağlayıcının boyut kodunu YEREL kimliğe çevirir.
//
// Teklif senkronu eskiden ülkeyi `countries.iso2` üzerinden arıyordu. Bu, ancak
// sağlayıcının kodu tesadüfen ISO2 ise çalışır; HeroSMS "62" gönderir ve arama
// boş döner. Sağlayıcı kodu ile yerel kimlik arasındaki köprü BURASIDIR.
func (q *Queries) ResolveDimensionLocal(ctx context.Context, arg ResolveDimensionLocalParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveDimensionLocal, arg.ProviderID, arg.Dimension, arg.RemoteCode)
	var local_id int64
	err := row.Scan(&local_id)
	return local_id, err
}

const setProviderActive = `-- name: SetProviderActive :exec
UPDATE providers SET is_active = $2 WHERE id = $1
`

type SetProviderActiveParams struct {
	ID       int64
	IsActive bool
}

func (q *Queries) SetProviderActive(ctx context.Context, arg SetProviderActiveParams) error {
	_, err := q.db.Exec(ctx, setProviderActive, arg.ID, arg.IsActive)
	return err
}

const setServiceIcon = `-- name: SetServiceIcon :one
UPDATE services SET icon_url = $1, updated_at = now()
WHERE code = $2
RETURNING code, name, icon_url
`

type SetServiceIconParams struct {
	IconUrl string
	Code    string
}

type SetServiceIconRow struct {
	Code    string
	Name    string
	IconUrl string
}

// Servis logosunu ayarlar. Yol `web/public/` köküne göredir: /servis-logolari/wa.svg
func (q *Queries) SetServiceIcon(ctx context.Context, arg SetServiceIconParams) (SetServiceIconRow, error) {
	row := q.db.QueryRow(ctx, setServiceIcon, arg.IconUrl, arg.Code)
	var i SetServiceIconRow
	err := row.Scan(&i.Code, &i.Name, &i.IconUrl)
	return i, err
}

const updateProviderAPIKey = `-- name: UpdateProviderAPIKey :exec
UPDATE providers SET api_key_enc = $1, updated_at = now() WHERE id = $2
`

type UpdateProviderAPIKeyParams struct {
	ApiKeyEnc []byte
	ID        int64
}

// API anahtarı güncelleme — AYRI bir sorgu.
//
// Diğer ayarlarla aynı UPDATE'e konsaydı, ayar değiştiren her istek anahtarı
// da yazardı ve boş bir alan anahtarı SİLERDİ. Ayrı tutmak, "kaydet"e basmanın
// anahtarı yanlışlıkla silmesini imkânsız kılar.
// test: internal/transport/http/handler/admin_integration_test.go#TestSavingProviderSettingsDoesNotEraseAPIKey
func (q *Queries) UpdateProviderAPIKey(ctx context.Context, arg UpdateProviderAPIKeyParams) error {
	_, err := q.db.Exec(ctx, updateProviderAPIKey, arg.ApiKeyEnc, arg.ID)
	return err
}

const updateProviderBalance = `-- name: UpdateProviderBalance :exec
UPDATE providers SET account_balance_micro = $2, account_synced_at = now() WHERE id = $1
`

type UpdateProviderBalanceParams struct {
	ID                  int64
	AccountBalanceMicro int64
}

func (q *Queries) UpdateProviderBalance(ctx context.Context, arg UpdateProviderBalanceParams) error {
	_, err := q.db.Exec(ctx, updateProviderBalance, arg.ID, arg.AccountBalanceMicro)
	return err
}

const updateProviderSettings = `-- name: UpdateProviderSettings :one
UPDATE providers SET
    base_url        = $1,
    is_active       = $2,
    priority        = $3,
    cost_multiplier = $4,
    updated_at      = now()
WHERE id = $5
RETURNING id, name, protocol, base_url, is_active, priority, cost_multiplier
`

type UpdateProviderSettingsParams struct {
	BaseUrl        string
	IsActive       bool
	Priority       int32
	CostMultiplier pgtype.Numeric
	ID             int64
}

type UpdateProviderSettingsRow struct {
	ID             int64
	Name           string
	Protocol       ProviderProtocol
	BaseUrl        string
	IsActive       bool
	Priority       int32
	CostMultiplier pgtype.Numeric
}

// Sağlayıcı ayarları. API ANAHTARI BURADAN GÜNCELLENMEZ — ayrı bir yol var.
func (q *Queries) UpdateProviderSettings(ctx context.Context, arg UpdateProviderSettingsParams) (UpdateProviderSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateProviderSettings,
		arg.BaseUrl,
		arg.IsActive,
		arg.Priority,
		arg.CostMultiplier,
		arg.ID,
	)
	var i UpdateProviderSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.IsActive,
		&i.Priority,
		&i.CostMultiplier,
	)
	return i, err
}

const upsertCountry = `-- name: UpsertCountry :one
INSERT INTO countries (iso2, name, name_tr, phone_code, supports_rent)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (iso2) DO UPDATE
    SET name = EXCLUDED.name,
        phone_code = EXCLUDED.phone_code,
        supports_rent = EXCLUDED.supports_rent,
        name_tr = CASE WHEN countries.name_tr = '' THEN EXCLUDED.name_tr ELSE countries.name_tr END
RETURNING id, iso2, name, name_tr, phone_code, is_visible, supports_rent, created_at, updated_at
`

type UpsertCountryParams struct {
	Iso2         string
	Name         string
	NameTr       string
	PhoneCode    string
	SupportsRent bool
}

func (q *Queries) UpsertCountry(ctx context.Context, arg UpsertCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, upsertCountry,
		arg.Iso2,
		arg.Name,
		arg.NameTr,
		arg.PhoneCode,
		arg.SupportsRent,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Iso2,
		&i.Name,
		&i.NameTr,
		&i.PhoneCode,
		&i.IsVisible,
		&i.SupportsRent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDimensionMap = `-- name: UpsertDimensionMap :exec

INSERT INTO provider_dimension_maps (provider_id, dimension, local_id, remote_code)
VALUES ($1,$2,$3,$4)
ON CONFLICT (provider_id, dimension, local_id)
DO UPDATE SET remote_code = EXCLUDED.remote_code, synced_at = now()
`

type UpsertDimensionMapParams struct {
	ProviderID int64
	Dimension  string
	LocalID    int64
	RemoteCode string
}

// ─────────────────────── Boyut eşleştirme ───────────────────────
func (q *Queries) UpsertDimensionMap(ctx context.Context, arg UpsertDimensionMapParams) error {
	_, err := q.db.Exec(ctx, upsertDimensionMap,
		arg.ProviderID,
		arg.Dimension,
		arg.LocalID,
		arg.RemoteCode,
	)
	return err
}

const upsertOffer = `-- name: UpsertOffer :exec

INSERT INTO provider_offers (provider_id, product_id, cost_micro, cost_currency, stock, is_available, synced_at)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (provider_id, product_id) DO UPDATE
    SET cost_micro = EXCLUDED.cost_micro,
        stock = EXCLUDED.stock,
        is_available = EXCLUDED.is_available,
        synced_at = EXCLUDED.synced_at
`

type UpsertOfferParams struct {
	ProviderID   int64
	ProductID    int64
	CostMicro    int64
	CostCurrency CurrencyCode
	Stock        int32
	IsAvailable  bool
	SyncedAt     time.Time
}

// ─────────────────────── Fiyat/stok önbelleği ───────────────────────
// synced_at UYGULAMADAN gelir, now() DEĞİL.
//
// Bayat teklif tespiti bu alanı bir eşikle karşılaştırır; yazım veritabanı
// saatini, karşılaştırma uygulama saatini kullanırsa aradaki kayma tüm
// teklifleri sessizce "yok" işaretler. İki taraf AYNI saat kaynağını kullanmalı.
func (q *Queries) UpsertOffer(ctx context.Context, arg UpsertOfferParams) error {
	_, err := q.db.Exec(ctx, upsertOffer,
		arg.ProviderID,
		arg.ProductID,
		arg.CostMicro,
		arg.CostCurrency,
		arg.Stock,
		arg.IsAvailable,
		arg.SyncedAt,
	)
	return err
}

const upsertProduct = `-- name: UpsertProduct :one

INSERT INTO products (kind, service_id, country_id, verification_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kind, service_id, country_id, operator_id, verification_type,
             duration_minutes, dimension_a_id)
DO UPDATE SET is_active = true
RETURNING id, kind, service_id, country_id, operator_id, verification_type, duration_minutes, dimension_a_id, attributes, is_active, created_at
`

type UpsertProductParams struct {
	Kind             ProductKind
	ServiceID        *int64
	CountryID        *int64
	VerificationType VerificationType
}

// ─────────────────────── Ürün ───────────────────────
func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProduct,
		arg.Kind,
		arg.ServiceID,
		arg.CountryID,
		arg.VerificationType,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ServiceID,
		&i.CountryID,
		&i.OperatorID,
		&i.VerificationType,
		&i.DurationMinutes,
		&i.DimensionAID,
		&i.Attributes,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRentalProduct = `-- name: UpsertRentalProduct :one
INSERT INTO products (kind, service_id, country_id, verification_type, duration_minutes)
VALUES ('SMS_RENTAL', $1, $2, 'sms', $3)
ON CONFLICT (kind, service_id, country_id, operator_id, verification_type,
             duration_minutes, dimension_a_id)
DO UPDATE SET is_active = true
RETURNING id, kind, service_id, country_id, operator_id, verification_type, duration_minutes, dimension_a_id, attributes, is_active, created_at
`

type UpsertRentalProductParams struct {
	ServiceID       *int64
	CountryID       *int64
	DurationMinutes *int32
}

// Kiralık ürün. Aktivasyondan TEK FARKI süre boyutunun dolu olması —
// ama o fark benzersizlik anahtarının parçası olduğu için aynı servis×ülke
// için sekiz ayrı ürün (sekiz süre) yan yana durabilir.
func (q *Queries) UpsertRentalProduct(ctx context.Context, arg UpsertRentalProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertRentalProduct, arg.ServiceID, arg.CountryID, arg.DurationMinutes)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ServiceID,
		&i.CountryID,
		&i.OperatorID,
		&i.VerificationType,
		&i.DurationMinutes,
		&i.DimensionAID,
		&i.Attributes,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const upsertService = `-- name: UpsertService :one

INSERT INTO services (code, name, name_tr, sort_order)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO UPDATE
    SET name = EXCLUDED.name,
        -- Türkçe ad ve görünürlük ADMIN tarafından yönetilir; senkron bunları EZMEZ.
        name_tr = CASE WHEN services.name_tr = '' THEN EXCLUDED.name_tr ELSE services.name_tr END
RETURNING id, code, name, name_tr, icon_url, is_visible, sort_order, created_at, updated_at
`

type UpsertServiceParams struct {
	Code      string
	Name      string
	NameTr    string
	SortOrder int32
}

// ─────────────────────── Boyutlar ───────────────────────
func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, upsertService,
		arg.Code,
		arg.Name,
		arg.NameTr,
		arg.SortOrder,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NameTr,
		&i.IconUrl,
		&i.IsVisible,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
