// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deposits.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const approveDeposit = `-- name: ApproveDeposit :one
UPDATE deposits SET
    status              = 'COMPLETED',
    credited_minor      = $1,
    admin_note          = $2,
    reviewed_by_user_id = $3,
    reviewed_at         = $4
WHERE public_id = $5 AND status = 'PENDING'
RETURNING id, public_id, user_id, method_id, method_name, amount_minor, credited_minor, status, tx_hash, network, receipt_path, user_note, admin_note, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at
`

type ApproveDepositParams struct {
	CreditedMinor    int64
	AdminNote        string
	ReviewedByUserID *int64
	ReviewedAt       *time.Time
	PublicID         uuid.UUID
}

// İKİNCİ SAVUNMA HATTI: `AND status = 'PENDING'` koşulu yarışta ikinci çağrıya
// SIFIR satır döndürür (pgx.ErrNoRows) — bu "zaten sonuçlandırılmış" demektir.
//
// 🔴 reviewed_at, status ile AYNI ifadede yazılır: deposit_reviewed_has_time
// CHECK'i (00008_orders.sql) iki adımlı yazımda 23514 ile düşer.
func (q *Queries) ApproveDeposit(ctx context.Context, arg ApproveDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, approveDeposit,
		arg.CreditedMinor,
		arg.AdminNote,
		arg.ReviewedByUserID,
		arg.ReviewedAt,
		arg.PublicID,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.MethodID,
		&i.MethodName,
		&i.AmountMinor,
		&i.CreditedMinor,
		&i.Status,
		&i.TxHash,
		&i.Network,
		&i.ReceiptPath,
		&i.UserNote,
		&i.AdminNote,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countDepositsForAdmin = `-- name: CountDepositsForAdmin :one
SELECT count(*) FROM deposits d
WHERE ($1::deposit_status IS NULL
       OR d.status = $1::deposit_status)
`

func (q *Queries) CountDepositsForAdmin(ctx context.Context, status *DepositStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countDepositsForAdmin, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserDeposits = `-- name: CountUserDeposits :one
SELECT count(*) FROM deposits WHERE user_id = $1
`

func (q *Queries) CountUserDeposits(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserDeposits, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeposit = `-- name: CreateDeposit :one

INSERT INTO deposits (user_id, method_id, method_name, amount_minor,
                      tx_hash, network, user_note)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
RETURNING id, public_id, user_id, method_id, method_name, amount_minor, credited_minor, status, tx_hash, network, receipt_path, user_note, admin_note, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at
`

type CreateDepositParams struct {
	UserID      int64
	MethodID    *int64
	MethodName  string
	AmountMinor int64
	TxHash      *string
	Network     string
	UserNote    string
}

// Bakiye yükleme talepleri (FR-500 … FR-503).
//
// Ödeme YÖNTEMİ sorguları burada değil, queries/orders.sql içindedir
// (deposit_methods CRUD'u zaten yazılmıştı).
// 🔴 tx_hash HAVALEDE NULL BIRAKILIR, boş string yazılmaz: deposits_tx_hash_uniq
// kısmi indeksi (WHERE tx_hash IS NOT NULL) NULL'ları hariç tutar. ” yazılırsa
// kullanıcının İKİNCİ havale talebi 23505 alır ve bir daha havale bildiremez.
// test: deposit_integration_test.go#TestBankTransferDepositLeavesTxHashNull
func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, createDeposit,
		arg.UserID,
		arg.MethodID,
		arg.MethodName,
		arg.AmountMinor,
		arg.TxHash,
		arg.Network,
		arg.UserNote,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.MethodID,
		&i.MethodName,
		&i.AmountMinor,
		&i.CreditedMinor,
		&i.Status,
		&i.TxHash,
		&i.Network,
		&i.ReceiptPath,
		&i.UserNote,
		&i.AdminNote,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeposit = `-- name: GetDeposit :one
SELECT id, public_id, user_id, method_id, method_name, amount_minor, credited_minor, status, tx_hash, network, receipt_path, user_note, admin_note, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at FROM deposits WHERE public_id = $1
`

// Yönetim yolu: sahiplik kısıtı YOKTUR, izin kontrolü middleware'dedir
// (deposits:read / deposits:approve).
func (q *Queries) GetDeposit(ctx context.Context, publicID uuid.UUID) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDeposit, publicID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.MethodID,
		&i.MethodName,
		&i.AmountMinor,
		&i.CreditedMinor,
		&i.Status,
		&i.TxHash,
		&i.Network,
		&i.ReceiptPath,
		&i.UserNote,
		&i.AdminNote,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositForUser = `-- name: GetDepositForUser :one
SELECT id, public_id, user_id, method_id, method_name, amount_minor, credited_minor, status, tx_hash, network, receipt_path, user_note, admin_note, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at FROM deposits WHERE public_id = $1 AND user_id = $2
`

type GetDepositForUserParams struct {
	PublicID uuid.UUID
	UserID   int64
}

// SAHİPLİK SORGUNUN PARÇASIDIR (CLAUDE.md değişmez #7). Başkasının talebi ile
// var olmayan talep AYNI sonucu (sıfır satır) verir.
func (q *Queries) GetDepositForUser(ctx context.Context, arg GetDepositForUserParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositForUser, arg.PublicID, arg.UserID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.MethodID,
		&i.MethodName,
		&i.AmountMinor,
		&i.CreditedMinor,
		&i.Status,
		&i.TxHash,
		&i.Network,
		&i.ReceiptPath,
		&i.UserNote,
		&i.AdminNote,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepositsForAdmin = `-- name: ListDepositsForAdmin :many
SELECT d.id, d.public_id, d.user_id, d.method_id, d.method_name, d.amount_minor, d.credited_minor, d.status, d.tx_hash, d.network, d.receipt_path, d.user_note, d.admin_note, d.rejection_reason, d.reviewed_by_user_id, d.reviewed_at, d.created_at, d.updated_at,
       u.public_id AS user_public_id,
       u.email     AS user_email,
       u.username  AS user_username
FROM deposits d
JOIN users u ON u.id = d.user_id
WHERE ($1::deposit_status IS NULL
       OR d.status = $1::deposit_status)
ORDER BY d.created_at DESC
LIMIT $3 OFFSET $2
`

type ListDepositsForAdminParams struct {
	Status *DepositStatus
	Off    int32
	Lim    int32
}

type ListDepositsForAdminRow struct {
	ID               int64
	PublicID         uuid.UUID
	UserID           int64
	MethodID         *int64
	MethodName       string
	AmountMinor      int64
	CreditedMinor    int64
	Status           DepositStatus
	TxHash           *string
	Network          string
	ReceiptPath      string
	UserNote         string
	AdminNote        string
	RejectionReason  string
	ReviewedByUserID *int64
	ReviewedAt       *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	UserPublicID     uuid.UUID
	UserEmail        string
	UserUsername     string
}

// Sayısal id dışarı verilmez: kullanıcı users.public_id ile gösterilir.
func (q *Queries) ListDepositsForAdmin(ctx context.Context, arg ListDepositsForAdminParams) ([]ListDepositsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listDepositsForAdmin, arg.Status, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepositsForAdminRow{}
	for rows.Next() {
		var i ListDepositsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.MethodID,
			&i.MethodName,
			&i.AmountMinor,
			&i.CreditedMinor,
			&i.Status,
			&i.TxHash,
			&i.Network,
			&i.ReceiptPath,
			&i.UserNote,
			&i.AdminNote,
			&i.RejectionReason,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserPublicID,
			&i.UserEmail,
			&i.UserUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDeposits = `-- name: ListUserDeposits :many
SELECT id, public_id, user_id, method_id, method_name, amount_minor, credited_minor, status, tx_hash, network, receipt_path, user_note, admin_note, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at FROM deposits
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListUserDepositsParams struct {
	UserID int64
	Off    int32
	Lim    int32
}

// deposits_user_idx (user_id, created_at DESC) tam olarak bu sıralamayı kullanır.
func (q *Queries) ListUserDeposits(ctx context.Context, arg ListUserDepositsParams) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listUserDeposits, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.MethodID,
			&i.MethodName,
			&i.AmountMinor,
			&i.CreditedMinor,
			&i.Status,
			&i.TxHash,
			&i.Network,
			&i.ReceiptPath,
			&i.UserNote,
			&i.AdminNote,
			&i.RejectionReason,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDepositForUpdate = `-- name: LockDepositForUpdate :one
SELECT id, public_id, user_id, method_id, method_name, amount_minor, credited_minor, status, tx_hash, network, receipt_path, user_note, admin_note, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at FROM deposits WHERE public_id = $1 FOR UPDATE
`

// ÇAĞIRANIN TRANSACTION'I İÇİNDE çağrılmalıdır. Kilit commit'e kadar tutulur;
// eşzamanlı onay istekleri burada sıraya girer. Kilitsiz okuyup sonra yazmak,
// iki yöneticinin (veya bir yöneticinin iki sekmesinin) aynı talebi iki kez
// onaylamasına ve bakiyenin iki kez artmasına yol açar.
// test: deposit_integration_test.go#TestApproveIsIdempotentUnderConcurrency
func (q *Queries) LockDepositForUpdate(ctx context.Context, publicID uuid.UUID) (Deposit, error) {
	row := q.db.QueryRow(ctx, lockDepositForUpdate, publicID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.MethodID,
		&i.MethodName,
		&i.AmountMinor,
		&i.CreditedMinor,
		&i.Status,
		&i.TxHash,
		&i.Network,
		&i.ReceiptPath,
		&i.UserNote,
		&i.AdminNote,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectDeposit = `-- name: RejectDeposit :one
UPDATE deposits SET
    status              = 'REJECTED',
    rejection_reason    = $1,
    admin_note          = $2,
    reviewed_by_user_id = $3,
    reviewed_at         = $4
WHERE public_id = $5 AND status = 'PENDING'
RETURNING id, public_id, user_id, method_id, method_name, amount_minor, credited_minor, status, tx_hash, network, receipt_path, user_note, admin_note, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at
`

type RejectDepositParams struct {
	RejectionReason  string
	AdminNote        string
	ReviewedByUserID *int64
	ReviewedAt       *time.Time
	PublicID         uuid.UUID
}

// Bakiyeye HİÇ dokunulmaz (FR-503); burada yalnız durum ve gerekçe yazılır.
func (q *Queries) RejectDeposit(ctx context.Context, arg RejectDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, rejectDeposit,
		arg.RejectionReason,
		arg.AdminNote,
		arg.ReviewedByUserID,
		arg.ReviewedAt,
		arg.PublicID,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.MethodID,
		&i.MethodName,
		&i.AmountMinor,
		&i.CreditedMinor,
		&i.Status,
		&i.TxHash,
		&i.Network,
		&i.ReceiptPath,
		&i.UserNote,
		&i.AdminNote,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setDepositReceipt = `-- name: SetDepositReceipt :one
UPDATE deposits SET receipt_path = $1
WHERE public_id = $2 AND user_id = $3 AND status = 'PENDING'
RETURNING id, public_id, user_id, method_id, method_name, amount_minor, credited_minor, status, tx_hash, network, receipt_path, user_note, admin_note, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at
`

type SetDepositReceiptParams struct {
	ReceiptPath string
	PublicID    uuid.UUID
	UserID      int64
}

// Dekont YALNIZ sahibi tarafından ve YALNIZ inceleme öncesinde eklenebilir:
// sonuçlandırılmış bir talebin kanıtını değiştirmek denetimi anlamsız kılar.
func (q *Queries) SetDepositReceipt(ctx context.Context, arg SetDepositReceiptParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, setDepositReceipt, arg.ReceiptPath, arg.PublicID, arg.UserID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.MethodID,
		&i.MethodName,
		&i.AmountMinor,
		&i.CreditedMinor,
		&i.Status,
		&i.TxHash,
		&i.Network,
		&i.ReceiptPath,
		&i.UserNote,
		&i.AdminNote,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
