// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type TokenPurpose string

const (
	TokenPurposeEMAILVERIFICATION TokenPurpose = "EMAIL_VERIFICATION"
	TokenPurposePASSWORDRESET     TokenPurpose = "PASSWORD_RESET"
)

func (e *TokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenPurpose(s)
	case string:
		*e = TokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenPurpose: %T", src)
	}
	return nil
}

type NullTokenPurpose struct {
	TokenPurpose TokenPurpose
	Valid        bool // Valid is true if TokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.TokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenPurpose), nil
}

type UserStatus string

const (
	UserStatusPENDINGVERIFICATION UserStatus = "PENDING_VERIFICATION"
	UserStatusACTIVE              UserStatus = "ACTIVE"
	UserStatusSUSPENDED           UserStatus = "SUSPENDED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID          int64
	ActorUserID *int64
	Action      string
	EntityType  string
	EntityID    string
	Before      []byte
	After       []byte
	Ip          *netip.Addr
	UserAgent   string
	RequestID   string
	CreatedAt   time.Time
}

type AuthToken struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	Purpose   TokenPurpose
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Permission struct {
	ID          int64
	Code        string
	Description string
}

type Role struct {
	ID          int64
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   time.Time
}

type RolePermission struct {
	RoleID       int64
	PermissionID int64
}

type Session struct {
	ID         string
	UserID     int64
	Ip         *netip.Addr
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
}

type User struct {
	ID               int64
	PublicID         uuid.UUID
	Email            string
	EmailVerifiedAt  *time.Time
	Username         string
	PasswordHash     string
	BalanceMinor     int64
	Status           UserStatus
	ReferralCode     *string
	ReferredByUserID *int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
}

type UserRole struct {
	UserID    int64
	RoleID    int64
	GrantedAt time.Time
}
