// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CurrencyCode string

const (
	CurrencyCodeTRY CurrencyCode = "TRY"
	CurrencyCodeUSD CurrencyCode = "USD"
)

func (e *CurrencyCode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrencyCode(s)
	case string:
		*e = CurrencyCode(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrencyCode: %T", src)
	}
	return nil
}

type NullCurrencyCode struct {
	CurrencyCode CurrencyCode
	Valid        bool // Valid is true if CurrencyCode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrencyCode) Scan(value interface{}) error {
	if value == nil {
		ns.CurrencyCode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrencyCode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrencyCode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrencyCode), nil
}

type DepositMethodKind string

const (
	DepositMethodKindBANKTRANSFER DepositMethodKind = "BANK_TRANSFER"
	DepositMethodKindCRYPTO       DepositMethodKind = "CRYPTO"
)

func (e *DepositMethodKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DepositMethodKind(s)
	case string:
		*e = DepositMethodKind(s)
	default:
		return fmt.Errorf("unsupported scan type for DepositMethodKind: %T", src)
	}
	return nil
}

type NullDepositMethodKind struct {
	DepositMethodKind DepositMethodKind
	Valid             bool // Valid is true if DepositMethodKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDepositMethodKind) Scan(value interface{}) error {
	if value == nil {
		ns.DepositMethodKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DepositMethodKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDepositMethodKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DepositMethodKind), nil
}

type DepositStatus string

const (
	DepositStatusPENDING   DepositStatus = "PENDING"
	DepositStatusCOMPLETED DepositStatus = "COMPLETED"
	DepositStatusREJECTED  DepositStatus = "REJECTED"
	DepositStatusREFUNDED  DepositStatus = "REFUNDED"
)

func (e *DepositStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DepositStatus(s)
	case string:
		*e = DepositStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DepositStatus: %T", src)
	}
	return nil
}

type NullDepositStatus struct {
	DepositStatus DepositStatus
	Valid         bool // Valid is true if DepositStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDepositStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DepositStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DepositStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDepositStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DepositStatus), nil
}

type LedgerType string

const (
	LedgerTypeDEPOSIT    LedgerType = "DEPOSIT"
	LedgerTypePURCHASE   LedgerType = "PURCHASE"
	LedgerTypeREFUND     LedgerType = "REFUND"
	LedgerTypeADJUSTMENT LedgerType = "ADJUSTMENT"
	LedgerTypeCOMMISSION LedgerType = "COMMISSION"
	LedgerTypeCHARGEBACK LedgerType = "CHARGEBACK"
)

func (e *LedgerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerType(s)
	case string:
		*e = LedgerType(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerType: %T", src)
	}
	return nil
}

type NullLedgerType struct {
	LedgerType LedgerType
	Valid      bool // Valid is true if LedgerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerType) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerType), nil
}

type OrderStatus string

const (
	OrderStatusPENDING   OrderStatus = "PENDING"
	OrderStatusCOMPLETED OrderStatus = "COMPLETED"
	OrderStatusCANCELLED OrderStatus = "CANCELLED"
	OrderStatusFAILED    OrderStatus = "FAILED"
	OrderStatusREFUNDED  OrderStatus = "REFUNDED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PricingScope string

const (
	PricingScopeGLOBAL         PricingScope = "GLOBAL"
	PricingScopeCOUNTRY        PricingScope = "COUNTRY"
	PricingScopeSERVICE        PricingScope = "SERVICE"
	PricingScopeSERVICECOUNTRY PricingScope = "SERVICE_COUNTRY"
	PricingScopePRODUCT        PricingScope = "PRODUCT"
)

func (e *PricingScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PricingScope(s)
	case string:
		*e = PricingScope(s)
	default:
		return fmt.Errorf("unsupported scan type for PricingScope: %T", src)
	}
	return nil
}

type NullPricingScope struct {
	PricingScope PricingScope
	Valid        bool // Valid is true if PricingScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPricingScope) Scan(value interface{}) error {
	if value == nil {
		ns.PricingScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PricingScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPricingScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PricingScope), nil
}

type ProductKind string

const (
	ProductKindSMSACTIVATION ProductKind = "SMS_ACTIVATION"
	ProductKindSMSRENTAL     ProductKind = "SMS_RENTAL"
)

func (e *ProductKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductKind(s)
	case string:
		*e = ProductKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductKind: %T", src)
	}
	return nil
}

type NullProductKind struct {
	ProductKind ProductKind
	Valid       bool // Valid is true if ProductKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductKind) Scan(value interface{}) error {
	if value == nil {
		ns.ProductKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductKind), nil
}

type ProviderProtocol string

const (
	ProviderProtocolFAKE      ProviderProtocol = "FAKE"
	ProviderProtocolHEROSMSV1 ProviderProtocol = "HEROSMS_V1"
	ProviderProtocolFIVESIM   ProviderProtocol = "FIVE_SIM"
)

func (e *ProviderProtocol) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderProtocol(s)
	case string:
		*e = ProviderProtocol(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderProtocol: %T", src)
	}
	return nil
}

type NullProviderProtocol struct {
	ProviderProtocol ProviderProtocol
	Valid            bool // Valid is true if ProviderProtocol is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderProtocol) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderProtocol, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderProtocol.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderProtocol) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderProtocol), nil
}

type RefundStatus string

const (
	RefundStatusNOTAPPLICABLE  RefundStatus = "NOT_APPLICABLE"
	RefundStatusPENDING        RefundStatus = "PENDING"
	RefundStatusRETRYSCHEDULED RefundStatus = "RETRY_SCHEDULED"
	RefundStatusREFUNDED       RefundStatus = "REFUNDED"
	RefundStatusDENIED         RefundStatus = "DENIED"
)

func (e *RefundStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RefundStatus(s)
	case string:
		*e = RefundStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RefundStatus: %T", src)
	}
	return nil
}

type NullRefundStatus struct {
	RefundStatus RefundStatus
	Valid        bool // Valid is true if RefundStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRefundStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RefundStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RefundStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRefundStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RefundStatus), nil
}

type TokenPurpose string

const (
	TokenPurposeEMAILVERIFICATION TokenPurpose = "EMAIL_VERIFICATION"
	TokenPurposePASSWORDRESET     TokenPurpose = "PASSWORD_RESET"
)

func (e *TokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenPurpose(s)
	case string:
		*e = TokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenPurpose: %T", src)
	}
	return nil
}

type NullTokenPurpose struct {
	TokenPurpose TokenPurpose
	Valid        bool // Valid is true if TokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.TokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenPurpose), nil
}

type UserStatus string

const (
	UserStatusPENDINGVERIFICATION UserStatus = "PENDING_VERIFICATION"
	UserStatusACTIVE              UserStatus = "ACTIVE"
	UserStatusSUSPENDED           UserStatus = "SUSPENDED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type VerificationType string

const (
	VerificationTypeSms  VerificationType = "sms"
	VerificationTypeCall VerificationType = "call"
)

func (e *VerificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationType(s)
	case string:
		*e = VerificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationType: %T", src)
	}
	return nil
}

type NullVerificationType struct {
	VerificationType VerificationType
	Valid            bool // Valid is true if VerificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationType) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationType), nil
}

type AuditLog struct {
	ID          int64
	ActorUserID *int64
	Action      string
	EntityType  string
	EntityID    string
	Before      []byte
	After       []byte
	Ip          *netip.Addr
	UserAgent   string
	RequestID   string
	CreatedAt   time.Time
}

type AuthToken struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	Purpose   TokenPurpose
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Country struct {
	ID           int64
	Iso2         string
	Name         string
	NameTr       string
	PhoneCode    string
	IsVisible    bool
	SupportsRent bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CountryReference struct {
	NameKey   string
	Iso2      string
	NameEn    string
	NameTr    string
	PhoneCode string
}

type Deposit struct {
	ID               int64
	PublicID         uuid.UUID
	UserID           int64
	MethodID         *int64
	MethodName       string
	AmountMinor      int64
	CreditedMinor    int64
	Status           DepositStatus
	TxHash           *string
	Network          string
	ReceiptPath      string
	UserNote         string
	AdminNote        string
	RejectionReason  string
	ReviewedByUserID *int64
	ReviewedAt       *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IdempotencyKey   *string
}

type DepositMethod struct {
	ID             int64
	PublicID       uuid.UUID
	Code           string
	Kind           DepositMethodKind
	Name           string
	Instructions   string
	Config         []byte
	MinAmountMinor int64
	MaxAmountMinor int64
	IsActive       bool
	SortOrder      int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type FxRate struct {
	ID        int64
	Base      CurrencyCode
	Quote     CurrencyCode
	Rate      pgtype.Numeric
	Source    string
	FetchedAt time.Time
}

type LedgerEntry struct {
	ID                int64
	UserID            int64
	AmountMinor       int64
	Currency          CurrencyCode
	EntryType         LedgerType
	ReferenceType     *string
	ReferenceID       *string
	BalanceAfterMinor int64
	IdempotencyKey    string
	CreatedByUserID   *int64
	Note              *string
	CreatedAt         time.Time
}

type LedgerReconciliation struct {
	UserID        int64
	Email         string
	CachedBalance int64
	LedgerBalance int64
	Drift         int32
}

type Operator struct {
	ID        int64
	CountryID int64
	Code      string
	Name      string
}

type Order struct {
	ID                        int64
	PublicID                  uuid.UUID
	UserID                    int64
	ProviderID                int64
	RemoteOrderID             string
	ProviderActivationID      *int64
	PhoneNumber               string
	VerificationType          VerificationType
	ProductID                 *int64
	ServiceCode               string
	ServiceName               string
	CountryIso2               string
	CountryName               string
	PhoneCode                 string
	QuoteID                   *int64
	PricePaidMinor            int64
	CostMicro                 int64
	FxRate                    pgtype.Numeric
	Status                    OrderStatus
	ExpiresAt                 time.Time
	CancellableAt             time.Time
	CompletedAt               *time.Time
	CancelledAt               *time.Time
	RefundedAt                *time.Time
	ProviderClosedAt          *time.Time
	CloseAttempts             int32
	CloseLastError            string
	ProviderRefundStatus      RefundStatus
	ProviderRefundAmountMinor int64
	RefundAttempts            int32
	RefundNextAttemptAt       *time.Time
	CancelReason              string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	// Sağlayıcıda kapatma denemesinin sahiplenme damgası (kira). NULL = sahipsiz.
	CloseClaimedAt *time.Time
}

type OrderMessage struct {
	ID            int64
	OrderID       int64
	ProviderOtpID string
	Code          string
	Body          string
	Sender        string
	ReceivedAt    time.Time
	CreatedAt     time.Time
}

type Permission struct {
	ID          int64
	Code        string
	Description string
}

type PriceQuote struct {
	ID             int64
	PublicID       uuid.UUID
	UserID         int64
	ProductID      int64
	ProviderID     int64
	CostMicro      int64
	CostCurrency   CurrencyCode
	FxRate         pgtype.Numeric
	MarginPercent  pgtype.Numeric
	PricingRuleID  *int64
	SellPriceMinor int64
	StockAtQuote   int32
	ExpiresAt      time.Time
	ConsumedAt     *time.Time
	CreatedAt      time.Time
}

type PricingRule struct {
	ID              int64
	Scope           PricingScope
	ServiceID       *int64
	CountryID       *int64
	ProductID       *int64
	MarginPercent   pgtype.Numeric
	FixedFeeMinor   int64
	MinPriceMinor   int64
	IsActive        bool
	ValidFrom       *time.Time
	ValidTo         *time.Time
	Note            string
	CreatedByUserID *int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Product struct {
	ID               int64
	Kind             ProductKind
	ServiceID        *int64
	CountryID        *int64
	OperatorID       *int64
	VerificationType VerificationType
	DurationMinutes  *int32
	DimensionAID     *int64
	Attributes       []byte
	IsActive         bool
	CreatedAt        time.Time
}

type Provider struct {
	ID                  int64
	Name                string
	Protocol            ProviderProtocol
	BaseUrl             string
	ApiKeyEnc           []byte
	IsActive            bool
	Priority            int32
	CostMultiplier      pgtype.Numeric
	AccountBalanceMicro int64
	AccountSyncedAt     *time.Time
	Capabilities        []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type ProviderDimensionMap struct {
	ProviderID int64
	Dimension  string
	LocalID    int64
	RemoteCode string
	SyncedAt   time.Time
}

type ProviderOffer struct {
	ProviderID   int64
	ProductID    int64
	CostMicro    int64
	CostCurrency CurrencyCode
	Stock        int32
	IsAvailable  bool
	SyncedAt     time.Time
}

type RentalDetail struct {
	OrderID       int64
	DurationHours int32
	RenewedCount  int32
	RentalEndsAt  time.Time
	CreatedAt     time.Time
}

type Role struct {
	ID          int64
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   time.Time
}

type RolePermission struct {
	RoleID       int64
	PermissionID int64
}

type Service struct {
	ID        int64
	Code      string
	Name      string
	NameTr    string
	IconUrl   string
	IsVisible bool
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID         string
	UserID     int64
	Ip         *netip.Addr
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
}

type User struct {
	ID               int64
	PublicID         uuid.UUID
	Email            string
	EmailVerifiedAt  *time.Time
	Username         string
	PasswordHash     string
	BalanceMinor     int64
	Status           UserStatus
	ReferralCode     *string
	ReferredByUserID *int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
}

type UserRole struct {
	UserID    int64
	RoleID    int64
	GrantedAt time.Time
}
