// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOrderClose = `-- name: ClaimOrderClose :one
UPDATE orders SET close_claimed_at = $1
WHERE id = $2
  AND provider_closed_at IS NULL
  AND status IN ('COMPLETED', 'CANCELLED', 'FAILED', 'REFUNDED')
  AND (close_claimed_at IS NULL OR close_claimed_at <= $3)
RETURNING id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at
`

type ClaimOrderCloseParams struct {
	Now              *time.Time
	ID               int64
	ClaimStaleBefore *time.Time
}

// SAHİPLENME: sağlayıcıda kapatma denemesini TEK bir işçiye verir.
//
// Kapatma bir HTTP çağrısı içerir; dış çağrı transaction içinde yapılmaz
// (değişmez #5), dolayısıyla satır kilidi çağrı boyunca tutulamaz —
// `GetOrderForUpdate` bir transaction dışında çağrıldığında kilit deyim
// biter bitmez bırakılır ve hiçbir şeyi korumaz. Bunun yerine satır koşullu
// bir UPDATE ile sahiplenilir: yarışı kaybeden işçi SIFIR satır alır
// (ConsumeQuote ile aynı desen) ve sağlayıcıya hiç gitmez.
//
// Kira süresi dolduğunda satır kendiliğinden yeniden uygun hâle gelir: çağrı
// sırasında ölen bir işçi satırı sonsuza kadar bloke edemez.
//
// `provider_closed_at IS NULL` koşulu da buradadır: zaten kapatılmış siparişe
// ikinci kez Cancel/Finish gönderilmez.
//
// 🔴 DURUM SÜZGECİ SAHİPLENMENİN PARÇASIDIR, ayrı bir `if` değil.
//
// Süzgeç Go tarafında dururken kapatılabilir olmayan bir satır (PENDING /
// ACTIVE) de sahiplenilebiliyordu: işçi satırı alıyor, durumu görüp
// `ReleaseOrderClose` ile bırakıyordu. O iki adımın ARASINDA sipariş terminal
// olursa, terminal geçişin doğurduğu kapatma goroutine'i sahiplenmeyi
// KAYBEDİYOR ve sessizce nil dönüyordu; hemen ardından gelen `release` de
// kirayı siliyordu. Sonuç: terminal sipariş, `provider_closed_at IS NULL` ve
// sağlayıcıya SIFIR çağrı — numara `activation-reaper`ın bir sonraki turuna
// kadar (≤60 sn) açıkta.
//
// Deterministik olarak üretilebiliyordu: `-count=10` → 10/10.
// test: rental_integration_test.go#TestRentalEndRaceWithProviderCloseHasSingleEffect
func (q *Queries) ClaimOrderClose(ctx context.Context, arg ClaimOrderCloseParams) (Order, error) {
	row := q.db.QueryRow(ctx, claimOrderClose, arg.Now, arg.ID, arg.ClaimStaleBefore)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProviderID,
		&i.RemoteOrderID,
		&i.ProviderActivationID,
		&i.PhoneNumber,
		&i.VerificationType,
		&i.ProductID,
		&i.ServiceCode,
		&i.ServiceName,
		&i.CountryIso2,
		&i.CountryName,
		&i.PhoneCode,
		&i.QuoteID,
		&i.PricePaidMinor,
		&i.CostMicro,
		&i.FxRate,
		&i.Status,
		&i.ExpiresAt,
		&i.CancellableAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.RefundedAt,
		&i.ProviderClosedAt,
		&i.CloseAttempts,
		&i.CloseLastError,
		&i.ProviderRefundStatus,
		&i.ProviderRefundAmountMinor,
		&i.RefundAttempts,
		&i.RefundNextAttemptAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloseClaimedAt,
		&i.ProductKind,
		&i.RefundableUntil,
		&i.LastPolledAt,
	)
	return i, err
}

const countAllOrders = `-- name: CountAllOrders :one
SELECT count(*)
FROM orders o JOIN users u ON u.id = o.user_id
WHERE ($1::order_status IS NULL OR o.status = $1)
  AND ($2::text IS NULL
       OR u.email ILIKE '%' || $2 || '%'
       OR u.username ILIKE '%' || $2 || '%'
       OR o.phone_number ILIKE '%' || $2 || '%')
`

type CountAllOrdersParams struct {
	Status *OrderStatus
	Q      *string
}

func (q *Queries) CountAllOrders(ctx context.Context, arg CountAllOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllOrders, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrderMessages = `-- name: CountOrderMessages :one
SELECT count(*) FROM order_messages WHERE order_id = $1
`

func (q *Queries) CountOrderMessages(ctx context.Context, orderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderMessages, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserOrders = `-- name: CountUserOrders :one
SELECT count(*) FROM orders o
WHERE o.user_id = $1
  AND ($2::order_status IS NULL OR o.status = $2::order_status)
  AND (NOT $3::boolean OR o.status IN ('PENDING', 'ACTIVE'))
  AND ($4::text IS NULL
       OR o.service_name::text ILIKE '%' || $4::text || '%'
       OR o.phone_number::text ILIKE '%' || $4::text || '%'
       OR o.country_name::text ILIKE '%' || $4::text || '%')
`

type CountUserOrdersParams struct {
	UserID     int64
	Status     *OrderStatus
	OnlyActive bool
	Q          *string
}

// 🔴 SÜZGEÇLER `ListUserOrders` İLE BİREBİR AYNI OLMAK ZORUNDA. Ayrışırsa
// sayfalama yalan söyler: "1–25 / 300" yazarken liste 4 satır gösterir ve
// "Sonraki" boş sayfa açar. İki sorgu tek bir kavramın iki yarısıdır.
// test: order_integration_test.go#TestListUserOrdersFiltreleri
func (q *Queries) CountUserOrders(ctx context.Context, arg CountUserOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserOrders,
		arg.UserID,
		arg.Status,
		arg.OnlyActive,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepositMethod = `-- name: CreateDepositMethod :one
INSERT INTO deposit_methods (code, kind, name, instructions, config,
                             min_amount_minor, max_amount_minor, sort_order)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
RETURNING id, public_id, code, kind, name, instructions, config, min_amount_minor, max_amount_minor, is_active, sort_order, created_at, updated_at
`

type CreateDepositMethodParams struct {
	Code           string
	Kind           DepositMethodKind
	Name           string
	Instructions   string
	Config         []byte
	MinAmountMinor int64
	MaxAmountMinor int64
	SortOrder      int32
}

func (q *Queries) CreateDepositMethod(ctx context.Context, arg CreateDepositMethodParams) (DepositMethod, error) {
	row := q.db.QueryRow(ctx, createDepositMethod,
		arg.Code,
		arg.Kind,
		arg.Name,
		arg.Instructions,
		arg.Config,
		arg.MinAmountMinor,
		arg.MaxAmountMinor,
		arg.SortOrder,
	)
	var i DepositMethod
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Code,
		&i.Kind,
		&i.Name,
		&i.Instructions,
		&i.Config,
		&i.MinAmountMinor,
		&i.MaxAmountMinor,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id, provider_id, remote_order_id, provider_activation_id,
    phone_number, verification_type,
    product_id, product_kind, service_code, service_name, country_iso2, country_name, phone_code,
    quote_id, price_paid_minor, cost_micro, fx_rate,
    expires_at, cancellable_at, refundable_until
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20
)
RETURNING id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at
`

type CreateOrderParams struct {
	UserID               int64
	ProviderID           int64
	RemoteOrderID        string
	ProviderActivationID *int64
	PhoneNumber          string
	VerificationType     VerificationType
	ProductID            *int64
	ProductKind          ProductKind
	ServiceCode          string
	ServiceName          string
	CountryIso2          string
	CountryName          string
	PhoneCode            string
	QuoteID              *int64
	PricePaidMinor       int64
	CostMicro            int64
	FxRate               pgtype.Numeric
	ExpiresAt            time.Time
	CancellableAt        time.Time
	RefundableUntil      *time.Time
}

// Sipariş kaydı — T2 içinde, sağlayıcı çağrısı BAŞARILI olduktan sonra.
//
// Katalog alanları ANLIK GÖRÜNTÜ olarak yazılır: servis/ülke satırları katalog
// senkronunda silinebilir, sipariş geçmişi buna dayanamaz.
// `product_kind` de bir ANLIK GÖRÜNTÜDÜR: "iade mi Finish mi" kararı katalog
// satırına JOIN ile verilemez, çünkü o satır silinebilir (product_id ON DELETE
// SET NULL). `refundable_until` NULL ise ek bir iptal tavanı yoktur (aktivasyon).
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.ProviderID,
		arg.RemoteOrderID,
		arg.ProviderActivationID,
		arg.PhoneNumber,
		arg.VerificationType,
		arg.ProductID,
		arg.ProductKind,
		arg.ServiceCode,
		arg.ServiceName,
		arg.CountryIso2,
		arg.CountryName,
		arg.PhoneCode,
		arg.QuoteID,
		arg.PricePaidMinor,
		arg.CostMicro,
		arg.FxRate,
		arg.ExpiresAt,
		arg.CancellableAt,
		arg.RefundableUntil,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProviderID,
		&i.RemoteOrderID,
		&i.ProviderActivationID,
		&i.PhoneNumber,
		&i.VerificationType,
		&i.ProductID,
		&i.ServiceCode,
		&i.ServiceName,
		&i.CountryIso2,
		&i.CountryName,
		&i.PhoneCode,
		&i.QuoteID,
		&i.PricePaidMinor,
		&i.CostMicro,
		&i.FxRate,
		&i.Status,
		&i.ExpiresAt,
		&i.CancellableAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.RefundedAt,
		&i.ProviderClosedAt,
		&i.CloseAttempts,
		&i.CloseLastError,
		&i.ProviderRefundStatus,
		&i.ProviderRefundAmountMinor,
		&i.RefundAttempts,
		&i.RefundNextAttemptAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloseClaimedAt,
		&i.ProductKind,
		&i.RefundableUntil,
		&i.LastPolledAt,
	)
	return i, err
}

const createRentalDetail = `-- name: CreateRentalDetail :one
INSERT INTO rental_details (order_id, duration_hours, rental_ends_at)
VALUES ($1, $2, $3)
ON CONFLICT (order_id) DO UPDATE
    SET duration_hours = EXCLUDED.duration_hours,
        rental_ends_at = EXCLUDED.rental_ends_at
RETURNING order_id, duration_hours, renewed_count, rental_ends_at, created_at
`

type CreateRentalDetailParams struct {
	OrderID       int64
	DurationHours int32
	RentalEndsAt  time.Time
}

// Kira dönemi kaydı — sipariş satırıyla AYNI transaction'da (T2) yazılır.
//
// Tablo 00008'de açıldı ama hiçbir kod ona yazmıyordu: `duration_hours`
// sağlayıcı çağrısından sonra çöpe gidiyordu ve `rental_ends_at` diye bir
// gerçek yoktu. Kira dönemi üzerine kurulacak her rapor "hiç kiralık yok"
// derdi — para akarken.
//
// YETKİLİ KAYNAK `orders.expires_at`TİR; bu satır dönemin KAYDIDIR. İkisini
// bağımsız iki doğruluk kaynağı yapmak, uzatmadan sonra birinin
// güncellenmemesiyle biter.
func (q *Queries) CreateRentalDetail(ctx context.Context, arg CreateRentalDetailParams) (RentalDetail, error) {
	row := q.db.QueryRow(ctx, createRentalDetail, arg.OrderID, arg.DurationHours, arg.RentalEndsAt)
	var i RentalDetail
	err := row.Scan(
		&i.OrderID,
		&i.DurationHours,
		&i.RenewedCount,
		&i.RentalEndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDepositMethod = `-- name: DeleteDepositMethod :exec
DELETE FROM deposit_methods WHERE public_id = $1
`

// Yöntem SİLİNİR ama geçmiş yükleme kayıtları KALIR: deposits.method_id
// ON DELETE SET NULL ve method_name anlık görüntü olarak saklanıyor.
func (q *Queries) DeleteDepositMethod(ctx context.Context, publicID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepositMethod, publicID)
	return err
}

const getDepositMethod = `-- name: GetDepositMethod :one
SELECT id, public_id, code, kind, name, instructions, config, min_amount_minor, max_amount_minor, is_active, sort_order, created_at, updated_at FROM deposit_methods WHERE public_id = $1
`

func (q *Queries) GetDepositMethod(ctx context.Context, publicID uuid.UUID) (DepositMethod, error) {
	row := q.db.QueryRow(ctx, getDepositMethod, publicID)
	var i DepositMethod
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Code,
		&i.Kind,
		&i.Name,
		&i.Instructions,
		&i.Config,
		&i.MinAmountMinor,
		&i.MaxAmountMinor,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByRemote = `-- name: GetOrderByRemote :one
SELECT id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at FROM orders
WHERE provider_id = $1 AND remote_order_id = $2
`

type GetOrderByRemoteParams struct {
	ProviderID    int64
	RemoteOrderID string
}

// Webhook korelasyonu: sağlayıcı YALNIZ aktivasyon kimliğini taşır.
func (q *Queries) GetOrderByRemote(ctx context.Context, arg GetOrderByRemoteParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByRemote, arg.ProviderID, arg.RemoteOrderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProviderID,
		&i.RemoteOrderID,
		&i.ProviderActivationID,
		&i.PhoneNumber,
		&i.VerificationType,
		&i.ProductID,
		&i.ServiceCode,
		&i.ServiceName,
		&i.CountryIso2,
		&i.CountryName,
		&i.PhoneCode,
		&i.QuoteID,
		&i.PricePaidMinor,
		&i.CostMicro,
		&i.FxRate,
		&i.Status,
		&i.ExpiresAt,
		&i.CancellableAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.RefundedAt,
		&i.ProviderClosedAt,
		&i.CloseAttempts,
		&i.CloseLastError,
		&i.ProviderRefundStatus,
		&i.ProviderRefundAmountMinor,
		&i.RefundAttempts,
		&i.RefundNextAttemptAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloseClaimedAt,
		&i.ProductKind,
		&i.RefundableUntil,
		&i.LastPolledAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at FROM orders WHERE id = $1 FOR UPDATE
`

// Durum değiştirmeden ÖNCE kilitle. Kilitsiz okuma + yazma, iki işçinin aynı
// siparişi aynı anda sonlandırmasına ve çift iadeye yol açar.
func (q *Queries) GetOrderForUpdate(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProviderID,
		&i.RemoteOrderID,
		&i.ProviderActivationID,
		&i.PhoneNumber,
		&i.VerificationType,
		&i.ProductID,
		&i.ServiceCode,
		&i.ServiceName,
		&i.CountryIso2,
		&i.CountryName,
		&i.PhoneCode,
		&i.QuoteID,
		&i.PricePaidMinor,
		&i.CostMicro,
		&i.FxRate,
		&i.Status,
		&i.ExpiresAt,
		&i.CancellableAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.RefundedAt,
		&i.ProviderClosedAt,
		&i.CloseAttempts,
		&i.CloseLastError,
		&i.ProviderRefundStatus,
		&i.ProviderRefundAmountMinor,
		&i.RefundAttempts,
		&i.RefundNextAttemptAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloseClaimedAt,
		&i.ProductKind,
		&i.RefundableUntil,
		&i.LastPolledAt,
	)
	return i, err
}

const getOrderForUser = `-- name: GetOrderForUser :one
SELECT id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at FROM orders WHERE public_id = $1 AND user_id = $2
`

type GetOrderForUserParams struct {
	PublicID uuid.UUID
	UserID   int64
}

// SAHİPLİK SORGUNUN PARÇASIDIR (CLAUDE.md değişmez #7).
// Ayrı bir `if order.UserID != userID` kontrolü yazılmaz: unutulabilir.
func (q *Queries) GetOrderForUser(ctx context.Context, arg GetOrderForUserParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUser, arg.PublicID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProviderID,
		&i.RemoteOrderID,
		&i.ProviderActivationID,
		&i.PhoneNumber,
		&i.VerificationType,
		&i.ProductID,
		&i.ServiceCode,
		&i.ServiceName,
		&i.CountryIso2,
		&i.CountryName,
		&i.PhoneCode,
		&i.QuoteID,
		&i.PricePaidMinor,
		&i.CostMicro,
		&i.FxRate,
		&i.Status,
		&i.ExpiresAt,
		&i.CancellableAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.RefundedAt,
		&i.ProviderClosedAt,
		&i.CloseAttempts,
		&i.CloseLastError,
		&i.ProviderRefundStatus,
		&i.ProviderRefundAmountMinor,
		&i.RefundAttempts,
		&i.RefundNextAttemptAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloseClaimedAt,
		&i.ProductKind,
		&i.RefundableUntil,
		&i.LastPolledAt,
	)
	return i, err
}

const getQuoteContext = `-- name: GetQuoteContext :one
SELECT
    s.code AS service_code, s.name AS service_name, s.name_tr AS service_name_tr,
    c.iso2 AS country_iso2, c.name AS country_name, c.name_tr AS country_name_tr,
    c.phone_code
FROM price_quotes q
JOIN products  p ON p.id = q.product_id
JOIN services  s ON s.id = p.service_id
JOIN countries c ON c.id = p.country_id
WHERE q.id = $1
`

type GetQuoteContextRow struct {
	ServiceCode   string
	ServiceName   string
	ServiceNameTr string
	CountryIso2   string
	CountryName   string
	CountryNameTr string
	PhoneCode     string
}

// Sipariş anlık görüntüsü için servis/ülke adları.
//
// Sipariş satırına KOPYALANIR: katalog satırları senkronda silinebilir ve
// sipariş geçmişi bir yıl sonra da okunabilir olmalıdır.
func (q *Queries) GetQuoteContext(ctx context.Context, quoteID int64) (GetQuoteContextRow, error) {
	row := q.db.QueryRow(ctx, getQuoteContext, quoteID)
	var i GetQuoteContextRow
	err := row.Scan(
		&i.ServiceCode,
		&i.ServiceName,
		&i.ServiceNameTr,
		&i.CountryIso2,
		&i.CountryName,
		&i.CountryNameTr,
		&i.PhoneCode,
	)
	return i, err
}

const getRentalDetail = `-- name: GetRentalDetail :one
SELECT order_id, duration_hours, renewed_count, rental_ends_at, created_at FROM rental_details WHERE order_id = $1
`

func (q *Queries) GetRentalDetail(ctx context.Context, orderID int64) (RentalDetail, error) {
	row := q.db.QueryRow(ctx, getRentalDetail, orderID)
	var i RentalDetail
	err := row.Scan(
		&i.OrderID,
		&i.DurationHours,
		&i.RenewedCount,
		&i.RentalEndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertOrderMessage = `-- name: InsertOrderMessage :one

INSERT INTO order_messages (order_id, provider_otp_id, code, body, sender, received_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (order_id, provider_otp_id) DO NOTHING
RETURNING id, order_id, provider_otp_id, code, body, sender, received_at, created_at
`

type InsertOrderMessageParams struct {
	OrderID       int64
	ProviderOtpID string
	Code          string
	Body          string
	Sender        string
	ReceivedAt    time.Time
}

// ─────────────────────────── Mesajlar ───────────────────────────
// DEDUP: aynı mesaj webhook, yoklama ve yeniden gönderimlerle en az sekiz kez
// gelebilir. UNIQUE kısıt son savunma hattıdır; ON CONFLICT ile sessizce
// yutulur ve `inserted` alanı gerçekten yeni mi söyler.
func (q *Queries) InsertOrderMessage(ctx context.Context, arg InsertOrderMessageParams) (OrderMessage, error) {
	row := q.db.QueryRow(ctx, insertOrderMessage,
		arg.OrderID,
		arg.ProviderOtpID,
		arg.Code,
		arg.Body,
		arg.Sender,
		arg.ReceivedAt,
	)
	var i OrderMessage
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProviderOtpID,
		&i.Code,
		&i.Body,
		&i.Sender,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveDepositMethods = `-- name: ListActiveDepositMethods :many
SELECT id, public_id, code, kind, name, instructions, config, min_amount_minor, max_amount_minor, is_active, sort_order, created_at, updated_at FROM deposit_methods WHERE is_active ORDER BY sort_order, name
`

// Kullanıcı: yalnız aktif yöntemler.
func (q *Queries) ListActiveDepositMethods(ctx context.Context) ([]DepositMethod, error) {
	rows, err := q.db.Query(ctx, listActiveDepositMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DepositMethod{}
	for rows.Next() {
		var i DepositMethod
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Code,
			&i.Kind,
			&i.Name,
			&i.Instructions,
			&i.Config,
			&i.MinAmountMinor,
			&i.MaxAmountMinor,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRentalsForPoll = `-- name: ListActiveRentalsForPoll :many
SELECT id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at FROM orders
WHERE product_kind = 'SMS_RENTAL'
  AND status IN ('PENDING', 'ACTIVE')
  AND expires_at > $1
ORDER BY last_polled_at ASC NULLS FIRST, id
LIMIT $2
`

type ListActiveRentalsForPollParams struct {
	Now time.Time
	Lim int32
}

// `rental-poller` için: dönemi süren kiralıklar.
//
// İKİ DURUM BİRDEN: 'PENDING' (henüz mesaj gelmedi) ve 'ACTIVE' (en az bir
// mesaj geldi, dönem sürüyor). Kiralıkta mesaj gelmesi yoklamayı bitirmez —
// ürünün tamamı "30 gün boyunca gelen HER mesajı gör"dür.
//
// 🔴 SIRALAMA `created_at` DEĞİL — ve bu bir hata düzeltmesidir.
//
// `created_at ASC` + `LIMIT` deseni aktivasyonda güvenlidir çünkü satırlar ~20
// dakikada kümeden çıkar; kiralıkta küme dönem boyunca (24–4320 saat) SABİT
// kalır. 101. kiralık, ilk 100'ün hiçbiri bitmeden hiçbir turda görünmezdi:
// webhook kaybolduğunda o kullanıcı 30 gün boyunca tek mesaj görmez.
//
// `last_polled_at` turu dönüşümlü yapar. `NULLS FIRST` yeni satırın ilk turda
// görülmesini garanti eder; `id` eşitlik hâlinde belirlenimli sıra verir
// (aynı damgayı taşıyan bir toplu güncellemeden sonra tur ilerlemeye devam
// etsin).
// test: ../internal/service/order/rental_integration_test.go#TestRentalPollNeverStarvesNewestRental
func (q *Queries) ListActiveRentalsForPoll(ctx context.Context, arg ListActiveRentalsForPollParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listActiveRentalsForPoll, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.ProviderID,
			&i.RemoteOrderID,
			&i.ProviderActivationID,
			&i.PhoneNumber,
			&i.VerificationType,
			&i.ProductID,
			&i.ServiceCode,
			&i.ServiceName,
			&i.CountryIso2,
			&i.CountryName,
			&i.PhoneCode,
			&i.QuoteID,
			&i.PricePaidMinor,
			&i.CostMicro,
			&i.FxRate,
			&i.Status,
			&i.ExpiresAt,
			&i.CancellableAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.RefundedAt,
			&i.ProviderClosedAt,
			&i.CloseAttempts,
			&i.CloseLastError,
			&i.ProviderRefundStatus,
			&i.ProviderRefundAmountMinor,
			&i.RefundAttempts,
			&i.RefundNextAttemptAt,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CloseClaimedAt,
			&i.ProductKind,
			&i.RefundableUntil,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOrders = `-- name: ListAllOrders :many

SELECT o.id, o.public_id, o.user_id, o.provider_id, o.remote_order_id, o.provider_activation_id, o.phone_number, o.verification_type, o.product_id, o.service_code, o.service_name, o.country_iso2, o.country_name, o.phone_code, o.quote_id, o.price_paid_minor, o.cost_micro, o.fx_rate, o.status, o.expires_at, o.cancellable_at, o.completed_at, o.cancelled_at, o.refunded_at, o.provider_closed_at, o.close_attempts, o.close_last_error, o.provider_refund_status, o.provider_refund_amount_minor, o.refund_attempts, o.refund_next_attempt_at, o.cancel_reason, o.created_at, o.updated_at, o.close_claimed_at, o.product_kind, o.refundable_until, o.last_polled_at, u.username, u.email
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE ($1::order_status IS NULL OR o.status = $1)
  AND ($2::text IS NULL
       OR u.email ILIKE '%' || $2 || '%'
       OR u.username ILIKE '%' || $2 || '%'
       OR o.phone_number ILIKE '%' || $2 || '%')
ORDER BY o.created_at DESC
LIMIT $4 OFFSET $3
`

type ListAllOrdersParams struct {
	Status *OrderStatus
	Q      *string
	Off    int32
	Lim    int32
}

type ListAllOrdersRow struct {
	ID                        int64
	PublicID                  uuid.UUID
	UserID                    int64
	ProviderID                int64
	RemoteOrderID             string
	ProviderActivationID      *int64
	PhoneNumber               string
	VerificationType          VerificationType
	ProductID                 *int64
	ServiceCode               string
	ServiceName               string
	CountryIso2               string
	CountryName               string
	PhoneCode                 string
	QuoteID                   *int64
	PricePaidMinor            int64
	CostMicro                 int64
	FxRate                    pgtype.Numeric
	Status                    OrderStatus
	ExpiresAt                 time.Time
	CancellableAt             time.Time
	CompletedAt               *time.Time
	CancelledAt               *time.Time
	RefundedAt                *time.Time
	ProviderClosedAt          *time.Time
	CloseAttempts             int32
	CloseLastError            string
	ProviderRefundStatus      RefundStatus
	ProviderRefundAmountMinor int64
	RefundAttempts            int32
	RefundNextAttemptAt       *time.Time
	CancelReason              string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	CloseClaimedAt            *time.Time
	ProductKind               ProductKind
	RefundableUntil           *time.Time
	LastPolledAt              *time.Time
	Username                  string
	Email                     string
}

// ─────────────────────────── Yönetim ───────────────────────────
// Yönetim paneli — `orders:read_all` izni gerektirir.
func (q *Queries) ListAllOrders(ctx context.Context, arg ListAllOrdersParams) ([]ListAllOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAllOrders,
		arg.Status,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllOrdersRow{}
	for rows.Next() {
		var i ListAllOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.ProviderID,
			&i.RemoteOrderID,
			&i.ProviderActivationID,
			&i.PhoneNumber,
			&i.VerificationType,
			&i.ProductID,
			&i.ServiceCode,
			&i.ServiceName,
			&i.CountryIso2,
			&i.CountryName,
			&i.PhoneCode,
			&i.QuoteID,
			&i.PricePaidMinor,
			&i.CostMicro,
			&i.FxRate,
			&i.Status,
			&i.ExpiresAt,
			&i.CancellableAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.RefundedAt,
			&i.ProviderClosedAt,
			&i.CloseAttempts,
			&i.CloseLastError,
			&i.ProviderRefundStatus,
			&i.ProviderRefundAmountMinor,
			&i.RefundAttempts,
			&i.RefundNextAttemptAt,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CloseClaimedAt,
			&i.ProductKind,
			&i.RefundableUntil,
			&i.LastPolledAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositMethods = `-- name: ListDepositMethods :many

SELECT id, public_id, code, kind, name, instructions, config, min_amount_minor, max_amount_minor, is_active, sort_order, created_at, updated_at FROM deposit_methods ORDER BY sort_order, name
`

// ─────────────────────── Ödeme yöntemleri ───────────────────────
// Yönetim: tüm yöntemler (pasifler dahil).
func (q *Queries) ListDepositMethods(ctx context.Context) ([]DepositMethod, error) {
	rows, err := q.db.Query(ctx, listDepositMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DepositMethod{}
	for rows.Next() {
		var i DepositMethod
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Code,
			&i.Kind,
			&i.Name,
			&i.Instructions,
			&i.Config,
			&i.MinAmountMinor,
			&i.MaxAmountMinor,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndedRentals = `-- name: ListEndedRentals :many
SELECT id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at FROM orders
WHERE product_kind = 'SMS_RENTAL'
  AND status IN ('PENDING', 'ACTIVE')
  AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListEndedRentalsParams struct {
	Now time.Time
	Lim int32
}

// `rental-closer` için: kira dönemi bitmiş ama hâlâ kapatılmamış kiralıklar.
//
// 'PENDING' de dahildir: hiç mesaj almamış bir kiralık 'ACTIVE'e hiç geçmez ve
// dönem sonunda yine kapatılmalıdır (FR-412: her sipariş sağlayıcıda kapanır).
func (q *Queries) ListEndedRentals(ctx context.Context, arg ListEndedRentalsParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listEndedRentals, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.ProviderID,
			&i.RemoteOrderID,
			&i.ProviderActivationID,
			&i.PhoneNumber,
			&i.VerificationType,
			&i.ProductID,
			&i.ServiceCode,
			&i.ServiceName,
			&i.CountryIso2,
			&i.CountryName,
			&i.PhoneCode,
			&i.QuoteID,
			&i.PricePaidMinor,
			&i.CostMicro,
			&i.FxRate,
			&i.Status,
			&i.ExpiresAt,
			&i.CancellableAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.RefundedAt,
			&i.ProviderClosedAt,
			&i.CloseAttempts,
			&i.CloseLastError,
			&i.ProviderRefundStatus,
			&i.ProviderRefundAmountMinor,
			&i.RefundAttempts,
			&i.RefundNextAttemptAt,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CloseClaimedAt,
			&i.ProductKind,
			&i.RefundableUntil,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingOrders = `-- name: ListExpiredPendingOrders :many
SELECT id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at FROM orders
WHERE status = 'PENDING' AND product_kind = 'SMS_ACTIVATION' AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredPendingOrdersParams struct {
	Now time.Time
	Lim int32
}

// `order-expirer` için: süresi dolmuş ama hâlâ beklemede olan AKTİVASYONLAR.
//
// 🔴 KİRALIKLAR DIŞARIDA — bu sorgunun sonucu TAM İADE demektir.
//
// Kiralıkta satılan şey süredir: numara 30 gün ayrıldı, sağlayıcıya ödendi,
// kullanıcı istediği an kullanabildi. Kod gelmemesi iade sebebi değildir ve
// sağlayıcının ücretsiz iptal penceresi (≈20 dk) 1. günde kapandığı için o
// parayı geri almanın yolu da yoktur: buradan yazılacak iadenin %100'ü bizim
// cebimizden çıkar ve "kiralık al, 30. günde paranı al" tekrarlanabilir bir
// sızıntı olur. Dönem sonu `ListEndedRentals` → EndRental ile işlenir; orada
// deftere kayıt yazılmaz.
// test: ../internal/service/order/rental_integration_test.go#TestRentalNeverAutoRefundsAtEndOfPeriod
func (q *Queries) ListExpiredPendingOrders(ctx context.Context, arg ListExpiredPendingOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingOrders, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.ProviderID,
			&i.RemoteOrderID,
			&i.ProviderActivationID,
			&i.PhoneNumber,
			&i.VerificationType,
			&i.ProductID,
			&i.ServiceCode,
			&i.ServiceName,
			&i.CountryIso2,
			&i.CountryName,
			&i.PhoneCode,
			&i.QuoteID,
			&i.PricePaidMinor,
			&i.CostMicro,
			&i.FxRate,
			&i.Status,
			&i.ExpiresAt,
			&i.CancellableAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.RefundedAt,
			&i.ProviderClosedAt,
			&i.CloseAttempts,
			&i.CloseLastError,
			&i.ProviderRefundStatus,
			&i.ProviderRefundAmountMinor,
			&i.RefundAttempts,
			&i.RefundNextAttemptAt,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CloseClaimedAt,
			&i.ProductKind,
			&i.RefundableUntil,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderMessages = `-- name: ListOrderMessages :many
SELECT id, order_id, provider_otp_id, code, body, sender, received_at, created_at FROM order_messages WHERE order_id = $1 ORDER BY received_at, id
`

func (q *Queries) ListOrderMessages(ctx context.Context, orderID int64) ([]OrderMessage, error) {
	rows, err := q.db.Query(ctx, listOrderMessages, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderMessage{}
	for rows.Next() {
		var i OrderMessage
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProviderOtpID,
			&i.Code,
			&i.Body,
			&i.Sender,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanHolds = `-- name: ListOrphanHolds :many
SELECT q.id, q.public_id, q.user_id, q.product_id, q.provider_id, q.cost_micro, q.cost_currency, q.fx_rate, q.margin_percent, q.pricing_rule_id, q.sell_price_minor, q.stock_at_quote, q.expires_at, q.consumed_at, q.created_at FROM price_quotes q
LEFT JOIN orders o ON o.quote_id = q.id
WHERE q.consumed_at IS NOT NULL
  AND q.consumed_at < $1
  AND o.id IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM ledger_entries le
      WHERE le.idempotency_key = 'order:' || q.public_id::text || ':refund'
  )
ORDER BY q.consumed_at
LIMIT $2
`

type ListOrphanHoldsParams struct {
	OlderThan *time.Time
	Lim       int32
}

// `orphan-hold-reaper` için: PARASI ÇEKİLMİŞ ama siparişi olmayan teklifler.
//
// T1 (teklif tüket + bakiye düş) ile T2 (sipariş yaz) arasında süreç ölürse
// kullanıcının parası gitmiş ama elinde numara yoktur. Bu sorgu o durumu bulur.
//
// `consumed_at` eşiği, henüz T2'ye ulaşmamış NORMAL akışları yakalamamak için:
// satın alma birkaç saniye sürer, hemen "yetim" ilan etmek çalışan bir siparişi
// iade eder.
//
// 🔴 İADE EDİLMİŞ OLANLAR DIŞLANIR — yoksa bu sorgu KALICI OLARAK TIKANIR.
//
// Sağlayıcı hatasıyla düşen HER satın alma (stok yok, 5xx, geçmiş expiredAt)
// tam olarak bu profilde bir satır bırakır: teklif tüketilmiş, iade `refundHold`
// tarafından ZATEN yazılmış, sipariş satırı hiç oluşmamış. Bu satırları dışlayan
// bir kolon yoktu; her başarısız satın alma sorguya kalıcı bir satır ekliyordu.
// 100 böyle satır biriktiğinde (tek sağlayıcı kesintisinde dakikalar sürer)
// `LIMIT` tümüyle ölü satırlarla dolar ve GERÇEKTEN iade edilmemiş yeni yetimler
// hiç görülmez. Yani güvenlik ağı sessizce yırtılır.
//
// Ayrı bir kolon yerine DEFTERE bakılır: iade anahtarı zaten deterministik
// (`order:{quote_public_id}:refund`, service/order/service.go:368) ve defter
// değişmezdir — ikinci bir doğruluk kaynağı yaratmaktansa var olanı sorgularız.
// test: order_integration_test.go#TestOrphanHoldQuerySkipsAlreadyRefunded
func (q *Queries) ListOrphanHolds(ctx context.Context, arg ListOrphanHoldsParams) ([]PriceQuote, error) {
	rows, err := q.db.Query(ctx, listOrphanHolds, arg.OlderThan, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceQuote{}
	for rows.Next() {
		var i PriceQuote
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.ProductID,
			&i.ProviderID,
			&i.CostMicro,
			&i.CostCurrency,
			&i.FxRate,
			&i.MarginPercent,
			&i.PricingRuleID,
			&i.SellPriceMinor,
			&i.StockAtQuote,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOrdersForPoll = `-- name: ListPendingOrdersForPoll :many

SELECT id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at FROM orders
WHERE status = 'PENDING' AND product_kind = 'SMS_ACTIVATION' AND expires_at > $1
ORDER BY created_at
LIMIT $2
`

type ListPendingOrdersForPollParams struct {
	Now time.Time
	Lim int32
}

// ─────────────────────────── İşçi sorguları ───────────────────────────
// `order-poller` için: kod bekleyen, süresi dolmamış AKTİVASYON siparişleri.
//
// 🔴 KİRALIKLAR DIŞARIDA — sıklık farkı yüzünden, tercih olduğu için değil.
// Aktivasyon ~20 dakika yaşar; kiralık 24–4320 SAAT. Sıralama `created_at`
// olduğu için 100 canlı kiralık bu LIMIT'in başını günlerce işgal eder ve
// aktivasyon siparişleri hiç yoklanmaz: webhook kaybolduğunda kod hiç gelmez,
// order-expirer tam iade yazar — hem sağlayıcı maliyeti hem satış kaybı.
// Kiralıkların kendi turu vardır (ListActiveRentalsForPoll, 5 dakika).
// test: ../internal/service/order/rental_integration_test.go#TestRentalsDoNotStarveActivationPoll
func (q *Queries) ListPendingOrdersForPoll(ctx context.Context, arg ListPendingOrdersForPollParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listPendingOrdersForPoll, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.ProviderID,
			&i.RemoteOrderID,
			&i.ProviderActivationID,
			&i.PhoneNumber,
			&i.VerificationType,
			&i.ProductID,
			&i.ServiceCode,
			&i.ServiceName,
			&i.CountryIso2,
			&i.CountryName,
			&i.PhoneCode,
			&i.QuoteID,
			&i.PricePaidMinor,
			&i.CostMicro,
			&i.FxRate,
			&i.Status,
			&i.ExpiresAt,
			&i.CancellableAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.RefundedAt,
			&i.ProviderClosedAt,
			&i.CloseAttempts,
			&i.CloseLastError,
			&i.ProviderRefundStatus,
			&i.ProviderRefundAmountMinor,
			&i.RefundAttempts,
			&i.RefundNextAttemptAt,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CloseClaimedAt,
			&i.ProductKind,
			&i.RefundableUntil,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundRetryOrders = `-- name: ListRefundRetryOrders :many
SELECT id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at FROM orders
WHERE provider_refund_status IN ('PENDING', 'RETRY_SCHEDULED')
  AND (refund_next_attempt_at IS NULL OR refund_next_attempt_at <= $1)
ORDER BY coalesce(refund_next_attempt_at, created_at)
LIMIT $2
`

type ListRefundRetryOrdersParams struct {
	Now *time.Time
	Lim int32
}

// `provider-refund-retry` için: sağlayıcıdan iade beklenen siparişler.
func (q *Queries) ListRefundRetryOrders(ctx context.Context, arg ListRefundRetryOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listRefundRetryOrders, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.ProviderID,
			&i.RemoteOrderID,
			&i.ProviderActivationID,
			&i.PhoneNumber,
			&i.VerificationType,
			&i.ProductID,
			&i.ServiceCode,
			&i.ServiceName,
			&i.CountryIso2,
			&i.CountryName,
			&i.PhoneCode,
			&i.QuoteID,
			&i.PricePaidMinor,
			&i.CostMicro,
			&i.FxRate,
			&i.Status,
			&i.ExpiresAt,
			&i.CancellableAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.RefundedAt,
			&i.ProviderClosedAt,
			&i.CloseAttempts,
			&i.CloseLastError,
			&i.ProviderRefundStatus,
			&i.ProviderRefundAmountMinor,
			&i.RefundAttempts,
			&i.RefundNextAttemptAt,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CloseClaimedAt,
			&i.ProductKind,
			&i.RefundableUntil,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclosedTerminalOrders = `-- name: ListUnclosedTerminalOrders :many
SELECT id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at FROM orders
WHERE provider_closed_at IS NULL
  AND status IN ('COMPLETED', 'CANCELLED', 'FAILED', 'REFUNDED')
  AND provider_refund_status NOT IN ('PENDING', 'RETRY_SCHEDULED')
ORDER BY updated_at
LIMIT $1
`

// `activation-reaper` için: terminal ama sağlayıcıda kapatılmamış siparişler.
// KK-412: bu sorgunun sonucu uzun vadede BOŞ olmalıdır.
//
// ROL AYRIMI: iade ekseni AÇIK olan satırlar ('PENDING','RETRY_SCHEDULED')
// `provider-refund-retry` işinin sorumluluğundadır ve buraya DÜŞMEZ. Bu filtre
// olmadan iki iş aynı satıra Cancel() gönderir ve sağlayıcının verdiği
// Retry-After süresi (FR-414) 60 saniyede bir çiğnenir.
//
// Kapatma ekseni (FR-412) YİNE reaper'ındır: iade ekseni DENIED/REFUNDED/
// NOT_APPLICABLE'a düştüğü an satır buraya geri döner — kapatma denemesinden
// vazgeçilmez.
// test: refund_retry_integration_test.go#TestReaperIgnoresScheduledRefundOrders
func (q *Queries) ListUnclosedTerminalOrders(ctx context.Context, lim int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, listUnclosedTerminalOrders, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.ProviderID,
			&i.RemoteOrderID,
			&i.ProviderActivationID,
			&i.PhoneNumber,
			&i.VerificationType,
			&i.ProductID,
			&i.ServiceCode,
			&i.ServiceName,
			&i.CountryIso2,
			&i.CountryName,
			&i.PhoneCode,
			&i.QuoteID,
			&i.PricePaidMinor,
			&i.CostMicro,
			&i.FxRate,
			&i.Status,
			&i.ExpiresAt,
			&i.CancellableAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.RefundedAt,
			&i.ProviderClosedAt,
			&i.CloseAttempts,
			&i.CloseLastError,
			&i.ProviderRefundStatus,
			&i.ProviderRefundAmountMinor,
			&i.RefundAttempts,
			&i.RefundNextAttemptAt,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CloseClaimedAt,
			&i.ProductKind,
			&i.RefundableUntil,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrders = `-- name: ListUserOrders :many
SELECT o.id, o.public_id, o.user_id, o.provider_id, o.remote_order_id, o.provider_activation_id, o.phone_number, o.verification_type, o.product_id, o.service_code, o.service_name, o.country_iso2, o.country_name, o.phone_code, o.quote_id, o.price_paid_minor, o.cost_micro, o.fx_rate, o.status, o.expires_at, o.cancellable_at, o.completed_at, o.cancelled_at, o.refunded_at, o.provider_closed_at, o.close_attempts, o.close_last_error, o.provider_refund_status, o.provider_refund_amount_minor, o.refund_attempts, o.refund_next_attempt_at, o.cancel_reason, o.created_at, o.updated_at, o.close_claimed_at, o.product_kind, o.refundable_until, o.last_polled_at, coalesce(s.icon_url, '')::text AS icon_url
FROM orders o
LEFT JOIN services s ON s.code = o.service_code
WHERE o.user_id = $1
  AND ($2::order_status IS NULL OR o.status = $2::order_status)
  AND (NOT $3::boolean OR o.status IN ('PENDING', 'ACTIVE'))
  AND ($4::text IS NULL
       OR o.service_name::text ILIKE '%' || $4::text || '%'
       OR o.phone_number::text ILIKE '%' || $4::text || '%'
       OR o.country_name::text ILIKE '%' || $4::text || '%')
ORDER BY o.created_at DESC
LIMIT $6 OFFSET $5
`

type ListUserOrdersParams struct {
	UserID     int64
	Status     *OrderStatus
	OnlyActive bool
	Q          *string
	Off        int32
	Lim        int32
}

type ListUserOrdersRow struct {
	Order   Order
	IconUrl string
}

// 🔴 `icon_url` CANLI KATALOGDAN gelir, sipariş kaydından DEĞİL.
//
// `orders.service_name` bilerek anlık görüntüdür: satış kaydı, katalog sonradan
// değişse bile ne satıldığını korumalıdır (para kaydı, 10 yıl saklanıyor).
// Logo ise sunum verisidir; markanın logosu güncellendiğinde eski siparişlerde
// de yeni logonun görünmesi İSTENİR. Bu yüzden sipariş satırına kopyalanmaz,
// her okumada katalogdan çekilir.
//
// LEFT JOIN gerekçesi: `service_code` satın alma anındaki metin anlık
// görüntüsüdür; katalog senkronu sağlayıcının kodunu değiştirirse eşleşme
// kaybolur. INNER JOIN, o kullanıcının geçmiş siparişini listeden sessizce
// düşürürdü. (Servis satırının SİLİNMESİ mümkün değil — orders → price_quotes
// → products → services yabancı anahtar zinciri buna izin vermiyor.)
// test: order_integration_test.go#TestListUserOrdersCarriesServiceIcon
//
// `sqlc.embed(o)` kullanılır, sütunlar tek tek sayılmaz: `SELECT o.*` ya da elle
// sütun listesi, sqlc'ye `db.Order` yerine YENİ bir satır tipi ürettirir ve aynı
// tipi bekleyen tüm çağrı yerleri kırılır. `embed` `db.Order`'ı olduğu gibi
// korur, `icon_url`'i yanına ekler — ve şemaya sütun eklendiğinde bu sorgu
// kendiliğinden güncel kalır.
//
// SÜZGEÇLER — `sqlc.narg()` + "NULL ise süzme" deseni (CLAUDE.md sqlc kuralları).
//
// ÜÇ SÜZGEÇ VARDIR VE `only_active` AYRI DURMAK ZORUNDADIR:
//
//	status       → TEK durum eşleşmesi ("İptal edilenleri göster")
//	only_active  → "AKTİF" = PENDING **veya** ACTIVE, yani tek durum DEĞİL
//	q            → serbest metin
//
// `ListTicketsForAdmin`'deki `only_pending` ile aynı gerekçe: bir kullanıcı
// kavramı ("aktif siparişim") birden çok duruma karşılık geliyorsa, onu tek
// durumlu süzgece sıkıştırmak listeyi sessizce eksiltir. ACTIVE, kiralık
// siparişin süren dönemidir ve özet ekranında gizlenemez.
// Go'da string birleştirerek SQL kurulmaz; `ListUsers` ile AYNI desen.
//
// 🔴 `user_id` KOŞULU HER İKİ SÜZGEÇTEN ÖNCE GELİR ve kaldırılamaz: sahiplik
// sorgunun parçasıdır (değişmez #7). Hiçbir `q`/`status` bileşimi başka bir
// kullanıcının siparişini döndüremez.
//
// İNDEKS EKLENMEDİ: `ILIKE '%...%'` bir btree indeksi kullanamaz zaten, ama
// tarama `user_id` ile ZATEN daraltılmış küçük bir kümede olur (bir kullanıcının
// kendi siparişleri) — planlayıcı `orders_user_idx` (user_id, created_at DESC) ile satırları
// getirir, süzgeç o küme üzerinde çalışır. Gerçek bir sorun ölçülürse çare
// `pg_trgm` GIN indeksidir, gövdede string birleştirmek değil.
func (q *Queries) ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]ListUserOrdersRow, error) {
	rows, err := q.db.Query(ctx, listUserOrders,
		arg.UserID,
		arg.Status,
		arg.OnlyActive,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrdersRow{}
	for rows.Next() {
		var i ListUserOrdersRow
		if err := rows.Scan(
			&i.Order.ID,
			&i.Order.PublicID,
			&i.Order.UserID,
			&i.Order.ProviderID,
			&i.Order.RemoteOrderID,
			&i.Order.ProviderActivationID,
			&i.Order.PhoneNumber,
			&i.Order.VerificationType,
			&i.Order.ProductID,
			&i.Order.ServiceCode,
			&i.Order.ServiceName,
			&i.Order.CountryIso2,
			&i.Order.CountryName,
			&i.Order.PhoneCode,
			&i.Order.QuoteID,
			&i.Order.PricePaidMinor,
			&i.Order.CostMicro,
			&i.Order.FxRate,
			&i.Order.Status,
			&i.Order.ExpiresAt,
			&i.Order.CancellableAt,
			&i.Order.CompletedAt,
			&i.Order.CancelledAt,
			&i.Order.RefundedAt,
			&i.Order.ProviderClosedAt,
			&i.Order.CloseAttempts,
			&i.Order.CloseLastError,
			&i.Order.ProviderRefundStatus,
			&i.Order.ProviderRefundAmountMinor,
			&i.Order.RefundAttempts,
			&i.Order.RefundNextAttemptAt,
			&i.Order.CancelReason,
			&i.Order.CreatedAt,
			&i.Order.UpdatedAt,
			&i.Order.CloseClaimedAt,
			&i.Order.ProductKind,
			&i.Order.RefundableUntil,
			&i.Order.LastPolledAt,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrdersPolled = `-- name: MarkOrdersPolled :exec
UPDATE orders SET last_polled_at = $1 WHERE id = ANY($2::bigint[])
`

type MarkOrdersPolledParams struct {
	Now *time.Time
	Ids []int64
}

// Yoklama turunun damgası. Sıradaki tur en uzun süredir yoklanmamış satırla
// başlasın diye, sağlayıcı çağrısından ÖNCE yazılır: sağlayıcı erişilemezse
// bile tur ilerler ve tek bir arızalı grup kümenin geri kalanını aç bırakmaz.
func (q *Queries) MarkOrdersPolled(ctx context.Context, arg MarkOrdersPolledParams) error {
	_, err := q.db.Exec(ctx, markOrdersPolled, arg.Now, arg.Ids)
	return err
}

const markProviderClosed = `-- name: MarkProviderClosed :exec
UPDATE orders SET provider_closed_at = $1, close_last_error = '' WHERE id = $2
`

type MarkProviderClosedParams struct {
	Now *time.Time
	ID  int64
}

// Kapatma BAŞARILI OLDUKTAN SONRA çağrılır.
// Başarısızken yazılırsa reaper o siparişi bir daha hiç denemez ve aktivasyon
// sağlayıcıda açık kalır (FR-412).
func (q *Queries) MarkProviderClosed(ctx context.Context, arg MarkProviderClosedParams) error {
	_, err := q.db.Exec(ctx, markProviderClosed, arg.Now, arg.ID)
	return err
}

const orderStatsSummary = `-- name: OrderStatsSummary :one
SELECT
    count(*)                                                   AS total,
    count(*) FILTER (WHERE status = 'PENDING')                 AS pending,
    -- Dönemi süren kiralık: ödendi, teslim edildi, henüz bitmedi.
    count(*) FILTER (WHERE status = 'ACTIVE')                  AS active,
    count(*) FILTER (WHERE status = 'COMPLETED')               AS completed,
    count(*) FILTER (WHERE status IN ('CANCELLED','REFUNDED')) AS cancelled,
    count(*) FILTER (WHERE status = 'FAILED')                  AS failed,
    -- KK-412 ölçüsü: TERMİNAL olduğu hâlde sağlayıcıda kapatılmamış siparişler.
    -- 'ACTIVE' de 'PENDING' gibi hariçtir — dönemi süren bir kiralık numara
    -- sağlayıcıda AÇIK OLMALIDIR; onu "kapatılmamış" saymak, sıfıra gitmesi
    -- beklenen bir göstergeyi normal işleyişle doldururdu.
    count(*) FILTER (WHERE provider_closed_at IS NULL
                       AND status NOT IN ('PENDING', 'ACTIVE'))AS unclosed,
    -- 🔴 'ACTIVE' DE GELİRDİR.
    --
    -- Yalnız 'COMPLETED' toplamak kiralıkta geliri dönem boyunca (24–4320
    -- saat) SIFIR gösterir: para akarken panel boş kalır — eski prototipin
    -- tam olarak bu hatası vardı. 'ACTIVE' bir kiralık ödenmiştir ve geri
    -- alınamaz: durum makinesinde ACTIVE→CANCELLED oku YOKTUR, yani o tutar
    -- iade edilemez. 'PENDING' bilerek dışarıda — o para hâlâ iade edilebilir
    -- ve gerçekleşmiş sayılamaz.
    coalesce(sum(price_paid_minor)
             FILTER (WHERE status IN ('COMPLETED', 'ACTIVE')), 0)::bigint AS revenue_minor
FROM orders
WHERE created_at >= $1
`

type OrderStatsSummaryRow struct {
	Total        int64
	Pending      int64
	Active       int64
	Completed    int64
	Cancelled    int64
	Failed       int64
	Unclosed     int64
	RevenueMinor int64
}

// Yönetim özeti. Tek sorguda: N ayrı COUNT sorgusu atmak, tablo büyüdükçe
// panelin açılışını yavaşlatır.
//
// KOVALAR TOPLAMI `total`A EŞİTTİR. Eskiden değildi: 'ACTIVE' ve 'FAILED'
// hiçbir kovaya girmiyordu, yani panel "toplam 100, dağılım 78" gösterirdi.
// Bir sayının nereye gittiği görünmüyorsa gösterge okunamaz.
func (q *Queries) OrderStatsSummary(ctx context.Context, since time.Time) (OrderStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, orderStatsSummary, since)
	var i OrderStatsSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Active,
		&i.Completed,
		&i.Cancelled,
		&i.Failed,
		&i.Unclosed,
		&i.RevenueMinor,
	)
	return i, err
}

const recordCloseFailure = `-- name: RecordCloseFailure :exec
UPDATE orders SET close_attempts = close_attempts + 1, close_last_error = $1
WHERE id = $2
`

type RecordCloseFailureParams struct {
	CloseLastError string
	ID             int64
}

func (q *Queries) RecordCloseFailure(ctx context.Context, arg RecordCloseFailureParams) error {
	_, err := q.db.Exec(ctx, recordCloseFailure, arg.CloseLastError, arg.ID)
	return err
}

const releaseOrderClose = `-- name: ReleaseOrderClose :exec
UPDATE orders SET close_claimed_at = NULL WHERE id = $1
`

// Sahiplenmeyi BIRAKIR: kapatılacak bir şey olmadığı anlaşıldığında çağrılır
// (örn. sipariş hâlâ beklemede). Kirayı boşuna tutmak, siparişin terminal
// olduğu anda yapılacak kapatmayı kira süresi kadar geciktirirdi.
//
// BAŞARISIZLIKTA ÇAĞRILMAZ: kira, başarısız bir denemenin hemen ardından
// ikinci bir denemeyi engelleyerek sağlayıcının verdiği Retry-After süresine
// saygı gösterir.
func (q *Queries) ReleaseOrderClose(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, releaseOrderClose, id)
	return err
}

const setDepositMethodActive = `-- name: SetDepositMethodActive :one
UPDATE deposit_methods SET is_active = $1 WHERE public_id = $2
RETURNING id, public_id, code, kind, name, instructions, config, min_amount_minor, max_amount_minor, is_active, sort_order, created_at, updated_at
`

type SetDepositMethodActiveParams struct {
	IsActive bool
	PublicID uuid.UUID
}

// Aktif/pasif AYRI bir sorgu: tek bir düğmeye basmak, o sırada düzenlenmekte
// olan diğer alanları yazmamalı.
func (q *Queries) SetDepositMethodActive(ctx context.Context, arg SetDepositMethodActiveParams) (DepositMethod, error) {
	row := q.db.QueryRow(ctx, setDepositMethodActive, arg.IsActive, arg.PublicID)
	var i DepositMethod
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Code,
		&i.Kind,
		&i.Name,
		&i.Instructions,
		&i.Config,
		&i.MinAmountMinor,
		&i.MaxAmountMinor,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setOrderStatus = `-- name: SetOrderStatus :one
UPDATE orders SET
    status       = $1,
    completed_at = CASE WHEN $1::order_status = 'COMPLETED' THEN coalesce(completed_at, $2) ELSE completed_at END,
    cancelled_at = CASE WHEN $1::order_status IN ('CANCELLED','REFUNDED') THEN coalesce(cancelled_at, $2) ELSE cancelled_at END,
    refunded_at  = CASE WHEN $1::order_status = 'REFUNDED' THEN coalesce(refunded_at, $2) ELSE refunded_at END,
    cancel_reason = CASE WHEN $3::text <> '' THEN $3 ELSE cancel_reason END
WHERE id = $4
RETURNING id, public_id, user_id, provider_id, remote_order_id, provider_activation_id, phone_number, verification_type, product_id, service_code, service_name, country_iso2, country_name, phone_code, quote_id, price_paid_minor, cost_micro, fx_rate, status, expires_at, cancellable_at, completed_at, cancelled_at, refunded_at, provider_closed_at, close_attempts, close_last_error, provider_refund_status, provider_refund_amount_minor, refund_attempts, refund_next_attempt_at, cancel_reason, created_at, updated_at, close_claimed_at, product_kind, refundable_until, last_polled_at
`

type SetOrderStatusParams struct {
	Status OrderStatus
	Now    *time.Time
	Reason string
	ID     int64
}

// Durum yazımı — YALNIZ domain/order.Transition doğruladıktan sonra çağrılır.
// Veritabanındaki tetikleyici ikinci savunma hattıdır.
func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderStatus,
		arg.Status,
		arg.Now,
		arg.Reason,
		arg.ID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProviderID,
		&i.RemoteOrderID,
		&i.ProviderActivationID,
		&i.PhoneNumber,
		&i.VerificationType,
		&i.ProductID,
		&i.ServiceCode,
		&i.ServiceName,
		&i.CountryIso2,
		&i.CountryName,
		&i.PhoneCode,
		&i.QuoteID,
		&i.PricePaidMinor,
		&i.CostMicro,
		&i.FxRate,
		&i.Status,
		&i.ExpiresAt,
		&i.CancellableAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.RefundedAt,
		&i.ProviderClosedAt,
		&i.CloseAttempts,
		&i.CloseLastError,
		&i.ProviderRefundStatus,
		&i.ProviderRefundAmountMinor,
		&i.RefundAttempts,
		&i.RefundNextAttemptAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloseClaimedAt,
		&i.ProductKind,
		&i.RefundableUntil,
		&i.LastPolledAt,
	)
	return i, err
}

const setProviderRefundStatus = `-- name: SetProviderRefundStatus :exec
UPDATE orders SET
    provider_refund_status       = $1,
    provider_refund_amount_minor = $2,
    refund_attempts              = refund_attempts + 1,
    refund_next_attempt_at       = $3
WHERE id = $4
`

type SetProviderRefundStatusParams struct {
	ProviderRefundStatus      RefundStatus
	ProviderRefundAmountMinor int64
	RefundNextAttemptAt       *time.Time
	ID                        int64
}

func (q *Queries) SetProviderRefundStatus(ctx context.Context, arg SetProviderRefundStatusParams) error {
	_, err := q.db.Exec(ctx, setProviderRefundStatus,
		arg.ProviderRefundStatus,
		arg.ProviderRefundAmountMinor,
		arg.RefundNextAttemptAt,
		arg.ID,
	)
	return err
}

const settleProviderRefund = `-- name: SettleProviderRefund :exec
UPDATE orders SET
    provider_refund_status = $1,
    refund_next_attempt_at = NULL
WHERE id = $2
  AND provider_refund_status IN ('PENDING', 'RETRY_SCHEDULED')
`

type SettleProviderRefundParams struct {
	ProviderRefundStatus RefundStatus
	ID                   int64
}

// İade eksenini KAPATIR: sağlayıcıya bir daha istek gönderilmez.
//
// `SetProviderRefundStatus`ten iki farkı var ve ikisi de kasıtlı:
//  1. `refund_attempts` ARTIRILMAZ — kapatmak bir deneme değildir.
//  2. Koşulludur: yalnız iade ekseni AÇIKKEN yazar, böylece iki işçi aynı
//     anda kapatmaya çalışsa da sonuç tektir ve REFUNDED/DENIED bir satırın
//     üstüne yazılmaz.
//
// test: ../internal/service/order/refund_retry_integration_test.go#TestFinishedOrderLeavesRefundQueue
func (q *Queries) SettleProviderRefund(ctx context.Context, arg SettleProviderRefundParams) error {
	_, err := q.db.Exec(ctx, settleProviderRefund, arg.ProviderRefundStatus, arg.ID)
	return err
}

const updateDepositMethod = `-- name: UpdateDepositMethod :one
UPDATE deposit_methods SET
    name             = $1,
    instructions     = $2,
    config           = $3,
    min_amount_minor = $4,
    max_amount_minor = $5,
    sort_order       = $6
WHERE public_id = $7
RETURNING id, public_id, code, kind, name, instructions, config, min_amount_minor, max_amount_minor, is_active, sort_order, created_at, updated_at
`

type UpdateDepositMethodParams struct {
	Name           string
	Instructions   string
	Config         []byte
	MinAmountMinor int64
	MaxAmountMinor int64
	SortOrder      int32
	PublicID       uuid.UUID
}

func (q *Queries) UpdateDepositMethod(ctx context.Context, arg UpdateDepositMethodParams) (DepositMethod, error) {
	row := q.db.QueryRow(ctx, updateDepositMethod,
		arg.Name,
		arg.Instructions,
		arg.Config,
		arg.MinAmountMinor,
		arg.MaxAmountMinor,
		arg.SortOrder,
		arg.PublicID,
	)
	var i DepositMethod
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Code,
		&i.Kind,
		&i.Name,
		&i.Instructions,
		&i.Config,
		&i.MinAmountMinor,
		&i.MaxAmountMinor,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
