// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeQuote = `-- name: ConsumeQuote :one
UPDATE price_quotes SET consumed_at = $2
WHERE id = $1 AND consumed_at IS NULL
RETURNING id, public_id, user_id, product_id, provider_id, cost_micro, cost_currency, fx_rate, margin_percent, pricing_rule_id, sell_price_minor, stock_at_quote, expires_at, consumed_at, created_at
`

type ConsumeQuoteParams struct {
	ID         int64
	ConsumedAt *time.Time
}

// Tek kullanımlık işaretleme.
// WHERE consumed_at IS NULL sayesinde yarış durumunda ikinci çağrı
// SIFIR satır döner — kilitle birlikte çift savunma.
func (q *Queries) ConsumeQuote(ctx context.Context, arg ConsumeQuoteParams) (PriceQuote, error) {
	row := q.db.QueryRow(ctx, consumeQuote, arg.ID, arg.ConsumedAt)
	var i PriceQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProductID,
		&i.ProviderID,
		&i.CostMicro,
		&i.CostCurrency,
		&i.FxRate,
		&i.MarginPercent,
		&i.PricingRuleID,
		&i.SellPriceMinor,
		&i.StockAtQuote,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveRulesByScope = `-- name: CountActiveRulesByScope :one
SELECT count(*) FROM pricing_rules WHERE is_active AND scope = $1
`

// Bir kapsamdaki etkin kural sayısı.
//
// Son GLOBAL kuralın pasifleştirilmesini engellemek için kullanılır: GLOBAL
// kural kalmazsa ListApplicableRules boş döner, SelectRule ErrNoRule verir ve
// SİSTEM SATIŞ YAPAMAZ hâle gelir.
func (q *Queries) CountActiveRulesByScope(ctx context.Context, scope PricingScope) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRulesByScope, scope)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPricingRule = `-- name: CreatePricingRule :one
INSERT INTO pricing_rules
    (scope, service_id, country_id, product_id, margin_percent,
     fixed_fee_minor, min_price_minor, note, created_by_user_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, scope, service_id, country_id, product_id, margin_percent, fixed_fee_minor, min_price_minor, is_active, valid_from, valid_to, note, created_by_user_id, created_at, updated_at
`

type CreatePricingRuleParams struct {
	Scope           PricingScope
	ServiceID       *int64
	CountryID       *int64
	ProductID       *int64
	MarginPercent   pgtype.Numeric
	FixedFeeMinor   int64
	MinPriceMinor   int64
	Note            string
	CreatedByUserID *int64
}

func (q *Queries) CreatePricingRule(ctx context.Context, arg CreatePricingRuleParams) (PricingRule, error) {
	row := q.db.QueryRow(ctx, createPricingRule,
		arg.Scope,
		arg.ServiceID,
		arg.CountryID,
		arg.ProductID,
		arg.MarginPercent,
		arg.FixedFeeMinor,
		arg.MinPriceMinor,
		arg.Note,
		arg.CreatedByUserID,
	)
	var i PricingRule
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ServiceID,
		&i.CountryID,
		&i.ProductID,
		&i.MarginPercent,
		&i.FixedFeeMinor,
		&i.MinPriceMinor,
		&i.IsActive,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Note,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuote = `-- name: CreateQuote :one

INSERT INTO price_quotes
    (user_id, product_id, provider_id, cost_micro, cost_currency, fx_rate,
     margin_percent, pricing_rule_id, sell_price_minor, stock_at_quote, expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, public_id, user_id, product_id, provider_id, cost_micro, cost_currency, fx_rate, margin_percent, pricing_rule_id, sell_price_minor, stock_at_quote, expires_at, consumed_at, created_at
`

type CreateQuoteParams struct {
	UserID         int64
	ProductID      int64
	ProviderID     int64
	CostMicro      int64
	CostCurrency   CurrencyCode
	FxRate         pgtype.Numeric
	MarginPercent  pgtype.Numeric
	PricingRuleID  *int64
	SellPriceMinor int64
	StockAtQuote   int32
	ExpiresAt      time.Time
}

// ─────────────────────── Teklif ───────────────────────
func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (PriceQuote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.UserID,
		arg.ProductID,
		arg.ProviderID,
		arg.CostMicro,
		arg.CostCurrency,
		arg.FxRate,
		arg.MarginPercent,
		arg.PricingRuleID,
		arg.SellPriceMinor,
		arg.StockAtQuote,
		arg.ExpiresAt,
	)
	var i PriceQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProductID,
		&i.ProviderID,
		&i.CostMicro,
		&i.CostCurrency,
		&i.FxRate,
		&i.MarginPercent,
		&i.PricingRuleID,
		&i.SellPriceMinor,
		&i.StockAtQuote,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivatePricingRule = `-- name: DeactivatePricingRule :exec
UPDATE pricing_rules SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivatePricingRule(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivatePricingRule, id)
	return err
}

const deleteExpiredQuotes = `-- name: DeleteExpiredQuotes :execrows
DELETE FROM price_quotes
WHERE consumed_at IS NULL AND expires_at < $1
`

// Tüketilmemiş ve süresi geçmiş teklifler temizlenir.
// Tüketilmiş olanlar SAKLANIR: sipariş kaydının fiyat kanıtıdır.
func (q *Queries) DeleteExpiredQuotes(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredQuotes, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestFXRate = `-- name: GetLatestFXRate :one
SELECT id, base, quote, rate, source, fetched_at FROM fx_rates
WHERE base = $1 AND quote = $2
ORDER BY fetched_at DESC, id DESC
LIMIT 1
`

type GetLatestFXRateParams struct {
	Base  CurrencyCode
	Quote CurrencyCode
}

func (q *Queries) GetLatestFXRate(ctx context.Context, arg GetLatestFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, getLatestFXRate, arg.Base, arg.Quote)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.Base,
		&i.Quote,
		&i.Rate,
		&i.Source,
		&i.FetchedAt,
	)
	return i, err
}

const getPricingRule = `-- name: GetPricingRule :one
SELECT id, scope, service_id, country_id, product_id, margin_percent, fixed_fee_minor, min_price_minor, is_active, valid_from, valid_to, note, created_by_user_id, created_at, updated_at FROM pricing_rules WHERE id = $1
`

func (q *Queries) GetPricingRule(ctx context.Context, id int64) (PricingRule, error) {
	row := q.db.QueryRow(ctx, getPricingRule, id)
	var i PricingRule
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ServiceID,
		&i.CountryID,
		&i.ProductID,
		&i.MarginPercent,
		&i.FixedFeeMinor,
		&i.MinPriceMinor,
		&i.IsActive,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Note,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPricingRuleLabels = `-- name: GetPricingRuleLabels :one
SELECT
    r.scope,
    s.code AS service_code,
    c.iso2 AS country_iso2,
    p.duration_minutes AS product_duration_minutes
FROM pricing_rules r
LEFT JOIN services  s ON s.id = r.service_id
LEFT JOIN countries c ON c.id = r.country_id
LEFT JOIN products  p ON p.id = r.product_id
WHERE r.id = $1
`

type GetPricingRuleLabelsRow struct {
	Scope                  PricingScope
	ServiceCode            *string
	CountryIso2            *string
	ProductDurationMinutes *int32
}

// Bir kuralın kapsamını İNSAN OKUR kodlarla verir.
//
// Denetim kaydının entity_id'si için gerekir: oraya sayısal kimlik yazmak
// (Değişmez #10) kaydı hem okunmaz hem de kimlik yeniden kullanıldığında
// yanıltıcı yapar. "SERVICE_COUNTRY:whatsapp:TR" bir yıl sonra da aynı şeyi
// anlatır.
func (q *Queries) GetPricingRuleLabels(ctx context.Context, id int64) (GetPricingRuleLabelsRow, error) {
	row := q.db.QueryRow(ctx, getPricingRuleLabels, id)
	var i GetPricingRuleLabelsRow
	err := row.Scan(
		&i.Scope,
		&i.ServiceCode,
		&i.CountryIso2,
		&i.ProductDurationMinutes,
	)
	return i, err
}

const getQuoteByPublicID = `-- name: GetQuoteByPublicID :one
SELECT id, public_id, user_id, product_id, provider_id, cost_micro, cost_currency, fx_rate, margin_percent, pricing_rule_id, sell_price_minor, stock_at_quote, expires_at, consumed_at, created_at FROM price_quotes WHERE public_id = $1
`

func (q *Queries) GetQuoteByPublicID(ctx context.Context, publicID uuid.UUID) (PriceQuote, error) {
	row := q.db.QueryRow(ctx, getQuoteByPublicID, publicID)
	var i PriceQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProductID,
		&i.ProviderID,
		&i.CostMicro,
		&i.CostCurrency,
		&i.FxRate,
		&i.MarginPercent,
		&i.PricingRuleID,
		&i.SellPriceMinor,
		&i.StockAtQuote,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertFXRate = `-- name: InsertFXRate :one

INSERT INTO fx_rates (base, quote, rate, source, fetched_at)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, base, quote, rate, source, fetched_at
`

type InsertFXRateParams struct {
	Base      CurrencyCode
	Quote     CurrencyCode
	Rate      pgtype.Numeric
	Source    string
	FetchedAt time.Time
}

// ─────────────────────── Kur ───────────────────────
func (q *Queries) InsertFXRate(ctx context.Context, arg InsertFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, insertFXRate,
		arg.Base,
		arg.Quote,
		arg.Rate,
		arg.Source,
		arg.FetchedAt,
	)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.Base,
		&i.Quote,
		&i.Rate,
		&i.Source,
		&i.FetchedAt,
	)
	return i, err
}

const listApplicableRules = `-- name: ListApplicableRules :many

SELECT id, scope, service_id, country_id, product_id, margin_percent, fixed_fee_minor, min_price_minor, is_active, valid_from, valid_to, note, created_by_user_id, created_at, updated_at FROM pricing_rules
WHERE is_active
  AND (valid_from IS NULL OR valid_from <= now())
  AND (valid_to   IS NULL OR valid_to   >  now())
  AND (
        scope = 'GLOBAL'
     OR (scope = 'COUNTRY'         AND country_id = $1)
     OR (scope = 'SERVICE'         AND service_id = $2)
     OR (scope = 'SERVICE_COUNTRY' AND service_id = $2
                                   AND country_id = $1)
     OR (scope = 'PRODUCT'         AND product_id = $3)
  )
`

type ListApplicableRulesParams struct {
	CountryID *int64
	ServiceID *int64
	ProductID *int64
}

// ─────────────────────── Fiyat kuralları ───────────────────────
// Bir ürün için uygulanabilir TÜM kuralları döner.
// En spesifik olanı seçmek domain/pricing.SelectRule'ün işidir; öncelik
// mantığı SQL'e dağıtılmaz, tek yerde kalır (docs/trd.md FR-303).
func (q *Queries) ListApplicableRules(ctx context.Context, arg ListApplicableRulesParams) ([]PricingRule, error) {
	rows, err := q.db.Query(ctx, listApplicableRules, arg.CountryID, arg.ServiceID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingRule{}
	for rows.Next() {
		var i PricingRule
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ServiceID,
			&i.CountryID,
			&i.ProductID,
			&i.MarginPercent,
			&i.FixedFeeMinor,
			&i.MinPriceMinor,
			&i.IsActive,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Note,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingRules = `-- name: ListPricingRules :many
SELECT id, scope, service_id, country_id, product_id, margin_percent, fixed_fee_minor, min_price_minor, is_active, valid_from, valid_to, note, created_by_user_id, created_at, updated_at FROM pricing_rules WHERE is_active ORDER BY scope DESC, id
`

func (q *Queries) ListPricingRules(ctx context.Context) ([]PricingRule, error) {
	rows, err := q.db.Query(ctx, listPricingRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricingRule{}
	for rows.Next() {
		var i PricingRule
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ServiceID,
			&i.CountryID,
			&i.ProductID,
			&i.MarginPercent,
			&i.FixedFeeMinor,
			&i.MinPriceMinor,
			&i.IsActive,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Note,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingRulesForAdmin = `-- name: ListPricingRulesForAdmin :many

SELECT
    r.id, r.scope, r.margin_percent, r.fixed_fee_minor, r.min_price_minor,
    r.note, r.valid_from, r.valid_to, r.created_at,
    s.code AS service_code,
    c.iso2 AS country_iso2,
    p.duration_minutes AS product_duration_minutes
FROM pricing_rules r
LEFT JOIN services  s ON s.id = r.service_id
LEFT JOIN countries c ON c.id = r.country_id
LEFT JOIN products  p ON p.id = r.product_id
WHERE r.is_active
ORDER BY r.scope DESC, r.id
`

type ListPricingRulesForAdminRow struct {
	ID                     int64
	Scope                  PricingScope
	MarginPercent          pgtype.Numeric
	FixedFeeMinor          int64
	MinPriceMinor          int64
	Note                   string
	ValidFrom              *time.Time
	ValidTo                *time.Time
	CreatedAt              time.Time
	ServiceCode            *string
	CountryIso2            *string
	ProductDurationMinutes *int32
}

// ─────────────────────── Fiyat kuralı yönetimi (FR-703) ───────────────────────
// Yönetim listesi: etkin kurallar + kapsamın İNSAN OKUR karşılığı.
//
// `ListPricingRules` yalnız ham satırı döner; panelde "service_id 42" değil
// "whatsapp × TR" yazmalı. Ad çözümlemesini Go tarafında N+1 sorguyla yapmak
// yerine tek JOIN'de çözülür.
func (q *Queries) ListPricingRulesForAdmin(ctx context.Context) ([]ListPricingRulesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listPricingRulesForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPricingRulesForAdminRow{}
	for rows.Next() {
		var i ListPricingRulesForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.MarginPercent,
			&i.FixedFeeMinor,
			&i.MinPriceMinor,
			&i.Note,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.ServiceCode,
			&i.CountryIso2,
			&i.ProductDurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveRuleForScope = `-- name: LockActiveRuleForScope :one
SELECT id, scope, service_id, country_id, product_id, margin_percent, fixed_fee_minor, min_price_minor, is_active, valid_from, valid_to, note, created_by_user_id, created_at, updated_at FROM pricing_rules
WHERE is_active
  AND scope = $1
  AND service_id IS NOT DISTINCT FROM $2::bigint
  AND country_id IS NOT DISTINCT FROM $3::bigint
  AND product_id IS NOT DISTINCT FROM $4::bigint
FOR UPDATE
`

type LockActiveRuleForScopeParams struct {
	Scope     PricingScope
	ServiceID *int64
	CountryID *int64
	ProductID *int64
}

// Bir kapsamdaki ETKİN kuralı KİLİTLER.
//
// Kural "güncelleme" yoktur: eski kural pasifleştirilip yenisi eklenir
// (kısmi tekil indeksler aynı kapsamda iki etkin kurala izin vermez).
// Kilit olmadan iki yönetici aynı anda kural yazdığında ikisi de eski satırı
// görür, ikisi de INSERT eder ve biri 23505 ile düşer — hangisinin geçtiği
// rastgele olur. FOR UPDATE bunu sıraya sokar.
//
// IS NOT DISTINCT FROM kullanılır: NULL = NULL karşılaştırması `=` ile
// daima NULL döner ve GLOBAL kapsam (üç alanı da NULL) hiç eşleşmezdi.
func (q *Queries) LockActiveRuleForScope(ctx context.Context, arg LockActiveRuleForScopeParams) (PricingRule, error) {
	row := q.db.QueryRow(ctx, lockActiveRuleForScope,
		arg.Scope,
		arg.ServiceID,
		arg.CountryID,
		arg.ProductID,
	)
	var i PricingRule
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ServiceID,
		&i.CountryID,
		&i.ProductID,
		&i.MarginPercent,
		&i.FixedFeeMinor,
		&i.MinPriceMinor,
		&i.IsActive,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Note,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockQuoteForConsumption = `-- name: LockQuoteForConsumption :one
SELECT id, public_id, user_id, product_id, provider_id, cost_micro, cost_currency, fx_rate, margin_percent, pricing_rule_id, sell_price_minor, stock_at_quote, expires_at, consumed_at, created_at FROM price_quotes
WHERE public_id = $1 AND user_id = $2
FOR UPDATE
`

type LockQuoteForConsumptionParams struct {
	PublicID uuid.UUID
	UserID   int64
}

// Teklifi KİLİTLER. Aynı teklifle iki eşzamanlı satın alma denemesinde
// yalnız biri geçmelidir (docs/trd.md KK-402).
func (q *Queries) LockQuoteForConsumption(ctx context.Context, arg LockQuoteForConsumptionParams) (PriceQuote, error) {
	row := q.db.QueryRow(ctx, lockQuoteForConsumption, arg.PublicID, arg.UserID)
	var i PriceQuote
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProductID,
		&i.ProviderID,
		&i.CostMicro,
		&i.CostCurrency,
		&i.FxRate,
		&i.MarginPercent,
		&i.PricingRuleID,
		&i.SellPriceMinor,
		&i.StockAtQuote,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
