// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// İKİNCİ SAVUNMA HATTI: `AND status = 'PENDING'` koşulu yarışta ikinci çağrıya
	// SIFIR satır döndürür (pgx.ErrNoRows) — bu "zaten sonuçlandırılmış" demektir.
	//
	// 🔴 reviewed_at, status ile AYNI ifadede yazılır: deposit_reviewed_has_time
	// CHECK'i (00008_orders.sql) iki adımlı yazımda 23514 ile düşer.
	ApproveDeposit(ctx context.Context, arg ApproveDepositParams) (Deposit, error)
	// Sitedeki özet: kaç onaylı yorum ve ortalama puan.
	//
	// 🔴 ORTALAMA ONDA BİRLİK TAM SAYI OLARAK döner (4.7 → 47), kayan nokta
	// olarak değil. Para değil ama aynı gerekçe geçerli: `float64` üzerinden
	// taşınan bir ortalama JSON'da 4.699999999999999 olur ve arayüzde iki farklı
	// yerde iki farklı yuvarlanır. Bölme TEK YERDE, gösterimde yapılır.
	// Yorum yoksa total 0 gelir ve ARAYÜZ BÖLÜMÜ HİÇ RENDER ETMEZ.
	ApprovedReviewStats(ctx context.Context) (ApprovedReviewStatsRow, error)
	AssignRole(ctx context.Context, arg AssignRoleParams) error
	// SAHİPLENME: sağlayıcıda kapatma denemesini TEK bir işçiye verir.
	//
	// Kapatma bir HTTP çağrısı içerir; dış çağrı transaction içinde yapılmaz
	// (değişmez #5), dolayısıyla satır kilidi çağrı boyunca tutulamaz —
	// `GetOrderForUpdate` bir transaction dışında çağrıldığında kilit deyim
	// biter bitmez bırakılır ve hiçbir şeyi korumaz. Bunun yerine satır koşullu
	// bir UPDATE ile sahiplenilir: yarışı kaybeden işçi SIFIR satır alır
	// (ConsumeQuote ile aynı desen) ve sağlayıcıya hiç gitmez.
	//
	// Kira süresi dolduğunda satır kendiliğinden yeniden uygun hâle gelir: çağrı
	// sırasında ölen bir işçi satırı sonsuza kadar bloke edemez.
	//
	// `provider_closed_at IS NULL` koşulu da buradadır: zaten kapatılmış siparişe
	// ikinci kez Cancel/Finish gönderilmez.
	//
	// 🔴 DURUM SÜZGECİ SAHİPLENMENİN PARÇASIDIR, ayrı bir `if` değil.
	//
	// Süzgeç Go tarafında dururken kapatılabilir olmayan bir satır (PENDING /
	// ACTIVE) de sahiplenilebiliyordu: işçi satırı alıyor, durumu görüp
	// `ReleaseOrderClose` ile bırakıyordu. O iki adımın ARASINDA sipariş terminal
	// olursa, terminal geçişin doğurduğu kapatma goroutine'i sahiplenmeyi
	// KAYBEDİYOR ve sessizce nil dönüyordu; hemen ardından gelen `release` de
	// kirayı siliyordu. Sonuç: terminal sipariş, `provider_closed_at IS NULL` ve
	// sağlayıcıya SIFIR çağrı — numara `activation-reaper`ın bir sonraki turuna
	// kadar (≤60 sn) açıkta.
	//
	// Deterministik olarak üretilebiliyordu: `-count=10` → 10/10.
	// test: rental_integration_test.go#TestRentalEndRaceWithProviderCloseHasSingleEffect
	ClaimOrderClose(ctx context.Context, arg ClaimOrderCloseParams) (Order, error)
	// Tek kullanımlıktır: UPDATE ... RETURNING ile atomik olarak tüketilir.
	// Ayrı SELECT + UPDATE yapılsaydı iki eşzamanlı istek aynı token'ı kullanabilirdi.
	ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (AuthToken, error)
	// Tek kullanımlık işaretleme.
	// WHERE consumed_at IS NULL sayesinde yarış durumunda ikinci çağrı
	// SIFIR satır döner — kilitle birlikte çift savunma.
	ConsumeQuote(ctx context.Context, arg ConsumeQuoteParams) (PriceQuote, error)
	// Bir kapsamdaki etkin kural sayısı.
	//
	// Son GLOBAL kuralın pasifleştirilmesini engellemek için kullanılır: GLOBAL
	// kural kalmazsa ListApplicableRules boş döner, SelectRule ErrNoRule verir ve
	// SİSTEM SATIŞ YAPAMAZ hâle gelir.
	CountActiveRulesByScope(ctx context.Context, scope PricingScope) (int64, error)
	CountAllOrders(ctx context.Context, arg CountAllOrdersParams) (int64, error)
	CountAuditLogsForAdmin(ctx context.Context, arg CountAuditLogsForAdminParams) (int64, error)
	// 🔴 SÜZGEÇ VE JOIN, ListDepositsForAdmin İLE BİREBİR AYNI. `q` kullanıcı
	// sütunlarında arandığı için sayım da `users`a katılmak ZORUNDA; katılmasaydı
	// arama yapıldığında sayfalama yanlış toplam gösterirdi.
	CountDepositsForAdmin(ctx context.Context, arg CountDepositsForAdminParams) (int64, error)
	CountDimensionMaps(ctx context.Context, arg CountDimensionMapsParams) (int64, error)
	//
	// 🔴 SÜZGEÇLER `ListLedgerEntries` İLE BİREBİR AYNI.
	//
	// ÖNCEDEN DEĞİLDİ: liste `from_ts`/`to_ts` süzerken sayım SÜZMÜYORDU. Tarih
	// aralığı arayüzde henüz açılmamıştı, yani hata gizli kalmıştı; açıldığı gün
	// sayfalama "1–25 / 412" derken liste 3 satır gösterecekti. `q` eklenirken
	// ikisi tek elden yazıldı.
	// test: wallet_integration_test.go#TestListLedgerEntriesSuzgecleri
	CountLedgerEntries(ctx context.Context, arg CountLedgerEntriesParams) (int64, error)
	CountOrderMessages(ctx context.Context, orderID int64) (int64, error)
	// Yönetim menüsündeki rozet için: kaç yorum karar bekliyor.
	CountPendingReviews(ctx context.Context) (int64, error)
	// Süzgeç koşulu ListReviewsForAdmin ile BİREBİR AYNI olmalıdır; ayrışırsa
	// sayfalama "23 kayıt" der ama 12 satır gösterir.
	// `q` kullanıcı sütunlarında da arandığı için sayım `users`a katılmak zorunda.
	CountReviewsForAdmin(ctx context.Context, arg CountReviewsForAdminParams) (int64, error)
	// 🔴 SÜZGEÇ `ListReviewsForUser` İLE AYNI OLMAK ZORUNDA; ayrışırsa sayfalama
	// yalan söyler (bkz. orders.sql, CountUserOrders notu).
	CountReviewsForUser(ctx context.Context, arg CountReviewsForUserParams) (int64, error)
	// Süzgeç koşulu ListTicketsForAdmin ile BİREBİR AYNI olmalıdır; ayrışırsa
	// sayfalama "23 kayıt" der ama 12 satır gösterir.
	// `q` kullanıcı sütunlarında da arandığı için sayım `users`a katılmak zorunda.
	CountTicketsForAdmin(ctx context.Context, arg CountTicketsForAdminParams) (int64, error)
	// 🔴 SÜZGEÇ `ListUserDeposits` İLE AYNI OLMAK ZORUNDA; ayrışırsa sayfalama
	// yalan söyler (bkz. orders.sql, CountUserOrders notu).
	// test: deposit_integration_test.go#TestListUserDepositsDurumSuzgeci
	CountUserDeposits(ctx context.Context, arg CountUserDepositsParams) (int64, error)
	//
	// 🔴 SÜZGEÇLER `ListUserOrders` İLE BİREBİR AYNI OLMAK ZORUNDA. Ayrışırsa
	// sayfalama yalan söyler: "1–25 / 300" yazarken liste 4 satır gösterir ve
	// "Sonraki" boş sayfa açar. İki sorgu tek bir kavramın iki yarısıdır.
	// test: order_integration_test.go#TestListUserOrdersFiltreleri
	CountUserOrders(ctx context.Context, arg CountUserOrdersParams) (int64, error)
	// 🔴 SÜZGEÇ `ListUserTickets` İLE AYNI OLMAK ZORUNDA; ayrışırsa sayfalama
	// yalan söyler (bkz. orders.sql, CountUserOrders notu).
	CountUserTickets(ctx context.Context, arg CountUserTicketsParams) (int64, error)
	CountUsersForAdmin(ctx context.Context, arg CountUsersForAdminParams) (int64, error)
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	// Bakiye yükleme talepleri (FR-500 … FR-503).
	//
	// Ödeme YÖNTEMİ sorguları burada değil, queries/orders.sql içindedir
	// (deposit_methods CRUD'u zaten yazılmıştı).
	// 🔴 tx_hash HAVALEDE NULL BIRAKILIR, boş string yazılmaz: deposits_tx_hash_uniq
	// kısmi indeksi (WHERE tx_hash IS NOT NULL) NULL'ları hariç tutar. '' yazılırsa
	// kullanıcının İKİNCİ havale talebi 23505 alır ve bir daha havale bildiremez.
	// test: deposit_integration_test.go#TestBankTransferDepositLeavesTxHashNull
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	CreateDepositMethod(ctx context.Context, arg CreateDepositMethodParams) (DepositMethod, error)
	// Sipariş kaydı — T2 içinde, sağlayıcı çağrısı BAŞARILI olduktan sonra.
	//
	// Katalog alanları ANLIK GÖRÜNTÜ olarak yazılır: servis/ülke satırları katalog
	// senkronunda silinebilir, sipariş geçmişi buna dayanamaz.
	// `product_kind` de bir ANLIK GÖRÜNTÜDÜR: "iade mi Finish mi" kararı katalog
	// satırına JOIN ile verilemez, çünkü o satır silinebilir (product_id ON DELETE
	// SET NULL). `refundable_until` NULL ise ek bir iptal tavanı yoktur (aktivasyon).
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePricingRule(ctx context.Context, arg CreatePricingRuleParams) (PricingRule, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	// ─────────────────────── Teklif ───────────────────────
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (PriceQuote, error)
	// Kira dönemi kaydı — sipariş satırıyla AYNI transaction'da (T2) yazılır.
	//
	// Tablo 00008'de açıldı ama hiçbir kod ona yazmıyordu: `duration_hours`
	// sağlayıcı çağrısından sonra çöpe gidiyordu ve `rental_ends_at` diye bir
	// gerçek yoktu. Kira dönemi üzerine kurulacak her rapor "hiç kiralık yok"
	// derdi — para akarken.
	//
	// YETKİLİ KAYNAK `orders.expires_at`TİR; bu satır dönemin KAYDIDIR. İkisini
	// bağımsız iki doğruluk kaynağı yapmak, uzatmadan sonra birinin
	// güncellenmemesiyle biter.
	CreateRentalDetail(ctx context.Context, arg CreateRentalDetailParams) (RentalDetail, error)
	// Müşteri yorumları.
	//
	// ÜÇ AYRI SORGU AİLESİ vardır ve karıştırılmaz:
	//   *ForUser   → sahiplik SORGUNUN PARÇASIDIR (değişmez #7)
	//   *ForAdmin  → sahiplik kısıtı yoktur; koruma izin ara katmanındadır
	//   Approved*  → OTURUMSUZ, sitede gösterilir; KİŞİSEL VERİ SEÇMEZ
	// Durum İSTEMCİDEN ALINMAZ: yeni yorum her zaman PENDING'dir (varsayılan) ve
	// oradan yalnız durum makinesi çıkarır (değişmez #13).
	//
	// 🔴 "Bu kullanıcının bekleyen yorumu var mı?" diye ÖNCE SELECT YAPILMAZ.
	// Kısıt kısmi benzersiz indekstedir (reviews_one_pending_per_user_idx) ve bu
	// INSERT 23505 ile düşer. Uygulama katmanındaki kontrol iki eşzamanlı isteğin
	// ikisi tarafından da geçilirdi.
	// test: internal/service/review/review_integration_test.go#TestConcurrentSubmitsLeaveOnePending
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Destek talepleri (FR-600).
	//
	// İKİ AYRI SORGU AİLESİ vardır ve karıştırılmaz:
	//   *ForUser  → sahiplik SORGUNUN PARÇASIDIR (değişmez #7)
	//   *ForAdmin → sahiplik kısıtı yoktur; koruma izin ara katmanındadır
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	// 🔴 is_staff AÇIKÇA VERİLİR. Sütunun varsayılanı yoktur (00012_tickets.sql):
	// parametreyi unutan bir çağrı derlenmez ya da veritabanında düşer, sessizce
	// "kullanıcı yazdı" diye kaydedilmez (KK-600).
	CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (TicketMessage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivatePricingRule(ctx context.Context, id int64) error
	// Kararı YAZAR, VERMEZ. Yeni durum serviste domain/review ile hesaplanır
	// (değişmez #13); bu sorgu yalnız sonucu kaydeder.
	//
	// 🔴 status, rejection_reason ve reviewed_at AYNI İFADEDE yazılır:
	// review_decided_has_time ve review_reason_only_when_rejected CHECK'leri
	// iki adımlı bir yazımda 23514 ile düşer.
	DecideReview(ctx context.Context, arg DecideReviewParams) (Review, error)
	// Yöntem SİLİNİR ama geçmiş yükleme kayıtları KALIR: deposits.method_id
	// ON DELETE SET NULL ve method_name anlık görüntü olarak saklanıyor.
	DeleteDepositMethod(ctx context.Context, publicID uuid.UUID) error
	// Süresi dolmuş e-posta doğrulama / şifre sıfırlama token'larını siler.
	//
	// Satır ham token taşımaz, yalnız SHA-256 özeti (migration 00001) — ama
	// kullanıcı bağı ve zaman damgası kişisel veridir, süresi dolmuş token'ın
	// işlevi ise yoktur (ConsumeAuthToken `expires_at > now()` arar).
	//
	// `expires_at` üzerinde indeks YOK: satır sayısı doğrulama/sıfırlama isteği
	// kadardır (ölçüm: 27) ve iş saatte bir koşar. İndeks eklemek her token
	// yazımına maliyet bindirir, kazancı ise bugün ölçülemez.
	DeleteExpiredAuthTokens(ctx context.Context, arg DeleteExpiredAuthTokensParams) (int64, error)
	// Tüketilmemiş ve süresi geçmiş fiyat tekliflerini siler.
	//
	// TÜKETİLMİŞ TEKLİF BU SORGUYA DÜŞMEZ (`consumed_at IS NULL` süzgeci):
	// tüketilmiş teklif bir siparişin fiyat kanıtıdır (`orders.quote_id`) ve
	// sipariş kaydıyla aynı süre durur. Ayrıca yetim provizyon işi (FR-408) tam
	// olarak o satırları tarar; silinseydi kurtarılamayan para kalırdı.
	// test: retention_integration_test.go#TestRetentionKeepsConsumedQuotes
	DeleteExpiredQuotes(ctx context.Context, arg DeleteExpiredQuotesParams) (int64, error)
	// Süresi dolmuş oturum satırlarını siler.
	//
	// 7 GÜNLÜK PAY KALDIRILDI: sorgu eskiden `expires_at < now() - interval '7 days'`
	// diyordu ve hiçbir yerden çağrılmıyordu. İlan edilen süre "oturum süresi
	// dolunca" olduğuna göre payın karşılığı yok. Süresi dolmuş satırın işlevi
	// zaten bitmiştir (GetSession `expires_at > now()` arar); geriye yalnız IP ve
	// tarayıcı imzası, yani kişisel veri kalır.
	//
	// ÇIKIŞ YAPILMIŞ (revoked_at dolu) ama süresi DOLMAMIŞ oturum burada durur;
	// süresi geldiğinde aynı sorguya düşer. `sessions_expires_at_idx` alt sorguyu
	// indeksten karşılar.
	DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) (int64, error)
	// 2 yıldan eski denetim kayıtlarını siler.
	//
	// Denetim kaydı "kim, ne zaman, neyi değiştirdi"yi tutar (FR-705) ve IP,
	// tarayıcı imzası, eski/yeni değerler gibi kişisel veri taşır. Ticari
	// zorunluluk kaydın süresiz durmasını gerektirmiyor; ilan edilen süre 2 yıl.
	//
	// `created_at` tek başına indeksli değil (mevcut indeksler entity ve aktör
	// eksenli), alt sorgu tarama yapar. Tablo yönetici işlemleriyle sınırlı
	// büyüdüğü için saatlik tarama bugün ucuzdur; hacim büyürse (created_at)
	// indeksi eklenmelidir.
	DeleteOldAuditLogs(ctx context.Context, arg DeleteOldAuditLogsParams) (int64, error)
	EmailExists(ctx context.Context, email string) (bool, error)
	FindLedgerEntriesByReference(ctx context.Context, arg FindLedgerEntriesByReferenceParams) ([]LedgerEntry, error)
	// Cüzdan sorguları.
	//
	// BU DOSYADAKİ SIRALAMA KRİTİKTİR ve wallet servisinde birebir uygulanır:
	//   1) idempotency kontrolü  →  2) satır KİLİDİ  →  3) yeterlilik  →  4) yazım
	// Kilitsiz bir okuma-değiştir-yazma döngüsü eşzamanlı isteklerde bakiyeyi bozar
	// (docs/memory.md §3.6 — eski prototipin hatası).
	// İdempotency: bu anahtarla daha önce işlem yapıldıysa sonucu döner.
	FindLedgerEntryByKey(ctx context.Context, idempotencyKey string) (LedgerEntry, error)
	GetCountryByISO(ctx context.Context, iso2 string) (Country, error)
	// Yönetim yolu: sahiplik kısıtı YOKTUR, izin kontrolü middleware'dedir
	// (deposits:read / deposits:approve).
	GetDeposit(ctx context.Context, publicID uuid.UUID) (Deposit, error)
	// Tekrarlanan talep isteğinde MEVCUT talebi döner.
	//
	// Kullanıcı kapsamı sorgunun parçasıdır: iki kullanıcının aynı anahtarı
	// üretmesi çakışma değil, ayrı işlemdir.
	// test: deposit_integration_test.go#TestDepositCreateIsIdempotent
	GetDepositByIdempotencyKey(ctx context.Context, arg GetDepositByIdempotencyKeyParams) (Deposit, error)
	// SAHİPLİK SORGUNUN PARÇASIDIR (CLAUDE.md değişmez #7). Başkasının talebi ile
	// var olmayan talep AYNI sonucu (sıfır satır) verir.
	GetDepositForUser(ctx context.Context, arg GetDepositForUserParams) (Deposit, error)
	GetDepositMethod(ctx context.Context, publicID uuid.UUID) (DepositMethod, error)
	GetLatestFXRate(ctx context.Context, arg GetLatestFXRateParams) (FxRate, error)
	// Webhook korelasyonu: sağlayıcı YALNIZ aktivasyon kimliğini taşır.
	GetOrderByRemote(ctx context.Context, arg GetOrderByRemoteParams) (Order, error)
	// Durum değiştirmeden ÖNCE kilitle. Kilitsiz okuma + yazma, iki işçinin aynı
	// siparişi aynı anda sonlandırmasına ve çift iadeye yol açar.
	GetOrderForUpdate(ctx context.Context, id int64) (Order, error)
	// SAHİPLİK SORGUNUN PARÇASIDIR (CLAUDE.md değişmez #7).
	// Ayrı bir `if order.UserID != userID` kontrolü yazılmaz: unutulabilir.
	GetOrderForUser(ctx context.Context, arg GetOrderForUserParams) (Order, error)
	GetPricingRule(ctx context.Context, id int64) (PricingRule, error)
	// Bir kuralın kapsamını İNSAN OKUR kodlarla verir.
	//
	// Denetim kaydının entity_id'si için gerekir: oraya sayısal kimlik yazmak
	// (Değişmez #10) kaydı hem okunmaz hem de kimlik yeniden kullanıldığında
	// yanıltıcı yapar. "SERVICE_COUNTRY:whatsapp:TR" bir yıl sonra da aynı şeyi
	// anlatır.
	GetPricingRuleLabels(ctx context.Context, id int64) (GetPricingRuleLabelsRow, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetProductForActivation(ctx context.Context, arg GetProductForActivationParams) (Product, error)
	GetProductForRental(ctx context.Context, arg GetProductForRentalParams) (Product, error)
	GetProvider(ctx context.Context, id int64) (Provider, error)
	GetProviderByName(ctx context.Context, name string) (Provider, error)
	// Bir ürünün, BELİRLİ BİR SAĞLAYICIDAKİ karşılıklarını verir.
	//
	// Sağlayıcıya istek atarken BİZİM kodlarımız (services.code, countries.iso2)
	// KULLANILAMAZ. HeroSMS ülkeyi "62" bilir, biz "TR" biliriz. Çeviri burada
	// yapılır; yapılmazsa sağlayıcı "böyle bir ülke yok" der ve teklif düşer.
	// test: internal/service/pricing/remote_codes_integration_test.go#TestProviderReceivesItsOwnCodes
	GetProviderRemoteCodes(ctx context.Context, arg GetProviderRemoteCodesParams) (GetProviderRemoteCodesRow, error)
	GetQuoteByPublicID(ctx context.Context, publicID uuid.UUID) (PriceQuote, error)
	// Sipariş anlık görüntüsü için servis/ülke adları.
	//
	// Sipariş satırına KOPYALANIR: katalog satırları senkronda silinebilir ve
	// sipariş geçmişi bir yıl sonra da okunabilir olmalıdır.
	GetQuoteContext(ctx context.Context, quoteID int64) (GetQuoteContextRow, error)
	GetRemoteCode(ctx context.Context, arg GetRemoteCodeParams) (string, error)
	GetRentalDetail(ctx context.Context, orderID int64) (RentalDetail, error)
	// SAHİPLİK SORGUNUN PARÇASIDIR (değişmez #7). Başkasının yorumu ile var
	// olmayan yorum AYNI sonucu (sıfır satır) verir; servis ikisini de
	// ErrNotFound'a çevirir.
	// test: internal/transport/http/handler/review_integration_test.go#TestUserCannotSeeOthersReview
	GetReviewForUser(ctx context.Context, arg GetReviewForUserParams) (Review, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetServiceByCode(ctx context.Context, code string) (Service, error)
	GetSession(ctx context.Context, id string) (Session, error)
	// Sayısal id dışarı verilmez: kullanıcı users.public_id ile gösterilir.
	GetTicketForAdmin(ctx context.Context, publicID uuid.UUID) (GetTicketForAdminRow, error)
	// SAHİPLİK SORGUNUN PARÇASIDIR (CLAUDE.md değişmez #7). Başkasının talebi ile
	// var olmayan talep AYNI sonucu (sıfır satır) verir; servis ikisini de
	// ErrNotFound'a çevirir.
	GetTicketForUser(ctx context.Context, arg GetTicketForUserParams) (Ticket, error)
	GetUserBalance(ctx context.Context, id int64) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByPublicID(ctx context.Context, publicID uuid.UUID) (User, error)
	GetUserPermissions(ctx context.Context, userID int64) ([]string, error)
	GetUserRoles(ctx context.Context, userID int64) ([]Role, error)
	GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// ─────────────────────── Kur ───────────────────────
	InsertFXRate(ctx context.Context, arg InsertFXRateParams) (FxRate, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	// ─────────────────────────── Mesajlar ───────────────────────────
	// DEDUP: aynı mesaj webhook, yoklama ve yeniden gönderimlerle en az sekiz kez
	// gelebilir. UNIQUE kısıt son savunma hattıdır; ON CONFLICT ile sessizce
	// yutulur ve `inserted` alanı gerçekten yeni mi söyler.
	InsertOrderMessage(ctx context.Context, arg InsertOrderMessageParams) (OrderMessage, error)
	InvalidateUserTokens(ctx context.Context, arg InvalidateUserTokensParams) error
	// Kullanıcı: yalnız aktif yöntemler.
	ListActiveDepositMethods(ctx context.Context) ([]DepositMethod, error)
	// ─────────────────────── Sağlayıcı ───────────────────────
	ListActiveProviders(ctx context.Context) ([]Provider, error)
	// `rental-poller` için: dönemi süren kiralıklar.
	//
	// İKİ DURUM BİRDEN: 'PENDING' (henüz mesaj gelmedi) ve 'ACTIVE' (en az bir
	// mesaj geldi, dönem sürüyor). Kiralıkta mesaj gelmesi yoklamayı bitirmez —
	// ürünün tamamı "30 gün boyunca gelen HER mesajı gör"dür.
	//
	// 🔴 SIRALAMA `created_at` DEĞİL — ve bu bir hata düzeltmesidir.
	//
	// `created_at ASC` + `LIMIT` deseni aktivasyonda güvenlidir çünkü satırlar ~20
	// dakikada kümeden çıkar; kiralıkta küme dönem boyunca (24–4320 saat) SABİT
	// kalır. 101. kiralık, ilk 100'ün hiçbiri bitmeden hiçbir turda görünmezdi:
	// webhook kaybolduğunda o kullanıcı 30 gün boyunca tek mesaj görmez.
	//
	// `last_polled_at` turu dönüşümlü yapar. `NULLS FIRST` yeni satırın ilk turda
	// görülmesini garanti eder; `id` eşitlik hâlinde belirlenimli sıra verir
	// (aynı damgayı taşıyan bir toplu güncellemeden sonra tur ilerlemeye devam
	// etsin).
	// test: ../internal/service/order/rental_integration_test.go#TestRentalPollNeverStarvesNewestRental
	ListActiveRentalsForPoll(ctx context.Context, arg ListActiveRentalsForPollParams) ([]Order, error)
	// ─────────────────────────── Yönetim ───────────────────────────
	// Yönetim paneli — `orders:read_all` izni gerektirir.
	ListAllOrders(ctx context.Context, arg ListAllOrdersParams) ([]ListAllOrdersRow, error)
	// ─────────────────────── Fiyat kuralları ───────────────────────
	// Bir ürün için uygulanabilir TÜM kuralları döner.
	// En spesifik olanı seçmek domain/pricing.SelectRule'ün işidir; öncelik
	// mantığı SQL'e dağıtılmaz, tek yerde kalır (docs/trd.md FR-303).
	ListApplicableRules(ctx context.Context, arg ListApplicableRulesParams) ([]PricingRule, error)
	// 🔴 SİTEDE GÖSTERİLEN LİSTE — OTURUMSUZ ERİŞİLİR.
	//
	// E-POSTA, sayısal id ve user_id BU SORGUDA SEÇİLMEZ. "Yanıtta gizleriz"
	// yeterli değildir: alan seçilirse bir gün birinin onu DTO'ya koyması bir
	// satır uzaklıktadır ve sızıntı sessiz olur. Seçilmeyen sütun sızamaz.
	// test: internal/transport/http/handler/review_integration_test.go#TestPublicReviewsNeverExposeEmail
	//
	// DISTINCT ON (user_id): bir kullanıcının zaman içinde birden fazla onaylı
	// yorumu olabilir (fikri değişip yenisini yazar). Sitede YALNIZ EN SONU
	// gösterilir; aksi hâlde aynı kişi listede iki kez çıkar ve yorum sayısı
	// gerçekte olduğundan kalabalık görünür.
	ListApprovedReviews(ctx context.Context, lim int32) ([]ListApprovedReviewsRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	// ─────────────────────── Denetim kaydı okuma (FR-705) ───────────────────────
	// Aktör / varlık / eylem / tarih süzgeçli, sayfalı denetim kaydı.
	//
	// AKTÖR public_id İLE SÜZÜLÜR, sayısal id ile değil (Değişmez #10): dışarıya
	// verilen kimlik neyse süzgeç de onu almalı, yoksa panel önce kullanıcıyı
	// sayısal kimliğe çevirmek zorunda kalır ve o kimlik yanıtta da görünür.
	//
	// E-POSTA SEÇİLMEZ. Aktörü tanımak için public_id + kullanıcı adı yeter;
	// e-posta denetim listesinde toplu olarak dışarı akan kişisel veridir.
	// id DESC ikinci ölçüt: aynı milisaniyede yazılan iki kayıt sayfalar arasında
	// yer değiştirirse aynı satır iki sayfada birden görünür ya da hiç görünmez.
	ListAuditLogsForAdmin(ctx context.Context, arg ListAuditLogsForAdminParams) ([]ListAuditLogsForAdminRow, error)
	// Kullanıcıya gösterilecek katalog: en az bir sağlayıcıda stoklu ürünler.
	// 🔴 `s.sort_order` GROUP BY'a AÇIKÇA eklenmek ZORUNDA. Gruplama anahtarındaki
	// `p.id` yalnız `products` sütunlarını işlevsel bağımlılıkla kurtarır;
	// `services` sütunları için PK (`s.id`) gerekirdi. Eksikse Postgres
	// "column s.sort_order must appear in the GROUP BY clause" hatasını verir.
	//
	// NOT: bu cümle bizim verdiğimiz bir güvence değil, Postgres'in davranışının
	// tarifidir. "reddeder" gibi bir fiil kullanılırsa scripts/check-guarantees.py
	// bunu güvence sayar ve aynı blokta bir `test:` atfı arar — bir kez düşürdü.
	// ÖNCE POPÜLERLİK, SONRA TÜRKİYE.
	//
	// `s.sort_order` popülerlik sırasıdır (web/scripts/servis-siralama.sql).
	// Alfabetik sıra kullanıcının aradığı servisi değil, adı "A" ile başlayanı
	// öne çıkarırdı.
	//
	// Ülke düzeyinde TÜRKİYE HER ZAMAN ÖNCE: kullanıcıların çoğu Türkiye'den ve
	// en çok aradıkları ülke bu. Alfabetik sırada "Türkiye" 190 ülkenin sonlarında
	// kalıyor ve kullanıcı her seferinde listeyi sonuna kadar kaydırıyor.
	//
	// Sıralama SUNUCUDA yapılır: istemcide yapılsaydı her istemci kendi kuralını
	// uygular, mobil ve masaüstü farklı sıralanırdı.
	ListAvailableProductsForCatalog(ctx context.Context, arg ListAvailableProductsForCatalogParams) ([]ListAvailableProductsForCatalogRow, error)
	// ─────────────────────── Ödeme yöntemleri ───────────────────────
	// Yönetim: tüm yöntemler (pasifler dahil).
	ListDepositMethods(ctx context.Context) ([]DepositMethod, error)
	// Sayısal id dışarı verilmez: kullanıcı users.public_id ile gösterilir.
	ListDepositsForAdmin(ctx context.Context, arg ListDepositsForAdminParams) ([]ListDepositsForAdminRow, error)
	ListDimensionMaps(ctx context.Context, arg ListDimensionMapsParams) ([]ProviderDimensionMap, error)
	// `rental-closer` için: kira dönemi bitmiş ama hâlâ kapatılmamış kiralıklar.
	//
	// 'PENDING' de dahildir: hiç mesaj almamış bir kiralık 'ACTIVE'e hiç geçmez ve
	// dönem sonunda yine kapatılmalıdır (FR-412: her sipariş sağlayıcıda kapanır).
	ListEndedRentals(ctx context.Context, arg ListEndedRentalsParams) ([]Order, error)
	// `order-expirer` için: süresi dolmuş ama hâlâ beklemede olan AKTİVASYONLAR.
	//
	// 🔴 KİRALIKLAR DIŞARIDA — bu sorgunun sonucu TAM İADE demektir.
	//
	// Kiralıkta satılan şey süredir: numara 30 gün ayrıldı, sağlayıcıya ödendi,
	// kullanıcı istediği an kullanabildi. Kod gelmemesi iade sebebi değildir ve
	// sağlayıcının ücretsiz iptal penceresi (≈20 dk) 1. günde kapandığı için o
	// parayı geri almanın yolu da yoktur: buradan yazılacak iadenin %100'ü bizim
	// cebimizden çıkar ve "kiralık al, 30. günde paranı al" tekrarlanabilir bir
	// sızıntı olur. Dönem sonu `ListEndedRentals` → EndRental ile işlenir; orada
	// deftere kayıt yazılmaz.
	// test: ../internal/service/order/rental_integration_test.go#TestRentalNeverAutoRefundsAtEndOfPeriod
	ListExpiredPendingOrders(ctx context.Context, arg ListExpiredPendingOrdersParams) ([]Order, error)
	// Kullanıcının hareket dökümü. SAHİPLİK sorgunun parçasıdır: user_id ayrı bir
	// if kontrolü değil, WHERE koşuludur (docs/design.md §10).
	//
	// `q` SERBEST METİN: not ve referans kimliği. Tür adı ARANMAZ — "iade" yazan
	// kullanıcı REFUND satırlarını beklerdi ama tür adı veritabanında DURMAZ,
	// sunucuda enum'dan üretilir (`ledgerTypeLabel`). O iş tür süzgecinindir.
	ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]LedgerEntry, error)
	// Bir ürün için sağlayıcı teklifleri; en ucuz önce.
	ListOffersForProduct(ctx context.Context, productID int64) ([]ListOffersForProductRow, error)
	// YALNIZ YÖNETİM ÖNİZLEMESİ İÇİN: stok koşulu yoktur.
	//
	// `ListOffersForProduct` stoksuz teklifleri eler — satış yolunda doğru olan
	// budur. Ama yönetici marjı değiştirirken stoğu tükenmiş bir ürünün fiyatını
	// da görebilmeli: maliyet biliniyor, satılamıyor olması fiyatı bilinmez
	// yapmaz. Bu sorgu SATIŞ YOLUNDA KULLANILMAZ.
	// test: internal/service/pricing/rules_integration_test.go#TestPreviewWorksWhenOutOfStock
	ListOffersForProductAnyStock(ctx context.Context, productID int64) ([]ListOffersForProductAnyStockRow, error)
	ListOrderMessages(ctx context.Context, orderID int64) ([]OrderMessage, error)
	// `orphan-hold-reaper` için: PARASI ÇEKİLMİŞ ama siparişi olmayan teklifler.
	//
	// T1 (teklif tüket + bakiye düş) ile T2 (sipariş yaz) arasında süreç ölürse
	// kullanıcının parası gitmiş ama elinde numara yoktur. Bu sorgu o durumu bulur.
	//
	// `consumed_at` eşiği, henüz T2'ye ulaşmamış NORMAL akışları yakalamamak için:
	// satın alma birkaç saniye sürer, hemen "yetim" ilan etmek çalışan bir siparişi
	// iade eder.
	//
	// 🔴 İADE EDİLMİŞ OLANLAR DIŞLANIR — yoksa bu sorgu KALICI OLARAK TIKANIR.
	//
	// Sağlayıcı hatasıyla düşen HER satın alma (stok yok, 5xx, geçmiş expiredAt)
	// tam olarak bu profilde bir satır bırakır: teklif tüketilmiş, iade `refundHold`
	// tarafından ZATEN yazılmış, sipariş satırı hiç oluşmamış. Bu satırları dışlayan
	// bir kolon yoktu; her başarısız satın alma sorguya kalıcı bir satır ekliyordu.
	// 100 böyle satır biriktiğinde (tek sağlayıcı kesintisinde dakikalar sürer)
	// `LIMIT` tümüyle ölü satırlarla dolar ve GERÇEKTEN iade edilmemiş yeni yetimler
	// hiç görülmez. Yani güvenlik ağı sessizce yırtılır.
	//
	// Ayrı bir kolon yerine DEFTERE bakılır: iade anahtarı zaten deterministik
	// (`order:{quote_public_id}:refund`, service/order/service.go:368) ve defter
	// değişmezdir — ikinci bir doğruluk kaynağı yaratmaktansa var olanı sorgularız.
	// test: order_integration_test.go#TestOrphanHoldQuerySkipsAlreadyRefunded
	ListOrphanHolds(ctx context.Context, arg ListOrphanHoldsParams) ([]PriceQuote, error)
	// ─────────────────────────── İşçi sorguları ───────────────────────────
	// `order-poller` için: kod bekleyen, süresi dolmamış AKTİVASYON siparişleri.
	//
	// 🔴 KİRALIKLAR DIŞARIDA — sıklık farkı yüzünden, tercih olduğu için değil.
	// Aktivasyon ~20 dakika yaşar; kiralık 24–4320 SAAT. Sıralama `created_at`
	// olduğu için 100 canlı kiralık bu LIMIT'in başını günlerce işgal eder ve
	// aktivasyon siparişleri hiç yoklanmaz: webhook kaybolduğunda kod hiç gelmez,
	// order-expirer tam iade yazar — hem sağlayıcı maliyeti hem satış kaybı.
	// Kiralıkların kendi turu vardır (ListActiveRentalsForPoll, 5 dakika).
	// test: ../internal/service/order/rental_integration_test.go#TestRentalsDoNotStarveActivationPoll
	ListPendingOrdersForPoll(ctx context.Context, arg ListPendingOrdersForPollParams) ([]Order, error)
	ListPricingRules(ctx context.Context) ([]PricingRule, error)
	// Saklama temizliği (DeleteExpiredQuotes) queries/retention.sql içindedir.
	// ─────────────────────── Fiyat kuralı yönetimi (FR-703) ───────────────────────
	// Yönetim listesi: etkin kurallar + kapsamın İNSAN OKUR karşılığı.
	//
	// `ListPricingRules` yalnız ham satırı döner; panelde "service_id 42" değil
	// "whatsapp × TR" yazmalı. Ad çözümlemesini Go tarafında N+1 sorguyla yapmak
	// yerine tek JOIN'de çözülür.
	ListPricingRulesForAdmin(ctx context.Context) ([]ListPricingRulesForAdminRow, error)
	// Yönetim sağlayıcı listesi.
	//
	// 🔴 api_key_enc SEÇİLMEZ. Şifreli hâli bile dışarı verilmez: panelde
	// gösterilecek bir şey değil ve varlığı/uzunluğu bilgi sızdırır.
	// Anahtarın TANIMLI OLUP OLMADIĞI yeterli bilgidir.
	ListProvidersForAdmin(ctx context.Context) ([]ListProvidersForAdminRow, error)
	// Mutabakat: defter toplamı ile önbelleklenmiş bakiyenin uyuşmadığı kullanıcılar.
	// Boş dönmesi beklenir; dönmezse ALARM üretilir (docs/trd.md FR-205).
	ListReconciliationDrift(ctx context.Context, limit int32) ([]ListReconciliationDriftRow, error)
	// `provider-refund-retry` için: sağlayıcıdan iade beklenen siparişler.
	ListRefundRetryOrders(ctx context.Context, arg ListRefundRetryOrdersParams) ([]Order, error)
	ListRentalCountriesForService(ctx context.Context, serviceCode string) ([]ListRentalCountriesForServiceRow, error)
	// Bir servis × ülke için kiralanabilir süreler ve en düşük maliyet.
	//
	// Fiyat BURADA DÖNMEZ: kullanıcıya gösterilen fiyat teklif (quote) ile
	// verilir. Buradaki maliyet yalnız SIRALAMA içindir ve dışa açılmaz.
	ListRentalDurationsForCatalog(ctx context.Context, arg ListRentalDurationsForCatalogParams) ([]ListRentalDurationsForCatalogRow, error)
	// Kiralık ızgarası: en az bir ülke×sürede stoklu servisler.
	// `s.sort_order` GROUP BY'da açıkça yer almalı (bkz. ListServicesWithStock).
	// Aktivasyon ızgarasıyla AYNI popülerlik sırası: kullanıcı iki ekranda farklı
	// sıra görürse listenin rastgele olduğunu düşünür.
	ListRentalServicesWithStock(ctx context.Context) ([]ListRentalServicesWithStockRow, error)
	// Dinamik süzgeç sqlc.narg deseniyle; Go'da string birleştirilmez.
	//
	// Yönetim görünümü kullanıcıyı TANIMLAR (e-posta dâhil): moderasyon kararı
	// kimin yazdığını bilmeden verilemez. Bu sütunlar SİTEDEKİ sorguda YOKTUR.
	// Bekleyenler EN ESKİ ÖNCE: moderasyon bir kuyruktur, en uzun bekleyen ilk
	// sırada olmalı. Karara bağlanmışlar en yeni önce: yönetici son ne yaptığına
	// bakar. Tek bir sıralama ikisini de doğru yapamaz.
	ListReviewsForAdmin(ctx context.Context, arg ListReviewsForAdminParams) ([]ListReviewsForAdminRow, error)
	// Kullanıcının KENDİ yorumları ve durumları. En yeni üstte.
	//
	// Durum süzgeci: `sqlc.narg` NULL ise süzme yok.
	// 🔴 `user_id` koşulu süzgeçten bağımsızdır (değişmez #7).
	ListReviewsForUser(ctx context.Context, arg ListReviewsForUserParams) ([]Review, error)
	// Servis IZGARASI için özet: yalnız en az bir ülkede STOKLU olan servisler,
	// her biri için stoklu ülke sayısı.
	//
	// NEDEN AYRI BİR SORGU: gerçek katalogda 9768 stoklu servis×ülke kombinasyonu
	// var ve hepsini tek yanıtta göndermek 1,09 MB ediyordu. Mobilde 4G'de bu
	// kabul edilemez (docs/frontend-contract.md §8). Izgara yalnız servisleri
	// gösterir; ülkeler servis seçilince ayrıca çekilir (~6 KB).
	// 🔴 `s.sort_order` GROUP BY'a AÇIKÇA eklenmelidir: `services` PK'sı (`s.id`)
	// gruplama anahtarında olmadığı için işlevsel bağımlılık kurtarmaz.
	// POPÜLERLİK ÖNCE. Sıra `services.sort_order` alanından gelir ve
	// web/scripts/servis-siralama.sql ile yönetilir; eşit değerler ada göre
	// alfabetik dizilir. Alfabetik sıralamak, kullanıcının aradığı servisi değil
	// adı "A" ile başlayanı öne çıkarıyordu (ızgaranın ilk ekranı Whatnot/Adobe).
	//
	// İSTEMCİDE YENİDEN SIRALANMAZ: sıralama tek yerde, burada yapılır.
	ListServicesWithStock(ctx context.Context) ([]ListServicesWithStockRow, error)
	// YÖNETİM GÖRÜNÜMÜ: yazarın kullanıcı adı da gelir — kim yanıtladı sorusu
	// destek ekibinin iç sorusudur.
	ListTicketMessagesForAdmin(ctx context.Context, ticketID int64) ([]ListTicketMessagesForAdminRow, error)
	// KULLANICI GÖRÜNÜMÜ: personelin kullanıcı adı SEÇİLMEZ.
	//
	// Personelin kimliği kullanıcıya gösterilmez; yazar etiketi is_staff'tan
	// türetilir ("Destek ekibi"). Sütunu getirip DTO'da atmak, bir gün birinin
	// onu yanıta koymasını bir satır uzaklığa indirirdi.
	// test: internal/transport/http/handler/ticket_integration_test.go#TestStaffUsernameNeverLeaksToUser
	ListTicketMessagesForUser(ctx context.Context, ticketID int64) ([]ListTicketMessagesForUserRow, error)
	// Dinamik süzgeç sqlc.narg deseniyle; Go'da string birleştirilmez.
	//
	// İKİ AYRI SÜZGEÇ vardır ve ikisi de gereklidir:
	//   status      → tam durum eşleşmesi ("Kapatılanları göster")
	//   only_pending→ YÖNETİCİNİN KUYRUĞU: OPEN **ve** USER_REPLIED birlikte
	//
	// "Açık talepler" TEK BİR DURUM DEĞİLDİR. Yalnız OPEN süzmek, kullanıcının
	// yanıt yazdığı (USER_REPLIED) talepleri varsayılan ekrandan gizler — yani
	// yanıt bekleyen müşteri görünmez olur.
	ListTicketsForAdmin(ctx context.Context, arg ListTicketsForAdminParams) ([]ListTicketsForAdminRow, error)
	// `activation-reaper` için: terminal ama sağlayıcıda kapatılmamış siparişler.
	// KK-412: bu sorgunun sonucu uzun vadede BOŞ olmalıdır.
	//
	// ROL AYRIMI: iade ekseni AÇIK olan satırlar ('PENDING','RETRY_SCHEDULED')
	// `provider-refund-retry` işinin sorumluluğundadır ve buraya DÜŞMEZ. Bu filtre
	// olmadan iki iş aynı satıra Cancel() gönderir ve sağlayıcının verdiği
	// Retry-After süresi (FR-414) 60 saniyede bir çiğnenir.
	//
	// Kapatma ekseni (FR-412) YİNE reaper'ındır: iade ekseni DENIED/REFUNDED/
	// NOT_APPLICABLE'a düştüğü an satır buraya geri döner — kapatma denemesinden
	// vazgeçilmez.
	// test: refund_retry_integration_test.go#TestReaperIgnoresScheduledRefundOrders
	ListUnclosedTerminalOrders(ctx context.Context, lim int32) ([]Order, error)
	// deposits_user_idx (user_id, created_at DESC) tam olarak bu sıralamayı kullanır.
	//
	// Durum süzgeci `ListDepositsForAdmin` ile AYNI desendir: `sqlc.narg` NULL ise
	// süzme yok. 🔴 `user_id` koşulu süzgeçten bağımsızdır ve kaldırılamaz —
	// sahiplik sorgunun parçasıdır (değişmez #7).
	ListUserDeposits(ctx context.Context, arg ListUserDepositsParams) ([]Deposit, error)
	//
	// 🔴 `icon_url` CANLI KATALOGDAN gelir, sipariş kaydından DEĞİL.
	//
	// `orders.service_name` bilerek anlık görüntüdür: satış kaydı, katalog sonradan
	// değişse bile ne satıldığını korumalıdır (para kaydı, 10 yıl saklanıyor).
	// Logo ise sunum verisidir; markanın logosu güncellendiğinde eski siparişlerde
	// de yeni logonun görünmesi İSTENİR. Bu yüzden sipariş satırına kopyalanmaz,
	// her okumada katalogdan çekilir.
	//
	// LEFT JOIN gerekçesi: `service_code` satın alma anındaki metin anlık
	// görüntüsüdür; katalog senkronu sağlayıcının kodunu değiştirirse eşleşme
	// kaybolur. INNER JOIN, o kullanıcının geçmiş siparişini listeden sessizce
	// düşürürdü. (Servis satırının SİLİNMESİ mümkün değil — orders → price_quotes
	// → products → services yabancı anahtar zinciri buna izin vermiyor.)
	// test: order_integration_test.go#TestListUserOrdersCarriesServiceIcon
	//
	// `sqlc.embed(o)` kullanılır, sütunlar tek tek sayılmaz: `SELECT o.*` ya da elle
	// sütun listesi, sqlc'ye `db.Order` yerine YENİ bir satır tipi ürettirir ve aynı
	// tipi bekleyen tüm çağrı yerleri kırılır. `embed` `db.Order`'ı olduğu gibi
	// korur, `icon_url`'i yanına ekler — ve şemaya sütun eklendiğinde bu sorgu
	// kendiliğinden güncel kalır.
	//
	// SÜZGEÇLER — `sqlc.narg()` + "NULL ise süzme" deseni (CLAUDE.md sqlc kuralları).
	//
	// ÜÇ SÜZGEÇ VARDIR VE `only_active` AYRI DURMAK ZORUNDADIR:
	//   status       → TEK durum eşleşmesi ("İptal edilenleri göster")
	//   only_active  → "AKTİF" = PENDING **veya** ACTIVE, yani tek durum DEĞİL
	//   q            → serbest metin
	// `ListTicketsForAdmin`'deki `only_pending` ile aynı gerekçe: bir kullanıcı
	// kavramı ("aktif siparişim") birden çok duruma karşılık geliyorsa, onu tek
	// durumlu süzgece sıkıştırmak listeyi sessizce eksiltir. ACTIVE, kiralık
	// siparişin süren dönemidir ve özet ekranında gizlenemez.
	// Go'da string birleştirerek SQL kurulmaz; `ListUsers` ile AYNI desen.
	//
	// 🔴 `user_id` KOŞULU HER İKİ SÜZGEÇTEN ÖNCE GELİR ve kaldırılamaz: sahiplik
	// sorgunun parçasıdır (değişmez #7). Hiçbir `q`/`status` bileşimi başka bir
	// kullanıcının siparişini döndüremez.
	//
	// İNDEKS EKLENMEDİ: `ILIKE '%...%'` bir btree indeksi kullanamaz zaten, ama
	// tarama `user_id` ile ZATEN daraltılmış küçük bir kümede olur (bir kullanıcının
	// kendi siparişleri) — planlayıcı `orders_user_idx` (user_id, created_at DESC) ile satırları
	// getirir, süzgeç o küme üzerinde çalışır. Gerçek bir sorun ölçülürse çare
	// `pg_trgm` GIN indeksidir, gövdede string birleştirmek değil.
	ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]ListUserOrdersRow, error)
	ListUserSessions(ctx context.Context, userID int64) ([]Session, error)
	// tickets_user_idx (user_id, last_reply_at DESC) tam olarak bu sıralamayı kullanır.
	//
	// Durum süzgeci `ListTicketsForAdmin` ile AYNI desen: `sqlc.narg` NULL ise
	// süzme yok. 🔴 `user_id` koşulu süzgeçten bağımsızdır (değişmez #7).
	ListUserTickets(ctx context.Context, arg ListUserTicketsParams) ([]ListUserTicketsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Yönetim kullanıcı listesi.
	//
	// 🔴 password_hash SEÇİLMEZ. Yönetim panelinde bile: bir sızıntıda parola
	// özetleri offline kırma denemelerine açık olur ve hiçbir yönetim işlevi
	// onlara ihtiyaç duymaz.
	// test: internal/transport/http/handler/admin_integration_test.go#TestListUsersNeverReturnsPasswordHash
	ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error)
	ListVisibleCountries(ctx context.Context) ([]Country, error)
	ListVisibleServices(ctx context.Context) ([]Service, error)
	// Bir kapsamdaki ETKİN kuralı KİLİTLER.
	//
	// Kural "güncelleme" yoktur: eski kural pasifleştirilip yenisi eklenir
	// (kısmi tekil indeksler aynı kapsamda iki etkin kurala izin vermez).
	// Kilit olmadan iki yönetici aynı anda kural yazdığında ikisi de eski satırı
	// görür, ikisi de INSERT eder ve biri 23505 ile düşer — hangisinin geçtiği
	// rastgele olur. FOR UPDATE bunu sıraya sokar.
	//
	// IS NOT DISTINCT FROM kullanılır: NULL = NULL karşılaştırması `=` ile
	// daima NULL döner ve GLOBAL kapsam (üç alanı da NULL) hiç eşleşmezdi.
	LockActiveRuleForScope(ctx context.Context, arg LockActiveRuleForScopeParams) (PricingRule, error)
	// ÇAĞIRANIN TRANSACTION'I İÇİNDE çağrılmalıdır. Kilit commit'e kadar tutulur;
	// eşzamanlı onay istekleri burada sıraya girer. Kilitsiz okuyup sonra yazmak,
	// iki yöneticinin (veya bir yöneticinin iki sekmesinin) aynı talebi iki kez
	// onaylamasına ve bakiyenin iki kez artmasına yol açar.
	// test: deposit_integration_test.go#TestApproveIsIdempotentUnderConcurrency
	LockDepositForUpdate(ctx context.Context, publicID uuid.UUID) (Deposit, error)
	// Teklifi KİLİTLER. Aynı teklifle iki eşzamanlı satın alma denemesinde
	// yalnız biri geçmelidir (docs/trd.md KK-402).
	LockQuoteForConsumption(ctx context.Context, arg LockQuoteForConsumptionParams) (PriceQuote, error)
	// Yönetim yolu: ÇAĞIRANIN TRANSACTION'I İÇİNDE. Kilit, aynı yoruma iki
	// yöneticinin aynı anda karar vermesini (biri onay, biri red) engeller.
	// test: internal/service/review/review_integration_test.go#TestConcurrentDecisionsLeaveOneOutcome
	LockReview(ctx context.Context, publicID uuid.UUID) (Review, error)
	// Yönetim yolu: sahiplik kısıtı YOKTUR, izin kontrolü middleware'dedir
	// (tickets:reply).
	LockTicket(ctx context.Context, publicID uuid.UUID) (Ticket, error)
	// ÇAĞIRANIN TRANSACTION'I İÇİNDE çağrılır. Kilit, aynı talebe iki mesajın
	// eşzamanlı yazılıp durumun ikisinden yalnız birine göre hesaplanmasını
	// engeller. Sahiplik yine SORGUDADIR — kilit almak yetki vermez.
	// test: internal/service/ticket/ticket_integration_test.go#TestUserCannotWriteToOthersTicket
	LockTicketForUser(ctx context.Context, arg LockTicketForUserParams) (Ticket, error)
	// Kullanıcı satırını KİLİTLER. Bu satır olmadan çift harcama mümkündür:
	// iki eşzamanlı istek aynı bakiyeyi okuyup ikisi de yeterli sanabilir.
	// Kilit, transaction bitene kadar tutulur.
	LockUserForUpdate(ctx context.Context, id int64) (LockUserForUpdateRow, error)
	MarkEmailVerified(ctx context.Context, id int64) error
	// Yoklama turunun damgası. Sıradaki tur en uzun süredir yoklanmamış satırla
	// başlasın diye, sağlayıcı çağrısından ÖNCE yazılır: sağlayıcı erişilemezse
	// bile tur ilerler ve tek bir arızalı grup kümenin geri kalanını aç bırakmaz.
	MarkOrdersPolled(ctx context.Context, arg MarkOrdersPolledParams) error
	// Kapatma BAŞARILI OLDUKTAN SONRA çağrılır.
	// Başarısızken yazılırsa reaper o siparişi bir daha hiç denemez ve aktivasyon
	// sağlayıcıda açık kalır (FR-412).
	MarkProviderClosed(ctx context.Context, arg MarkProviderClosedParams) error
	// Senkron turunda görülmeyen teklifler "yok" sayılır. Aksi halde sağlayıcının
	// listeden çıkardığı bir kombinasyon sonsuza kadar stokta görünürdü.
	MarkStaleOffersUnavailable(ctx context.Context, arg MarkStaleOffersUnavailableParams) (int64, error)
	// Yönetim özeti. Tek sorguda: N ayrı COUNT sorgusu atmak, tablo büyüdükçe
	// panelin açılışını yavaşlatır.
	//
	// KOVALAR TOPLAMI `total`A EŞİTTİR. Eskiden değildi: 'ACTIVE' ve 'FAILED'
	// hiçbir kovaya girmiyordu, yani panel "toplam 100, dağılım 78" gösterirdi.
	// Bir sayının nereye gittiği görünmüyorsa gösterge okunamaz.
	OrderStatsSummary(ctx context.Context, since time.Time) (OrderStatsSummaryRow, error)
	RecordCloseFailure(ctx context.Context, arg RecordCloseFailureParams) error
	// ═══════════════════════════ SAKLAMA POLİTİKASI ═══════════════════════════
	//
	// Gizlilik metninde ilan edilen süreler BURADA uygulanır. Metin ile bu dosya
	// ayrı düştüğü an kullanıcıya verilmiş bir söz karşılıksız kalır: sayfa
	// "90 gün sonra sileriz" der, veri durur. Beş sorgu bu yüzden tek dosyada
	// toplandı — süreyi değiştiren kişi hepsini bir arada görsün.
	//
	// SÜRELER (9 Eylül 2026 kararı):
	//   SMS içeriği (order_messages)         90 gün          → gövde boşaltılır, satır durur
	//   oturum (sessions)                    süresi dolunca  → satır silinir
	//   tek kullanımlık token (auth_tokens)  süresi dolunca  → satır silinir
	//   tüketilmemiş teklif (price_quotes)   süresi dolunca  → satır silinir
	//   denetim kaydı (audit_logs)           2 yıl           → satır silinir
	//
	// BU DOSYADA OLMAYANLAR: orders, deposits, ledger_entries. Mali kayıt 10 yıl
	// durur; `ledger_entries` ayrıca değişmezdir (migration 00004 tetikleyicisi).
	// Temizlik işi o tabloların hiçbirine uzanmaz.
	// test: retention_integration_test.go#TestRetentionLeavesLedgerAndOrdersUntouched
	//
	// HER SORGU PARTİLİDİR (LIMIT). Tek ifadeyle milyonlarca satır silmek tabloyu
	// kilitler, WAL'i şişirir ve temizliği bir kesintiye çevirir. Çağıran
	// (internal/worker/jobs.go) parti tükenene kadar döner.
	//
	// ZAMAN DIŞARIDAN GELİR (`older_than`), `now()` değil: sınır davranışı ancak
	// sahte saatle sınanabilir ve saat kaynağı tek yerde kalır (ClockPort).
	// SMS içeriğini boşaltır, SATIRI BIRAKIR (90 gün).
	//
	// NEDEN SATIR DURUYOR: "kod geldi mi gelmedi mi" tartışmasının tek kanıtı bu
	// satırdır (handler/order.go visibleMessages: iade edilmiş siparişin mesajı
	// gösterilmez ama veritabanında durur). Sipariş kaydı 10 yıl saklanırken mesaj
	// satırını yok etmek o kaydı eksik bırakırdı: iade edilmiş bir siparişte
	// "aslında kod gelmişti" bilgisi de giderdi. KVKK'nın veri minimizasyonu
	// İÇERİĞİ ister, OLGUYU değil — metin gider, `received_at` kalır.
	//
	// provider_otp_id DE DEĞİŞİR: sağlayıcı kendi mesaj kimliğini vermediğinde bu
	// alan SHA-256(activationId + receivedAt + text) olur, yani METİNDEN TÜRER.
	// Gövdeyi boşaltıp metinden türeyen özeti bırakmak "içerik silindi" sözünü
	// yarım bırakırdı. Yerine satırın kendi kimliğinden türeyen ve çakışmayan bir
	// işaret yazılır. Dedup değerinin 90 gün sonra karşılığı yoktur: kapatılmış
	// aktivasyon için sağlayıcı 409 döner, geçmiş mesaj yeniden gelmez.
	//
	// İŞARET AYNI ZAMANDA SÜZGEÇTİR: ikinci koşu boşaltılmış satıra dokunmaz,
	// `!~ '^redacted:'` onu dışarıda tutar.
	// test: retention_integration_test.go#TestRetentionRedactionIsIdempotent
	//
	// ÖLÇÜT `created_at`, `received_at` DEĞİL: söz verdiğimiz şey BİZİM saklama
	// süremizdir. `received_at` sağlayıcının bildirdiği andır; geçmişe kaçık bir
	// değer satırı vaktinden önce, geleceğe kaçık bir değer hiç boşaltmazdı.
	RedactOldOrderMessages(ctx context.Context, arg RedactOldOrderMessagesParams) (int64, error)
	// Bakiyeye HİÇ dokunulmaz (FR-503); burada yalnız durum ve gerekçe yazılır.
	RejectDeposit(ctx context.Context, arg RejectDepositParams) (Deposit, error)
	// Sahiplenmeyi BIRAKIR: kapatılacak bir şey olmadığı anlaşıldığında çağrılır
	// (örn. sipariş hâlâ beklemede). Kirayı boşuna tutmak, siparişin terminal
	// olduğu anda yapılacak kapatmayı kira süresi kadar geciktirirdi.
	//
	// BAŞARISIZLIKTA ÇAĞRILMAZ: kira, başarısız bir denemenin hemen ardından
	// ikinci bir denemeyi engelleyerek sağlayıcının verdiği Retry-After süresine
	// saygı gösterir.
	ReleaseOrderClose(ctx context.Context, id int64) error
	ReplaceUserRoles(ctx context.Context, arg ReplaceUserRolesParams) error
	// Sağlayıcının İngilizce ülke adını ISO2 + Türkçe ad + telefon koduna çevirir.
	ResolveCountryRef(ctx context.Context, nameKey string) (ResolveCountryRefRow, error)
	// Sağlayıcının boyut kodunu YEREL kimliğe çevirir.
	//
	// Teklif senkronu eskiden ülkeyi `countries.iso2` üzerinden arıyordu. Bu, ancak
	// sağlayıcının kodu tesadüfen ISO2 ise çalışır; HeroSMS "62" gönderir ve arama
	// boş döner. Sağlayıcı kodu ile yerel kimlik arasındaki köprü BURASIDIR.
	ResolveDimensionLocal(ctx context.Context, arg ResolveDimensionLocalParams) (int64, error)
	RevokeAllUserSessions(ctx context.Context, userID int64) error
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	RevokeSession(ctx context.Context, id string) error
	// Aktif/pasif AYRI bir sorgu: tek bir düğmeye basmak, o sırada düzenlenmekte
	// olan diğer alanları yazmamalı.
	SetDepositMethodActive(ctx context.Context, arg SetDepositMethodActiveParams) (DepositMethod, error)
	// Dekont YALNIZ sahibi tarafından ve YALNIZ inceleme öncesinde eklenebilir:
	// sonuçlandırılmış bir talebin kanıtını değiştirmek denetimi anlamsız kılar.
	SetDepositReceipt(ctx context.Context, arg SetDepositReceiptParams) (Deposit, error)
	// Durum yazımı — YALNIZ domain/order.Transition doğruladıktan sonra çağrılır.
	// Veritabanındaki tetikleyici ikinci savunma hattıdır.
	SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (Order, error)
	SetProviderActive(ctx context.Context, arg SetProviderActiveParams) error
	SetProviderRefundStatus(ctx context.Context, arg SetProviderRefundStatusParams) error
	// Servis logosunu ayarlar. Yol `web/public/` köküne göredir: /servis-logolari/wa.svg
	SetServiceIcon(ctx context.Context, arg SetServiceIconParams) (SetServiceIconRow, error)
	// 🔴 closed_at, status ile AYNI ifadede yazılır: ticket_closed_has_time
	// CHECK'i (00012_tickets.sql) iki adımlı yazımda 23514 ile düşer.
	// Talep yeniden açılırken closed_at NULL'a döner.
	SetTicketStatus(ctx context.Context, arg SetTicketStatusParams) (Ticket, error)
	SetUserBalance(ctx context.Context, arg SetUserBalanceParams) error
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) error
	// Yönetim: kullanıcı durumunu değiştirir.
	// public_id ile çalışır — sayısal id dışarı verilmez (değişmez #10).
	SetUserStatusByPublicID(ctx context.Context, arg SetUserStatusByPublicIDParams) (SetUserStatusByPublicIDRow, error)
	// İade eksenini KAPATIR: sağlayıcıya bir daha istek gönderilmez.
	//
	// `SetProviderRefundStatus`ten iki farkı var ve ikisi de kasıtlı:
	//   1. `refund_attempts` ARTIRILMAZ — kapatmak bir deneme değildir.
	//   2. Koşulludur: yalnız iade ekseni AÇIKKEN yazar, böylece iki işçi aynı
	//      anda kapatmaya çalışsa da sonuç tektir ve REFUNDED/DENIED bir satırın
	//      üstüne yazılmaz.
	// test: ../internal/service/order/refund_retry_integration_test.go#TestFinishedOrderLeavesRefundQueue
	SettleProviderRefund(ctx context.Context, arg SettleProviderRefundParams) error
	// Kâr raporu ve muhasebe özeti girdisi.
	SumLedgerByType(ctx context.Context, arg SumLedgerByTypeParams) ([]SumLedgerByTypeRow, error)
	TouchSession(ctx context.Context, id string) error
	// Mesaj eklendikten SONRA durumu ve son yanıt zamanını yazar.
	//
	// Yeni durum SERVİSTE domain/ticket ile hesaplanır (değişmez #13): bu sorgu
	// karar vermez, kararı yazar.
	TouchTicketAfterMessage(ctx context.Context, arg TouchTicketAfterMessageParams) (Ticket, error)
	UpdateDepositMethod(ctx context.Context, arg UpdateDepositMethodParams) (DepositMethod, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	// API anahtarı güncelleme — AYRI bir sorgu.
	//
	// Diğer ayarlarla aynı UPDATE'e konsaydı, ayar değiştiren her istek anahtarı
	// da yazardı ve boş bir alan anahtarı SİLERDİ. Ayrı tutmak, "kaydet"e basmanın
	// anahtarı yanlışlıkla silmesini imkânsız kılar.
	// test: internal/transport/http/handler/admin_integration_test.go#TestSavingProviderSettingsDoesNotEraseAPIKey
	//
	// 🔴 `:exec` DEĞİL `:one`: etkilenen satır sayısı GÖRÜLMELİDİR. `:exec` yalnız
	// hata döner, "hiçbir satır güncellenmedi" hata DEĞİLDİR — var olmayan bir
	// sağlayıcı kimliğine anahtar yazmak sessizce başarılı görünüyordu ve yönetici
	// maskeli önizlemeyi görüp anahtarı kaydettiğini sanıyordu. Sağlayıcı
	// çalışmadığında sebep aranacak en son yer orasıdır.
	// test: internal/transport/http/handler/admin_provider_integration_test.go#TestSetAPIKeyOnMissingProviderIs404
	UpdateProviderAPIKey(ctx context.Context, arg UpdateProviderAPIKeyParams) (int64, error)
	UpdateProviderBalance(ctx context.Context, arg UpdateProviderBalanceParams) error
	// Sağlayıcı ayarları. API ANAHTARI BURADAN GÜNCELLENMEZ — ayrı bir yol var.
	UpdateProviderSettings(ctx context.Context, arg UpdateProviderSettingsParams) (UpdateProviderSettingsRow, error)
	UpsertCountry(ctx context.Context, arg UpsertCountryParams) (Country, error)
	// ─────────────────────── Boyut eşleştirme ───────────────────────
	UpsertDimensionMap(ctx context.Context, arg UpsertDimensionMapParams) error
	// ─────────────────────── Fiyat/stok önbelleği ───────────────────────
	// synced_at UYGULAMADAN gelir, now() DEĞİL.
	//
	// Bayat teklif tespiti bu alanı bir eşikle karşılaştırır; yazım veritabanı
	// saatini, karşılaştırma uygulama saatini kullanırsa aradaki kayma tüm
	// teklifleri sessizce "yok" işaretler. İki taraf AYNI saat kaynağını kullanmalı.
	UpsertOffer(ctx context.Context, arg UpsertOfferParams) error
	UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (Permission, error)
	// ─────────────────────── Ürün ───────────────────────
	UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error)
	// Kiralık ürün. Aktivasyondan TEK FARKI süre boyutunun dolu olması —
	// ama o fark benzersizlik anahtarının parçası olduğu için aynı servis×ülke
	// için sekiz ayrı ürün (sekiz süre) yan yana durabilir.
	UpsertRentalProduct(ctx context.Context, arg UpsertRentalProductParams) (Product, error)
	UpsertRole(ctx context.Context, arg UpsertRoleParams) (Role, error)
	// ─────────────────────── Boyutlar ───────────────────────
	UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error)
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
