// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// İKİNCİ SAVUNMA HATTI: `AND status = 'PENDING'` koşulu yarışta ikinci çağrıya
	// SIFIR satır döndürür (pgx.ErrNoRows) — bu "zaten sonuçlandırılmış" demektir.
	//
	// 🔴 reviewed_at, status ile AYNI ifadede yazılır: deposit_reviewed_has_time
	// CHECK'i (00008_orders.sql) iki adımlı yazımda 23514 ile düşer.
	ApproveDeposit(ctx context.Context, arg ApproveDepositParams) (Deposit, error)
	// Sitedeki özet: kaç onaylı yorum ve ortalama puan.
	//
	// 🔴 ORTALAMA ONDA BİRLİK TAM SAYI OLARAK döner (4.7 → 47), kayan nokta
	// olarak değil. Para değil ama aynı gerekçe geçerli: `float64` üzerinden
	// taşınan bir ortalama JSON'da 4.699999999999999 olur ve arayüzde iki farklı
	// yerde iki farklı yuvarlanır. Bölme TEK YERDE, gösterimde yapılır.
	// Yorum yoksa total 0 gelir ve ARAYÜZ BÖLÜMÜ HİÇ RENDER ETMEZ.
	ApprovedReviewStats(ctx context.Context) (ApprovedReviewStatsRow, error)
	AssignRole(ctx context.Context, arg AssignRoleParams) error
	// SAHİPLENME: sağlayıcıda kapatma denemesini TEK bir işçiye verir.
	//
	// Kapatma bir HTTP çağrısı içerir; dış çağrı transaction içinde yapılmaz
	// (değişmez #5), dolayısıyla satır kilidi çağrı boyunca tutulamaz —
	// `GetOrderForUpdate` bir transaction dışında çağrıldığında kilit deyim
	// biter bitmez bırakılır ve hiçbir şeyi korumaz. Bunun yerine satır koşullu
	// bir UPDATE ile sahiplenilir: yarışı kaybeden işçi SIFIR satır alır
	// (ConsumeQuote ile aynı desen) ve sağlayıcıya hiç gitmez.
	//
	// Kira süresi dolduğunda satır kendiliğinden yeniden uygun hâle gelir: çağrı
	// sırasında ölen bir işçi satırı sonsuza kadar bloke edemez.
	//
	// `provider_closed_at IS NULL` koşulu da buradadır: zaten kapatılmış siparişe
	// ikinci kez Cancel/Finish gönderilmez.
	// test: refund_retry_integration_test.go#TestConcurrentCloseSendsSingleProviderCall
	ClaimOrderClose(ctx context.Context, arg ClaimOrderCloseParams) (Order, error)
	// Tek kullanımlıktır: UPDATE ... RETURNING ile atomik olarak tüketilir.
	// Ayrı SELECT + UPDATE yapılsaydı iki eşzamanlı istek aynı token'ı kullanabilirdi.
	ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (AuthToken, error)
	// Tek kullanımlık işaretleme.
	// WHERE consumed_at IS NULL sayesinde yarış durumunda ikinci çağrı
	// SIFIR satır döner — kilitle birlikte çift savunma.
	ConsumeQuote(ctx context.Context, arg ConsumeQuoteParams) (PriceQuote, error)
	// Bir kapsamdaki etkin kural sayısı.
	//
	// Son GLOBAL kuralın pasifleştirilmesini engellemek için kullanılır: GLOBAL
	// kural kalmazsa ListApplicableRules boş döner, SelectRule ErrNoRule verir ve
	// SİSTEM SATIŞ YAPAMAZ hâle gelir.
	CountActiveRulesByScope(ctx context.Context, scope PricingScope) (int64, error)
	CountAllOrders(ctx context.Context, arg CountAllOrdersParams) (int64, error)
	CountAuditLogsForAdmin(ctx context.Context, arg CountAuditLogsForAdminParams) (int64, error)
	CountDepositsForAdmin(ctx context.Context, status *DepositStatus) (int64, error)
	CountDimensionMaps(ctx context.Context, arg CountDimensionMapsParams) (int64, error)
	CountLedgerEntries(ctx context.Context, arg CountLedgerEntriesParams) (int64, error)
	CountOrderMessages(ctx context.Context, orderID int64) (int64, error)
	// Yönetim menüsündeki rozet için: kaç yorum karar bekliyor.
	CountPendingReviews(ctx context.Context) (int64, error)
	// Süzgeç koşulu ListReviewsForAdmin ile BİREBİR AYNI olmalıdır; ayrışırsa
	// sayfalama "23 kayıt" der ama 12 satır gösterir.
	CountReviewsForAdmin(ctx context.Context, status *ReviewStatus) (int64, error)
	CountReviewsForUser(ctx context.Context, userID int64) (int64, error)
	// Süzgeç koşulu ListTicketsForAdmin ile BİREBİR AYNI olmalıdır; ayrışırsa
	// sayfalama "23 kayıt" der ama 12 satır gösterir.
	CountTicketsForAdmin(ctx context.Context, arg CountTicketsForAdminParams) (int64, error)
	CountUserDeposits(ctx context.Context, userID int64) (int64, error)
	CountUserOrders(ctx context.Context, userID int64) (int64, error)
	CountUserTickets(ctx context.Context, userID int64) (int64, error)
	CountUsersForAdmin(ctx context.Context, arg CountUsersForAdminParams) (int64, error)
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	// Bakiye yükleme talepleri (FR-500 … FR-503).
	//
	// Ödeme YÖNTEMİ sorguları burada değil, queries/orders.sql içindedir
	// (deposit_methods CRUD'u zaten yazılmıştı).
	// 🔴 tx_hash HAVALEDE NULL BIRAKILIR, boş string yazılmaz: deposits_tx_hash_uniq
	// kısmi indeksi (WHERE tx_hash IS NOT NULL) NULL'ları hariç tutar. '' yazılırsa
	// kullanıcının İKİNCİ havale talebi 23505 alır ve bir daha havale bildiremez.
	// test: deposit_integration_test.go#TestBankTransferDepositLeavesTxHashNull
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	CreateDepositMethod(ctx context.Context, arg CreateDepositMethodParams) (DepositMethod, error)
	// Sipariş kaydı — T2 içinde, sağlayıcı çağrısı BAŞARILI olduktan sonra.
	//
	// Katalog alanları ANLIK GÖRÜNTÜ olarak yazılır: servis/ülke satırları katalog
	// senkronunda silinebilir, sipariş geçmişi buna dayanamaz.
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePricingRule(ctx context.Context, arg CreatePricingRuleParams) (PricingRule, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	// ─────────────────────── Teklif ───────────────────────
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (PriceQuote, error)
	// Müşteri yorumları.
	//
	// ÜÇ AYRI SORGU AİLESİ vardır ve karıştırılmaz:
	//   *ForUser   → sahiplik SORGUNUN PARÇASIDIR (değişmez #7)
	//   *ForAdmin  → sahiplik kısıtı yoktur; koruma izin ara katmanındadır
	//   Approved*  → OTURUMSUZ, sitede gösterilir; KİŞİSEL VERİ SEÇMEZ
	// Durum İSTEMCİDEN ALINMAZ: yeni yorum her zaman PENDING'dir (varsayılan) ve
	// oradan yalnız durum makinesi çıkarır (değişmez #13).
	//
	// 🔴 "Bu kullanıcının bekleyen yorumu var mı?" diye ÖNCE SELECT YAPILMAZ.
	// Kısıt kısmi benzersiz indekstedir (reviews_one_pending_per_user_idx) ve bu
	// INSERT 23505 ile düşer. Uygulama katmanındaki kontrol iki eşzamanlı isteğin
	// ikisi tarafından da geçilirdi.
	// test: internal/service/review/review_integration_test.go#TestConcurrentSubmitsLeaveOnePending
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Destek talepleri (FR-600).
	//
	// İKİ AYRI SORGU AİLESİ vardır ve karıştırılmaz:
	//   *ForUser  → sahiplik SORGUNUN PARÇASIDIR (değişmez #7)
	//   *ForAdmin → sahiplik kısıtı yoktur; koruma izin ara katmanındadır
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	// 🔴 is_staff AÇIKÇA VERİLİR. Sütunun varsayılanı yoktur (00012_tickets.sql):
	// parametreyi unutan bir çağrı derlenmez ya da veritabanında düşer, sessizce
	// "kullanıcı yazdı" diye kaydedilmez (KK-600).
	CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (TicketMessage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivatePricingRule(ctx context.Context, id int64) error
	// Kararı YAZAR, VERMEZ. Yeni durum serviste domain/review ile hesaplanır
	// (değişmez #13); bu sorgu yalnız sonucu kaydeder.
	//
	// 🔴 status, rejection_reason ve reviewed_at AYNI İFADEDE yazılır:
	// review_decided_has_time ve review_reason_only_when_rejected CHECK'leri
	// iki adımlı bir yazımda 23514 ile düşer.
	DecideReview(ctx context.Context, arg DecideReviewParams) (Review, error)
	// Yöntem SİLİNİR ama geçmiş yükleme kayıtları KALIR: deposits.method_id
	// ON DELETE SET NULL ve method_name anlık görüntü olarak saklanıyor.
	DeleteDepositMethod(ctx context.Context, publicID uuid.UUID) error
	DeleteExpiredAuthTokens(ctx context.Context) (int64, error)
	// Tüketilmemiş ve süresi geçmiş teklifler temizlenir.
	// Tüketilmiş olanlar SAKLANIR: sipariş kaydının fiyat kanıtıdır.
	DeleteExpiredQuotes(ctx context.Context, expiresAt time.Time) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	EmailExists(ctx context.Context, email string) (bool, error)
	FindLedgerEntriesByReference(ctx context.Context, arg FindLedgerEntriesByReferenceParams) ([]LedgerEntry, error)
	// Cüzdan sorguları.
	//
	// BU DOSYADAKİ SIRALAMA KRİTİKTİR ve wallet servisinde birebir uygulanır:
	//   1) idempotency kontrolü  →  2) satır KİLİDİ  →  3) yeterlilik  →  4) yazım
	// Kilitsiz bir okuma-değiştir-yazma döngüsü eşzamanlı isteklerde bakiyeyi bozar
	// (docs/memory.md §3.6 — eski prototipin hatası).
	// İdempotency: bu anahtarla daha önce işlem yapıldıysa sonucu döner.
	FindLedgerEntryByKey(ctx context.Context, idempotencyKey string) (LedgerEntry, error)
	GetCountryByISO(ctx context.Context, iso2 string) (Country, error)
	// Yönetim yolu: sahiplik kısıtı YOKTUR, izin kontrolü middleware'dedir
	// (deposits:read / deposits:approve).
	GetDeposit(ctx context.Context, publicID uuid.UUID) (Deposit, error)
	// Tekrarlanan talep isteğinde MEVCUT talebi döner.
	//
	// Kullanıcı kapsamı sorgunun parçasıdır: iki kullanıcının aynı anahtarı
	// üretmesi çakışma değil, ayrı işlemdir.
	// test: deposit_integration_test.go#TestDepositCreateIsIdempotent
	GetDepositByIdempotencyKey(ctx context.Context, arg GetDepositByIdempotencyKeyParams) (Deposit, error)
	// SAHİPLİK SORGUNUN PARÇASIDIR (CLAUDE.md değişmez #7). Başkasının talebi ile
	// var olmayan talep AYNI sonucu (sıfır satır) verir.
	GetDepositForUser(ctx context.Context, arg GetDepositForUserParams) (Deposit, error)
	GetDepositMethod(ctx context.Context, publicID uuid.UUID) (DepositMethod, error)
	GetLatestFXRate(ctx context.Context, arg GetLatestFXRateParams) (FxRate, error)
	// Webhook korelasyonu: sağlayıcı YALNIZ aktivasyon kimliğini taşır.
	GetOrderByRemote(ctx context.Context, arg GetOrderByRemoteParams) (Order, error)
	// Durum değiştirmeden ÖNCE kilitle. Kilitsiz okuma + yazma, iki işçinin aynı
	// siparişi aynı anda sonlandırmasına ve çift iadeye yol açar.
	GetOrderForUpdate(ctx context.Context, id int64) (Order, error)
	// SAHİPLİK SORGUNUN PARÇASIDIR (CLAUDE.md değişmez #7).
	// Ayrı bir `if order.UserID != userID` kontrolü yazılmaz: unutulabilir.
	GetOrderForUser(ctx context.Context, arg GetOrderForUserParams) (Order, error)
	GetPricingRule(ctx context.Context, id int64) (PricingRule, error)
	// Bir kuralın kapsamını İNSAN OKUR kodlarla verir.
	//
	// Denetim kaydının entity_id'si için gerekir: oraya sayısal kimlik yazmak
	// (Değişmez #10) kaydı hem okunmaz hem de kimlik yeniden kullanıldığında
	// yanıltıcı yapar. "SERVICE_COUNTRY:whatsapp:TR" bir yıl sonra da aynı şeyi
	// anlatır.
	GetPricingRuleLabels(ctx context.Context, id int64) (GetPricingRuleLabelsRow, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetProductForActivation(ctx context.Context, arg GetProductForActivationParams) (Product, error)
	GetProductForRental(ctx context.Context, arg GetProductForRentalParams) (Product, error)
	GetProvider(ctx context.Context, id int64) (Provider, error)
	GetProviderByName(ctx context.Context, name string) (Provider, error)
	// Bir ürünün, BELİRLİ BİR SAĞLAYICIDAKİ karşılıklarını verir.
	//
	// Sağlayıcıya istek atarken BİZİM kodlarımız (services.code, countries.iso2)
	// KULLANILAMAZ. HeroSMS ülkeyi "62" bilir, biz "TR" biliriz. Çeviri burada
	// yapılır; yapılmazsa sağlayıcı "böyle bir ülke yok" der ve teklif düşer.
	// test: internal/service/pricing/remote_codes_integration_test.go#TestProviderReceivesItsOwnCodes
	GetProviderRemoteCodes(ctx context.Context, arg GetProviderRemoteCodesParams) (GetProviderRemoteCodesRow, error)
	GetQuoteByPublicID(ctx context.Context, publicID uuid.UUID) (PriceQuote, error)
	// Sipariş anlık görüntüsü için servis/ülke adları.
	//
	// Sipariş satırına KOPYALANIR: katalog satırları senkronda silinebilir ve
	// sipariş geçmişi bir yıl sonra da okunabilir olmalıdır.
	GetQuoteContext(ctx context.Context, quoteID int64) (GetQuoteContextRow, error)
	GetRemoteCode(ctx context.Context, arg GetRemoteCodeParams) (string, error)
	// SAHİPLİK SORGUNUN PARÇASIDIR (değişmez #7). Başkasının yorumu ile var
	// olmayan yorum AYNI sonucu (sıfır satır) verir; servis ikisini de
	// ErrNotFound'a çevirir.
	// test: internal/transport/http/handler/review_integration_test.go#TestUserCannotSeeOthersReview
	GetReviewForUser(ctx context.Context, arg GetReviewForUserParams) (Review, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetServiceByCode(ctx context.Context, code string) (Service, error)
	GetSession(ctx context.Context, id string) (Session, error)
	// Sayısal id dışarı verilmez: kullanıcı users.public_id ile gösterilir.
	GetTicketForAdmin(ctx context.Context, publicID uuid.UUID) (GetTicketForAdminRow, error)
	// SAHİPLİK SORGUNUN PARÇASIDIR (CLAUDE.md değişmez #7). Başkasının talebi ile
	// var olmayan talep AYNI sonucu (sıfır satır) verir; servis ikisini de
	// ErrNotFound'a çevirir.
	GetTicketForUser(ctx context.Context, arg GetTicketForUserParams) (Ticket, error)
	GetUserBalance(ctx context.Context, id int64) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByPublicID(ctx context.Context, publicID uuid.UUID) (User, error)
	GetUserPermissions(ctx context.Context, userID int64) ([]string, error)
	GetUserRoles(ctx context.Context, userID int64) ([]Role, error)
	GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// ─────────────────────── Kur ───────────────────────
	InsertFXRate(ctx context.Context, arg InsertFXRateParams) (FxRate, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	// ─────────────────────────── Mesajlar ───────────────────────────
	// DEDUP: aynı mesaj webhook, yoklama ve yeniden gönderimlerle en az sekiz kez
	// gelebilir. UNIQUE kısıt son savunma hattıdır; ON CONFLICT ile sessizce
	// yutulur ve `inserted` alanı gerçekten yeni mi söyler.
	InsertOrderMessage(ctx context.Context, arg InsertOrderMessageParams) (OrderMessage, error)
	InvalidateUserTokens(ctx context.Context, arg InvalidateUserTokensParams) error
	// Kullanıcı: yalnız aktif yöntemler.
	ListActiveDepositMethods(ctx context.Context) ([]DepositMethod, error)
	// ─────────────────────── Sağlayıcı ───────────────────────
	ListActiveProviders(ctx context.Context) ([]Provider, error)
	// ─────────────────────────── Yönetim ───────────────────────────
	// Yönetim paneli — `orders:read_all` izni gerektirir.
	ListAllOrders(ctx context.Context, arg ListAllOrdersParams) ([]ListAllOrdersRow, error)
	// ─────────────────────── Fiyat kuralları ───────────────────────
	// Bir ürün için uygulanabilir TÜM kuralları döner.
	// En spesifik olanı seçmek domain/pricing.SelectRule'ün işidir; öncelik
	// mantığı SQL'e dağıtılmaz, tek yerde kalır (docs/trd.md FR-303).
	ListApplicableRules(ctx context.Context, arg ListApplicableRulesParams) ([]PricingRule, error)
	// 🔴 SİTEDE GÖSTERİLEN LİSTE — OTURUMSUZ ERİŞİLİR.
	//
	// E-POSTA, sayısal id ve user_id BU SORGUDA SEÇİLMEZ. "Yanıtta gizleriz"
	// yeterli değildir: alan seçilirse bir gün birinin onu DTO'ya koyması bir
	// satır uzaklıktadır ve sızıntı sessiz olur. Seçilmeyen sütun sızamaz.
	// test: internal/transport/http/handler/review_integration_test.go#TestPublicReviewsNeverExposeEmail
	//
	// DISTINCT ON (user_id): bir kullanıcının zaman içinde birden fazla onaylı
	// yorumu olabilir (fikri değişip yenisini yazar). Sitede YALNIZ EN SONU
	// gösterilir; aksi hâlde aynı kişi listede iki kez çıkar ve yorum sayısı
	// gerçekte olduğundan kalabalık görünür.
	ListApprovedReviews(ctx context.Context, lim int32) ([]ListApprovedReviewsRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	// ─────────────────────── Denetim kaydı okuma (FR-705) ───────────────────────
	// Aktör / varlık / eylem / tarih süzgeçli, sayfalı denetim kaydı.
	//
	// AKTÖR public_id İLE SÜZÜLÜR, sayısal id ile değil (Değişmez #10): dışarıya
	// verilen kimlik neyse süzgeç de onu almalı, yoksa panel önce kullanıcıyı
	// sayısal kimliğe çevirmek zorunda kalır ve o kimlik yanıtta da görünür.
	//
	// E-POSTA SEÇİLMEZ. Aktörü tanımak için public_id + kullanıcı adı yeter;
	// e-posta denetim listesinde toplu olarak dışarı akan kişisel veridir.
	// id DESC ikinci ölçüt: aynı milisaniyede yazılan iki kayıt sayfalar arasında
	// yer değiştirirse aynı satır iki sayfada birden görünür ya da hiç görünmez.
	ListAuditLogsForAdmin(ctx context.Context, arg ListAuditLogsForAdminParams) ([]ListAuditLogsForAdminRow, error)
	// Kullanıcıya gösterilecek katalog: en az bir sağlayıcıda stoklu ürünler.
	// TÜRKİYE HER ZAMAN ÖNCE.
	//
	// Kullanıcıların çoğu Türkiye'den ve en çok aradıkları ülke bu. Alfabetik
	// sırada "Türkiye" 190 ülkenin sonlarında kalıyor ve kullanıcı her seferinde
	// listeyi sonuna kadar kaydırıyor. Sıralama SUNUCUDA yapılır: istemcide
	// yapılsaydı her istemci kendi kuralını uygular, mobil ve masaüstü farklı
	// sıralanırdı.
	ListAvailableProductsForCatalog(ctx context.Context, arg ListAvailableProductsForCatalogParams) ([]ListAvailableProductsForCatalogRow, error)
	// ─────────────────────── Ödeme yöntemleri ───────────────────────
	// Yönetim: tüm yöntemler (pasifler dahil).
	ListDepositMethods(ctx context.Context) ([]DepositMethod, error)
	// Sayısal id dışarı verilmez: kullanıcı users.public_id ile gösterilir.
	ListDepositsForAdmin(ctx context.Context, arg ListDepositsForAdminParams) ([]ListDepositsForAdminRow, error)
	ListDimensionMaps(ctx context.Context, arg ListDimensionMapsParams) ([]ProviderDimensionMap, error)
	// `order-expirer` için: süresi dolmuş ama hâlâ beklemede olan siparişler.
	ListExpiredPendingOrders(ctx context.Context, arg ListExpiredPendingOrdersParams) ([]Order, error)
	// Kullanıcının hareket dökümü. SAHİPLİK sorgunun parçasıdır: user_id ayrı bir
	// if kontrolü değil, WHERE koşuludur (docs/design.md §10).
	ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]LedgerEntry, error)
	// Bir ürün için sağlayıcı teklifleri; en ucuz önce.
	ListOffersForProduct(ctx context.Context, productID int64) ([]ListOffersForProductRow, error)
	// YALNIZ YÖNETİM ÖNİZLEMESİ İÇİN: stok koşulu yoktur.
	//
	// `ListOffersForProduct` stoksuz teklifleri eler — satış yolunda doğru olan
	// budur. Ama yönetici marjı değiştirirken stoğu tükenmiş bir ürünün fiyatını
	// da görebilmeli: maliyet biliniyor, satılamıyor olması fiyatı bilinmez
	// yapmaz. Bu sorgu SATIŞ YOLUNDA KULLANILMAZ.
	// test: internal/service/pricing/rules_integration_test.go#TestPreviewWorksWhenOutOfStock
	ListOffersForProductAnyStock(ctx context.Context, productID int64) ([]ListOffersForProductAnyStockRow, error)
	ListOrderMessages(ctx context.Context, orderID int64) ([]OrderMessage, error)
	// `orphan-hold-reaper` için: PARASI ÇEKİLMİŞ ama siparişi olmayan teklifler.
	//
	// T1 (teklif tüket + bakiye düş) ile T2 (sipariş yaz) arasında süreç ölürse
	// kullanıcının parası gitmiş ama elinde numara yoktur. Bu sorgu o durumu bulur.
	//
	// `consumed_at` eşiği, henüz T2'ye ulaşmamış NORMAL akışları yakalamamak için:
	// satın alma birkaç saniye sürer, hemen "yetim" ilan etmek çalışan bir siparişi
	// iade eder.
	//
	// 🔴 İADE EDİLMİŞ OLANLAR DIŞLANIR — yoksa bu sorgu KALICI OLARAK TIKANIR.
	//
	// Sağlayıcı hatasıyla düşen HER satın alma (stok yok, 5xx, geçmiş expiredAt)
	// tam olarak bu profilde bir satır bırakır: teklif tüketilmiş, iade `refundHold`
	// tarafından ZATEN yazılmış, sipariş satırı hiç oluşmamış. Bu satırları dışlayan
	// bir kolon yoktu; her başarısız satın alma sorguya kalıcı bir satır ekliyordu.
	// 100 böyle satır biriktiğinde (tek sağlayıcı kesintisinde dakikalar sürer)
	// `LIMIT` tümüyle ölü satırlarla dolar ve GERÇEKTEN iade edilmemiş yeni yetimler
	// hiç görülmez. Yani güvenlik ağı sessizce yırtılır.
	//
	// Ayrı bir kolon yerine DEFTERE bakılır: iade anahtarı zaten deterministik
	// (`order:{quote_public_id}:refund`, service/order/service.go:368) ve defter
	// değişmezdir — ikinci bir doğruluk kaynağı yaratmaktansa var olanı sorgularız.
	// test: order_integration_test.go#TestOrphanHoldQuerySkipsAlreadyRefunded
	ListOrphanHolds(ctx context.Context, arg ListOrphanHoldsParams) ([]PriceQuote, error)
	// ─────────────────────────── İşçi sorguları ───────────────────────────
	// `order-poller` için: kod bekleyen, süresi dolmamış siparişler.
	ListPendingOrdersForPoll(ctx context.Context, arg ListPendingOrdersForPollParams) ([]Order, error)
	ListPricingRules(ctx context.Context) ([]PricingRule, error)
	// ─────────────────────── Fiyat kuralı yönetimi (FR-703) ───────────────────────
	// Yönetim listesi: etkin kurallar + kapsamın İNSAN OKUR karşılığı.
	//
	// `ListPricingRules` yalnız ham satırı döner; panelde "service_id 42" değil
	// "whatsapp × TR" yazmalı. Ad çözümlemesini Go tarafında N+1 sorguyla yapmak
	// yerine tek JOIN'de çözülür.
	ListPricingRulesForAdmin(ctx context.Context) ([]ListPricingRulesForAdminRow, error)
	// Yönetim sağlayıcı listesi.
	//
	// 🔴 api_key_enc SEÇİLMEZ. Şifreli hâli bile dışarı verilmez: panelde
	// gösterilecek bir şey değil ve varlığı/uzunluğu bilgi sızdırır.
	// Anahtarın TANIMLI OLUP OLMADIĞI yeterli bilgidir.
	ListProvidersForAdmin(ctx context.Context) ([]ListProvidersForAdminRow, error)
	// Mutabakat: defter toplamı ile önbelleklenmiş bakiyenin uyuşmadığı kullanıcılar.
	// Boş dönmesi beklenir; dönmezse ALARM üretilir (docs/trd.md FR-205).
	ListReconciliationDrift(ctx context.Context, limit int32) ([]ListReconciliationDriftRow, error)
	// `provider-refund-retry` için: sağlayıcıdan iade beklenen siparişler.
	ListRefundRetryOrders(ctx context.Context, arg ListRefundRetryOrdersParams) ([]Order, error)
	ListRentalCountriesForService(ctx context.Context, serviceCode string) ([]ListRentalCountriesForServiceRow, error)
	// Bir servis × ülke için kiralanabilir süreler ve en düşük maliyet.
	//
	// Fiyat BURADA DÖNMEZ: kullanıcıya gösterilen fiyat teklif (quote) ile
	// verilir. Buradaki maliyet yalnız SIRALAMA içindir ve dışa açılmaz.
	ListRentalDurationsForCatalog(ctx context.Context, arg ListRentalDurationsForCatalogParams) ([]ListRentalDurationsForCatalogRow, error)
	// Kiralık ızgarası: en az bir ülke×sürede stoklu servisler.
	ListRentalServicesWithStock(ctx context.Context) ([]ListRentalServicesWithStockRow, error)
	// Dinamik süzgeç sqlc.narg deseniyle; Go'da string birleştirilmez.
	//
	// Yönetim görünümü kullanıcıyı TANIMLAR (e-posta dâhil): moderasyon kararı
	// kimin yazdığını bilmeden verilemez. Bu sütunlar SİTEDEKİ sorguda YOKTUR.
	// Bekleyenler EN ESKİ ÖNCE: moderasyon bir kuyruktur, en uzun bekleyen ilk
	// sırada olmalı. Karara bağlanmışlar en yeni önce: yönetici son ne yaptığına
	// bakar. Tek bir sıralama ikisini de doğru yapamaz.
	ListReviewsForAdmin(ctx context.Context, arg ListReviewsForAdminParams) ([]ListReviewsForAdminRow, error)
	// Kullanıcının KENDİ yorumları ve durumları. En yeni üstte.
	ListReviewsForUser(ctx context.Context, arg ListReviewsForUserParams) ([]Review, error)
	// Servis IZGARASI için özet: yalnız en az bir ülkede STOKLU olan servisler,
	// her biri için stoklu ülke sayısı.
	//
	// NEDEN AYRI BİR SORGU: gerçek katalogda 9768 stoklu servis×ülke kombinasyonu
	// var ve hepsini tek yanıtta göndermek 1,09 MB ediyordu. Mobilde 4G'de bu
	// kabul edilemez (docs/frontend-contract.md §8). Izgara yalnız servisleri
	// gösterir; ülkeler servis seçilince ayrıca çekilir (~6 KB).
	ListServicesWithStock(ctx context.Context) ([]ListServicesWithStockRow, error)
	// YÖNETİM GÖRÜNÜMÜ: yazarın kullanıcı adı da gelir — kim yanıtladı sorusu
	// destek ekibinin iç sorusudur.
	ListTicketMessagesForAdmin(ctx context.Context, ticketID int64) ([]ListTicketMessagesForAdminRow, error)
	// KULLANICI GÖRÜNÜMÜ: personelin kullanıcı adı SEÇİLMEZ.
	//
	// Personelin kimliği kullanıcıya gösterilmez; yazar etiketi is_staff'tan
	// türetilir ("Destek ekibi"). Sütunu getirip DTO'da atmak, bir gün birinin
	// onu yanıta koymasını bir satır uzaklığa indirirdi.
	// test: internal/transport/http/handler/ticket_integration_test.go#TestStaffUsernameNeverLeaksToUser
	ListTicketMessagesForUser(ctx context.Context, ticketID int64) ([]ListTicketMessagesForUserRow, error)
	// Dinamik süzgeç sqlc.narg deseniyle; Go'da string birleştirilmez.
	//
	// İKİ AYRI SÜZGEÇ vardır ve ikisi de gereklidir:
	//   status      → tam durum eşleşmesi ("Kapatılanları göster")
	//   only_pending→ YÖNETİCİNİN KUYRUĞU: OPEN **ve** USER_REPLIED birlikte
	//
	// "Açık talepler" TEK BİR DURUM DEĞİLDİR. Yalnız OPEN süzmek, kullanıcının
	// yanıt yazdığı (USER_REPLIED) talepleri varsayılan ekrandan gizler — yani
	// yanıt bekleyen müşteri görünmez olur.
	ListTicketsForAdmin(ctx context.Context, arg ListTicketsForAdminParams) ([]ListTicketsForAdminRow, error)
	// `activation-reaper` için: terminal ama sağlayıcıda kapatılmamış siparişler.
	// KK-412: bu sorgunun sonucu uzun vadede BOŞ olmalıdır.
	//
	// ROL AYRIMI: iade ekseni AÇIK olan satırlar ('PENDING','RETRY_SCHEDULED')
	// `provider-refund-retry` işinin sorumluluğundadır ve buraya DÜŞMEZ. Bu filtre
	// olmadan iki iş aynı satıra Cancel() gönderir ve sağlayıcının verdiği
	// Retry-After süresi (FR-414) 60 saniyede bir çiğnenir.
	//
	// Kapatma ekseni (FR-412) YİNE reaper'ındır: iade ekseni DENIED/REFUNDED/
	// NOT_APPLICABLE'a düştüğü an satır buraya geri döner — kapatma denemesinden
	// vazgeçilmez.
	// test: refund_retry_integration_test.go#TestReaperIgnoresScheduledRefundOrders
	ListUnclosedTerminalOrders(ctx context.Context, lim int32) ([]Order, error)
	// deposits_user_idx (user_id, created_at DESC) tam olarak bu sıralamayı kullanır.
	ListUserDeposits(ctx context.Context, arg ListUserDepositsParams) ([]Deposit, error)
	ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error)
	ListUserSessions(ctx context.Context, userID int64) ([]Session, error)
	// tickets_user_idx (user_id, last_reply_at DESC) tam olarak bu sıralamayı kullanır.
	ListUserTickets(ctx context.Context, arg ListUserTicketsParams) ([]ListUserTicketsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Yönetim kullanıcı listesi.
	//
	// 🔴 password_hash SEÇİLMEZ. Yönetim panelinde bile: bir sızıntıda parola
	// özetleri offline kırma denemelerine açık olur ve hiçbir yönetim işlevi
	// onlara ihtiyaç duymaz.
	// test: internal/transport/http/handler/admin_integration_test.go#TestListUsersNeverReturnsPasswordHash
	ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error)
	ListVisibleCountries(ctx context.Context) ([]Country, error)
	ListVisibleServices(ctx context.Context) ([]Service, error)
	// Bir kapsamdaki ETKİN kuralı KİLİTLER.
	//
	// Kural "güncelleme" yoktur: eski kural pasifleştirilip yenisi eklenir
	// (kısmi tekil indeksler aynı kapsamda iki etkin kurala izin vermez).
	// Kilit olmadan iki yönetici aynı anda kural yazdığında ikisi de eski satırı
	// görür, ikisi de INSERT eder ve biri 23505 ile düşer — hangisinin geçtiği
	// rastgele olur. FOR UPDATE bunu sıraya sokar.
	//
	// IS NOT DISTINCT FROM kullanılır: NULL = NULL karşılaştırması `=` ile
	// daima NULL döner ve GLOBAL kapsam (üç alanı da NULL) hiç eşleşmezdi.
	LockActiveRuleForScope(ctx context.Context, arg LockActiveRuleForScopeParams) (PricingRule, error)
	// ÇAĞIRANIN TRANSACTION'I İÇİNDE çağrılmalıdır. Kilit commit'e kadar tutulur;
	// eşzamanlı onay istekleri burada sıraya girer. Kilitsiz okuyup sonra yazmak,
	// iki yöneticinin (veya bir yöneticinin iki sekmesinin) aynı talebi iki kez
	// onaylamasına ve bakiyenin iki kez artmasına yol açar.
	// test: deposit_integration_test.go#TestApproveIsIdempotentUnderConcurrency
	LockDepositForUpdate(ctx context.Context, publicID uuid.UUID) (Deposit, error)
	// Teklifi KİLİTLER. Aynı teklifle iki eşzamanlı satın alma denemesinde
	// yalnız biri geçmelidir (docs/trd.md KK-402).
	LockQuoteForConsumption(ctx context.Context, arg LockQuoteForConsumptionParams) (PriceQuote, error)
	// Yönetim yolu: ÇAĞIRANIN TRANSACTION'I İÇİNDE. Kilit, aynı yoruma iki
	// yöneticinin aynı anda karar vermesini (biri onay, biri red) engeller.
	LockReview(ctx context.Context, publicID uuid.UUID) (Review, error)
	// Yönetim yolu: sahiplik kısıtı YOKTUR, izin kontrolü middleware'dedir
	// (tickets:reply).
	LockTicket(ctx context.Context, publicID uuid.UUID) (Ticket, error)
	// ÇAĞIRANIN TRANSACTION'I İÇİNDE çağrılır. Kilit, aynı talebe iki mesajın
	// eşzamanlı yazılıp durumun ikisinden yalnız birine göre hesaplanmasını
	// engeller. Sahiplik yine SORGUDADIR — kilit almak yetki vermez.
	// test: internal/service/ticket/ticket_integration_test.go#TestUserCannotWriteToOthersTicket
	LockTicketForUser(ctx context.Context, arg LockTicketForUserParams) (Ticket, error)
	// Kullanıcı satırını KİLİTLER. Bu satır olmadan çift harcama mümkündür:
	// iki eşzamanlı istek aynı bakiyeyi okuyup ikisi de yeterli sanabilir.
	// Kilit, transaction bitene kadar tutulur.
	LockUserForUpdate(ctx context.Context, id int64) (LockUserForUpdateRow, error)
	MarkEmailVerified(ctx context.Context, id int64) error
	// Kapatma BAŞARILI OLDUKTAN SONRA çağrılır.
	// Başarısızken yazılırsa reaper o siparişi bir daha hiç denemez ve aktivasyon
	// sağlayıcıda açık kalır (FR-412).
	MarkProviderClosed(ctx context.Context, arg MarkProviderClosedParams) error
	// Senkron turunda görülmeyen teklifler "yok" sayılır. Aksi halde sağlayıcının
	// listeden çıkardığı bir kombinasyon sonsuza kadar stokta görünürdü.
	MarkStaleOffersUnavailable(ctx context.Context, arg MarkStaleOffersUnavailableParams) (int64, error)
	// Yönetim özeti. Tek sorguda: N ayrı COUNT sorgusu atmak, tablo büyüdükçe
	// panelin açılışını yavaşlatır.
	OrderStatsSummary(ctx context.Context, since time.Time) (OrderStatsSummaryRow, error)
	RecordCloseFailure(ctx context.Context, arg RecordCloseFailureParams) error
	// Bakiyeye HİÇ dokunulmaz (FR-503); burada yalnız durum ve gerekçe yazılır.
	RejectDeposit(ctx context.Context, arg RejectDepositParams) (Deposit, error)
	// Sahiplenmeyi BIRAKIR: kapatılacak bir şey olmadığı anlaşıldığında çağrılır
	// (örn. sipariş hâlâ beklemede). Kirayı boşuna tutmak, siparişin terminal
	// olduğu anda yapılacak kapatmayı kira süresi kadar geciktirirdi.
	//
	// BAŞARISIZLIKTA ÇAĞRILMAZ: kira, başarısız bir denemenin hemen ardından
	// ikinci bir denemeyi engelleyerek sağlayıcının verdiği Retry-After süresine
	// saygı gösterir.
	ReleaseOrderClose(ctx context.Context, id int64) error
	ReplaceUserRoles(ctx context.Context, arg ReplaceUserRolesParams) error
	// Sağlayıcının İngilizce ülke adını ISO2 + Türkçe ad + telefon koduna çevirir.
	ResolveCountryRef(ctx context.Context, nameKey string) (ResolveCountryRefRow, error)
	// Sağlayıcının boyut kodunu YEREL kimliğe çevirir.
	//
	// Teklif senkronu eskiden ülkeyi `countries.iso2` üzerinden arıyordu. Bu, ancak
	// sağlayıcının kodu tesadüfen ISO2 ise çalışır; HeroSMS "62" gönderir ve arama
	// boş döner. Sağlayıcı kodu ile yerel kimlik arasındaki köprü BURASIDIR.
	ResolveDimensionLocal(ctx context.Context, arg ResolveDimensionLocalParams) (int64, error)
	RevokeAllUserSessions(ctx context.Context, userID int64) error
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	RevokeSession(ctx context.Context, id string) error
	// Aktif/pasif AYRI bir sorgu: tek bir düğmeye basmak, o sırada düzenlenmekte
	// olan diğer alanları yazmamalı.
	SetDepositMethodActive(ctx context.Context, arg SetDepositMethodActiveParams) (DepositMethod, error)
	// Dekont YALNIZ sahibi tarafından ve YALNIZ inceleme öncesinde eklenebilir:
	// sonuçlandırılmış bir talebin kanıtını değiştirmek denetimi anlamsız kılar.
	SetDepositReceipt(ctx context.Context, arg SetDepositReceiptParams) (Deposit, error)
	// Durum yazımı — YALNIZ domain/order.Transition doğruladıktan sonra çağrılır.
	// Veritabanındaki tetikleyici ikinci savunma hattıdır.
	SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (Order, error)
	SetProviderActive(ctx context.Context, arg SetProviderActiveParams) error
	SetProviderRefundStatus(ctx context.Context, arg SetProviderRefundStatusParams) error
	// Servis logosunu ayarlar. Yol `web/public/` köküne göredir: /servis-logolari/wa.svg
	SetServiceIcon(ctx context.Context, arg SetServiceIconParams) (SetServiceIconRow, error)
	// 🔴 closed_at, status ile AYNI ifadede yazılır: ticket_closed_has_time
	// CHECK'i (00012_tickets.sql) iki adımlı yazımda 23514 ile düşer.
	// Talep yeniden açılırken closed_at NULL'a döner.
	SetTicketStatus(ctx context.Context, arg SetTicketStatusParams) (Ticket, error)
	SetUserBalance(ctx context.Context, arg SetUserBalanceParams) error
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) error
	// Yönetim: kullanıcı durumunu değiştirir.
	// public_id ile çalışır — sayısal id dışarı verilmez (değişmez #10).
	SetUserStatusByPublicID(ctx context.Context, arg SetUserStatusByPublicIDParams) (SetUserStatusByPublicIDRow, error)
	// İade eksenini KAPATIR: sağlayıcıya bir daha istek gönderilmez.
	//
	// `SetProviderRefundStatus`ten iki farkı var ve ikisi de kasıtlı:
	//   1. `refund_attempts` ARTIRILMAZ — kapatmak bir deneme değildir.
	//   2. Koşulludur: yalnız iade ekseni AÇIKKEN yazar, böylece iki işçi aynı
	//      anda kapatmaya çalışsa da sonuç tektir ve REFUNDED/DENIED bir satırın
	//      üstüne yazılmaz.
	// test: ../internal/service/order/refund_retry_integration_test.go#TestFinishedOrderLeavesRefundQueue
	SettleProviderRefund(ctx context.Context, arg SettleProviderRefundParams) error
	// Kâr raporu ve muhasebe özeti girdisi.
	SumLedgerByType(ctx context.Context, arg SumLedgerByTypeParams) ([]SumLedgerByTypeRow, error)
	TouchSession(ctx context.Context, id string) error
	// Mesaj eklendikten SONRA durumu ve son yanıt zamanını yazar.
	//
	// Yeni durum SERVİSTE domain/ticket ile hesaplanır (değişmez #13): bu sorgu
	// karar vermez, kararı yazar.
	TouchTicketAfterMessage(ctx context.Context, arg TouchTicketAfterMessageParams) (Ticket, error)
	UpdateDepositMethod(ctx context.Context, arg UpdateDepositMethodParams) (DepositMethod, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	// API anahtarı güncelleme — AYRI bir sorgu.
	//
	// Diğer ayarlarla aynı UPDATE'e konsaydı, ayar değiştiren her istek anahtarı
	// da yazardı ve boş bir alan anahtarı SİLERDİ. Ayrı tutmak, "kaydet"e basmanın
	// anahtarı yanlışlıkla silmesini imkânsız kılar.
	// test: internal/transport/http/handler/admin_integration_test.go#TestSavingProviderSettingsDoesNotEraseAPIKey
	//
	// 🔴 `:exec` DEĞİL `:one`: etkilenen satır sayısı GÖRÜLMELİDİR. `:exec` yalnız
	// hata döner, "hiçbir satır güncellenmedi" hata DEĞİLDİR — var olmayan bir
	// sağlayıcı kimliğine anahtar yazmak sessizce başarılı görünüyordu ve yönetici
	// maskeli önizlemeyi görüp anahtarı kaydettiğini sanıyordu. Sağlayıcı
	// çalışmadığında sebep aranacak en son yer orasıdır.
	// test: internal/transport/http/handler/admin_provider_integration_test.go#TestSetAPIKeyOnMissingProviderIs404
	UpdateProviderAPIKey(ctx context.Context, arg UpdateProviderAPIKeyParams) (int64, error)
	UpdateProviderBalance(ctx context.Context, arg UpdateProviderBalanceParams) error
	// Sağlayıcı ayarları. API ANAHTARI BURADAN GÜNCELLENMEZ — ayrı bir yol var.
	UpdateProviderSettings(ctx context.Context, arg UpdateProviderSettingsParams) (UpdateProviderSettingsRow, error)
	UpsertCountry(ctx context.Context, arg UpsertCountryParams) (Country, error)
	// ─────────────────────── Boyut eşleştirme ───────────────────────
	UpsertDimensionMap(ctx context.Context, arg UpsertDimensionMapParams) error
	// ─────────────────────── Fiyat/stok önbelleği ───────────────────────
	// synced_at UYGULAMADAN gelir, now() DEĞİL.
	//
	// Bayat teklif tespiti bu alanı bir eşikle karşılaştırır; yazım veritabanı
	// saatini, karşılaştırma uygulama saatini kullanırsa aradaki kayma tüm
	// teklifleri sessizce "yok" işaretler. İki taraf AYNI saat kaynağını kullanmalı.
	UpsertOffer(ctx context.Context, arg UpsertOfferParams) error
	UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (Permission, error)
	// ─────────────────────── Ürün ───────────────────────
	UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error)
	// Kiralık ürün. Aktivasyondan TEK FARKI süre boyutunun dolu olması —
	// ama o fark benzersizlik anahtarının parçası olduğu için aynı servis×ülke
	// için sekiz ayrı ürün (sekiz süre) yan yana durabilir.
	UpsertRentalProduct(ctx context.Context, arg UpsertRentalProductParams) (Product, error)
	UpsertRole(ctx context.Context, arg UpsertRoleParams) (Role, error)
	// ─────────────────────── Boyutlar ───────────────────────
	UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error)
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
