// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignRoleParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.RoleID)
	return err
}

const countUsersForAdmin = `-- name: CountUsersForAdmin :one
SELECT count(*) FROM users u
WHERE ($1::text IS NULL
       OR u.email ILIKE '%' || $1 || '%'
       OR u.username ILIKE '%' || $1 || '%')
  AND ($2::user_status IS NULL OR u.status = $2)
`

type CountUsersForAdminParams struct {
	Q      *string
	Status *UserStatus
}

func (q *Queries) CountUsersForAdmin(ctx context.Context, arg CountUsersForAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersForAdmin, arg.Q, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_system, created_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.code
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p       ON p.id = rp.permission_id
WHERE ur.user_id = $1
ORDER BY p.code
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name, r.description, r.is_system, r.created_at FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantPermissionToRole = `-- name: GrantPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GrantPermissionToRoleParams struct {
	RoleID       int64
	PermissionID int64
}

func (q *Queries) GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, grantPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many
SELECT
    u.public_id, u.email, u.username, u.status,
    u.email_verified_at, u.balance_minor, u.created_at,
    coalesce(string_agg(DISTINCT r.name, ','), '')::text AS roles,
    (SELECT count(*) FROM orders o WHERE o.user_id = u.id)::bigint AS order_count
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
WHERE ($1::text IS NULL
       OR u.email ILIKE '%' || $1 || '%'
       OR u.username ILIKE '%' || $1 || '%')
  AND ($2::user_status IS NULL OR u.status = $2)
GROUP BY u.id
ORDER BY u.created_at DESC
LIMIT $4 OFFSET $3
`

type ListUsersForAdminParams struct {
	Q      *string
	Status *UserStatus
	Off    int32
	Lim    int32
}

type ListUsersForAdminRow struct {
	PublicID        uuid.UUID
	Email           string
	Username        string
	Status          UserStatus
	EmailVerifiedAt *time.Time
	BalanceMinor    int64
	CreatedAt       time.Time
	Roles           string
	OrderCount      int64
}

// Yönetim kullanıcı listesi.
//
// 🔴 password_hash SEÇİLMEZ. Yönetim panelinde bile: bir sızıntıda parola
// özetleri offline kırma denemelerine açık olur ve hiçbir yönetim işlevi
// onlara ihtiyaç duymaz.
// test: internal/transport/http/handler/admin_integration_test.go#TestListUsersNeverReturnsPasswordHash
func (q *Queries) ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersForAdmin,
		arg.Q,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForAdminRow{}
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Email,
			&i.Username,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.BalanceMinor,
			&i.CreatedAt,
			&i.Roles,
			&i.OrderCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceUserRoles = `-- name: ReplaceUserRoles :exec
WITH cleared AS (DELETE FROM user_roles WHERE user_id = $1)
INSERT INTO user_roles (user_id, role_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type ReplaceUserRolesParams struct {
	UserID  int64
	RoleIds []int64
}

func (q *Queries) ReplaceUserRoles(ctx context.Context, arg ReplaceUserRolesParams) error {
	_, err := q.db.Exec(ctx, replaceUserRoles, arg.UserID, arg.RoleIds)
	return err
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RevokeRoleParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.Exec(ctx, revokeRole, arg.UserID, arg.RoleID)
	return err
}

const upsertPermission = `-- name: UpsertPermission :one
INSERT INTO permissions (code, description) VALUES ($1, $2)
ON CONFLICT (code) DO UPDATE SET description = EXCLUDED.description
RETURNING id, code, description
`

type UpsertPermissionParams struct {
	Code        string
	Description string
}

func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, upsertPermission, arg.Code, arg.Description)
	var i Permission
	err := row.Scan(&i.ID, &i.Code, &i.Description)
	return i, err
}

const upsertRole = `-- name: UpsertRole :one
INSERT INTO roles (name, description, is_system) VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description
RETURNING id, name, description, is_system, created_at
`

type UpsertRoleParams struct {
	Name        string
	Description string
	IsSystem    bool
}

func (q *Queries) UpsertRole(ctx context.Context, arg UpsertRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, upsertRole, arg.Name, arg.Description, arg.IsSystem)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}
