// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const approvedReviewStats = `-- name: ApprovedReviewStats :one
WITH sonuncu AS (
    SELECT DISTINCT ON (r.user_id) r.rating
    FROM reviews r
    WHERE r.status = 'APPROVED'
    ORDER BY r.user_id, r.reviewed_at DESC, r.id DESC
)
SELECT count(*)::bigint AS total,
       COALESCE(round(avg(rating) * 10), 0)::bigint AS average_x10
FROM sonuncu
`

type ApprovedReviewStatsRow struct {
	Total      int64
	AverageX10 int64
}

// Sitedeki özet: kaç onaylı yorum ve ortalama puan.
//
// 🔴 ORTALAMA ONDA BİRLİK TAM SAYI OLARAK döner (4.7 → 47), kayan nokta
// olarak değil. Para değil ama aynı gerekçe geçerli: `float64` üzerinden
// taşınan bir ortalama JSON'da 4.699999999999999 olur ve arayüzde iki farklı
// yerde iki farklı yuvarlanır. Bölme TEK YERDE, gösterimde yapılır.
// Yorum yoksa total 0 gelir ve ARAYÜZ BÖLÜMÜ HİÇ RENDER ETMEZ.
func (q *Queries) ApprovedReviewStats(ctx context.Context) (ApprovedReviewStatsRow, error) {
	row := q.db.QueryRow(ctx, approvedReviewStats)
	var i ApprovedReviewStatsRow
	err := row.Scan(&i.Total, &i.AverageX10)
	return i, err
}

const countPendingReviews = `-- name: CountPendingReviews :one
SELECT count(*) FROM reviews WHERE status = 'PENDING'
`

// Yönetim menüsündeki rozet için: kaç yorum karar bekliyor.
func (q *Queries) CountPendingReviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingReviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsForAdmin = `-- name: CountReviewsForAdmin :one
SELECT count(*) FROM reviews r
WHERE ($1::review_status IS NULL
       OR r.status = $1::review_status)
`

// Süzgeç koşulu ListReviewsForAdmin ile BİREBİR AYNI olmalıdır; ayrışırsa
// sayfalama "23 kayıt" der ama 12 satır gösterir.
func (q *Queries) CountReviewsForAdmin(ctx context.Context, status *ReviewStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsForAdmin, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsForUser = `-- name: CountReviewsForUser :one
SELECT count(*) FROM reviews WHERE user_id = $1
`

func (q *Queries) CountReviewsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one

INSERT INTO reviews (user_id, rating, body)
VALUES ($1, $2, $3)
RETURNING id, public_id, user_id, rating, body, status, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at
`

type CreateReviewParams struct {
	UserID int64
	Rating int16
	Body   string
}

// Müşteri yorumları.
//
// ÜÇ AYRI SORGU AİLESİ vardır ve karıştırılmaz:
//
//	*ForUser   → sahiplik SORGUNUN PARÇASIDIR (değişmez #7)
//	*ForAdmin  → sahiplik kısıtı yoktur; koruma izin ara katmanındadır
//	Approved*  → OTURUMSUZ, sitede gösterilir; KİŞİSEL VERİ SEÇMEZ
//
// Durum İSTEMCİDEN ALINMAZ: yeni yorum her zaman PENDING'dir (varsayılan) ve
// oradan yalnız durum makinesi çıkarır (değişmez #13).
//
// 🔴 "Bu kullanıcının bekleyen yorumu var mı?" diye ÖNCE SELECT YAPILMAZ.
// Kısıt kısmi benzersiz indekstedir (reviews_one_pending_per_user_idx) ve bu
// INSERT 23505 ile düşer. Uygulama katmanındaki kontrol iki eşzamanlı isteğin
// ikisi tarafından da geçilirdi.
// test: internal/service/review/review_integration_test.go#TestConcurrentSubmitsLeaveOnePending
func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview, arg.UserID, arg.Rating, arg.Body)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Rating,
		&i.Body,
		&i.Status,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decideReview = `-- name: DecideReview :one
UPDATE reviews
SET status = $1,
    rejection_reason = $2,
    reviewed_by_user_id = $3,
    reviewed_at = $4
WHERE public_id = $5
RETURNING id, public_id, user_id, rating, body, status, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at
`

type DecideReviewParams struct {
	Status           ReviewStatus
	RejectionReason  string
	ReviewedByUserID *int64
	ReviewedAt       *time.Time
	PublicID         uuid.UUID
}

// Kararı YAZAR, VERMEZ. Yeni durum serviste domain/review ile hesaplanır
// (değişmez #13); bu sorgu yalnız sonucu kaydeder.
//
// 🔴 status, rejection_reason ve reviewed_at AYNI İFADEDE yazılır:
// review_decided_has_time ve review_reason_only_when_rejected CHECK'leri
// iki adımlı bir yazımda 23514 ile düşer.
func (q *Queries) DecideReview(ctx context.Context, arg DecideReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, decideReview,
		arg.Status,
		arg.RejectionReason,
		arg.ReviewedByUserID,
		arg.ReviewedAt,
		arg.PublicID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Rating,
		&i.Body,
		&i.Status,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewForUser = `-- name: GetReviewForUser :one
SELECT id, public_id, user_id, rating, body, status, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at FROM reviews WHERE public_id = $1 AND user_id = $2
`

type GetReviewForUserParams struct {
	PublicID uuid.UUID
	UserID   int64
}

// SAHİPLİK SORGUNUN PARÇASIDIR (değişmez #7). Başkasının yorumu ile var
// olmayan yorum AYNI sonucu (sıfır satır) verir; servis ikisini de
// ErrNotFound'a çevirir.
// test: internal/transport/http/handler/review_integration_test.go#TestUserCannotSeeOthersReview
func (q *Queries) GetReviewForUser(ctx context.Context, arg GetReviewForUserParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewForUser, arg.PublicID, arg.UserID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Rating,
		&i.Body,
		&i.Status,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovedReviews = `-- name: ListApprovedReviews :many
WITH sonuncu AS (
    SELECT DISTINCT ON (r.user_id)
           r.public_id, r.rating, r.body, r.reviewed_at, u.username
    FROM reviews r
    JOIN users u ON u.id = r.user_id
    WHERE r.status = 'APPROVED'
    ORDER BY r.user_id, r.reviewed_at DESC, r.id DESC
)
SELECT public_id, rating, body, reviewed_at, username
FROM sonuncu
ORDER BY reviewed_at DESC
LIMIT $1
`

type ListApprovedReviewsRow struct {
	PublicID   uuid.UUID
	Rating     int16
	Body       string
	ReviewedAt *time.Time
	Username   string
}

// 🔴 SİTEDE GÖSTERİLEN LİSTE — OTURUMSUZ ERİŞİLİR.
//
// E-POSTA, sayısal id ve user_id BU SORGUDA SEÇİLMEZ. "Yanıtta gizleriz"
// yeterli değildir: alan seçilirse bir gün birinin onu DTO'ya koyması bir
// satır uzaklıktadır ve sızıntı sessiz olur. Seçilmeyen sütun sızamaz.
// test: internal/transport/http/handler/review_integration_test.go#TestPublicReviewsNeverExposeEmail
//
// DISTINCT ON (user_id): bir kullanıcının zaman içinde birden fazla onaylı
// yorumu olabilir (fikri değişip yenisini yazar). Sitede YALNIZ EN SONU
// gösterilir; aksi hâlde aynı kişi listede iki kez çıkar ve yorum sayısı
// gerçekte olduğundan kalabalık görünür.
func (q *Queries) ListApprovedReviews(ctx context.Context, lim int32) ([]ListApprovedReviewsRow, error) {
	rows, err := q.db.Query(ctx, listApprovedReviews, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedReviewsRow{}
	for rows.Next() {
		var i ListApprovedReviewsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Rating,
			&i.Body,
			&i.ReviewedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForAdmin = `-- name: ListReviewsForAdmin :many
SELECT r.id, r.public_id, r.user_id, r.rating, r.body, r.status, r.rejection_reason, r.reviewed_by_user_id, r.reviewed_at, r.created_at, r.updated_at,
       u.public_id AS user_public_id,
       u.email     AS user_email,
       u.username  AS user_username
FROM reviews r
JOIN users u ON u.id = r.user_id
WHERE ($1::review_status IS NULL
       OR r.status = $1::review_status)
ORDER BY (r.status = 'PENDING') DESC,
         CASE WHEN r.status = 'PENDING' THEN r.created_at END ASC,
         r.created_at DESC,
         r.id DESC
LIMIT $3 OFFSET $2
`

type ListReviewsForAdminParams struct {
	Status *ReviewStatus
	Off    int32
	Lim    int32
}

type ListReviewsForAdminRow struct {
	ID               int64
	PublicID         uuid.UUID
	UserID           int64
	Rating           int16
	Body             string
	Status           ReviewStatus
	RejectionReason  string
	ReviewedByUserID *int64
	ReviewedAt       *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	UserPublicID     uuid.UUID
	UserEmail        string
	UserUsername     string
}

// Dinamik süzgeç sqlc.narg deseniyle; Go'da string birleştirilmez.
//
// Yönetim görünümü kullanıcıyı TANIMLAR (e-posta dâhil): moderasyon kararı
// kimin yazdığını bilmeden verilemez. Bu sütunlar SİTEDEKİ sorguda YOKTUR.
// Bekleyenler EN ESKİ ÖNCE: moderasyon bir kuyruktur, en uzun bekleyen ilk
// sırada olmalı. Karara bağlanmışlar en yeni önce: yönetici son ne yaptığına
// bakar. Tek bir sıralama ikisini de doğru yapamaz.
func (q *Queries) ListReviewsForAdmin(ctx context.Context, arg ListReviewsForAdminParams) ([]ListReviewsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listReviewsForAdmin, arg.Status, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsForAdminRow{}
	for rows.Next() {
		var i ListReviewsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Rating,
			&i.Body,
			&i.Status,
			&i.RejectionReason,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserPublicID,
			&i.UserEmail,
			&i.UserUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForUser = `-- name: ListReviewsForUser :many
SELECT id, public_id, user_id, rating, body, status, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at FROM reviews
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListReviewsForUserParams struct {
	UserID int64
	Off    int32
	Lim    int32
}

// Kullanıcının KENDİ yorumları ve durumları. En yeni üstte.
func (q *Queries) ListReviewsForUser(ctx context.Context, arg ListReviewsForUserParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsForUser, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Rating,
			&i.Body,
			&i.Status,
			&i.RejectionReason,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReview = `-- name: LockReview :one
SELECT id, public_id, user_id, rating, body, status, rejection_reason, reviewed_by_user_id, reviewed_at, created_at, updated_at FROM reviews WHERE public_id = $1 FOR UPDATE
`

// Yönetim yolu: ÇAĞIRANIN TRANSACTION'I İÇİNDE. Kilit, aynı yoruma iki
// yöneticinin aynı anda karar vermesini (biri onay, biri red) engeller.
func (q *Queries) LockReview(ctx context.Context, publicID uuid.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, lockReview, publicID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Rating,
		&i.Body,
		&i.Status,
		&i.RejectionReason,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
