// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTicketsForAdmin = `-- name: CountTicketsForAdmin :one
SELECT count(*) FROM tickets t
WHERE ($1::ticket_status IS NULL
       OR t.status = $1::ticket_status)
  AND (NOT $2::boolean
       OR t.status IN ('OPEN', 'USER_REPLIED'))
`

type CountTicketsForAdminParams struct {
	Status      *TicketStatus
	OnlyPending bool
}

// Süzgeç koşulu ListTicketsForAdmin ile BİREBİR AYNI olmalıdır; ayrışırsa
// sayfalama "23 kayıt" der ama 12 satır gösterir.
func (q *Queries) CountTicketsForAdmin(ctx context.Context, arg CountTicketsForAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsForAdmin, arg.Status, arg.OnlyPending)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserTickets = `-- name: CountUserTickets :one
SELECT count(*) FROM tickets WHERE user_id = $1
`

func (q *Queries) CountUserTickets(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTickets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :one

INSERT INTO tickets (user_id, subject, priority)
VALUES ($1, $2, $3)
RETURNING id, public_id, user_id, subject, priority, status, last_reply_at, closed_at, created_at, updated_at
`

type CreateTicketParams struct {
	UserID   int64
	Subject  string
	Priority TicketPriority
}

// Destek talepleri (FR-600).
//
// İKİ AYRI SORGU AİLESİ vardır ve karıştırılmaz:
//
//	*ForUser  → sahiplik SORGUNUN PARÇASIDIR (değişmez #7)
//	*ForAdmin → sahiplik kısıtı yoktur; koruma izin ara katmanındadır
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket, arg.UserID, arg.Subject, arg.Priority)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Subject,
		&i.Priority,
		&i.Status,
		&i.LastReplyAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketMessage = `-- name: CreateTicketMessage :one
INSERT INTO ticket_messages (ticket_id, user_id, is_staff, body)
VALUES ($1, $2, $3, $4)
RETURNING id, public_id, ticket_id, user_id, is_staff, body, created_at
`

type CreateTicketMessageParams struct {
	TicketID int64
	UserID   *int64
	IsStaff  bool
	Body     string
}

// 🔴 is_staff AÇIKÇA VERİLİR. Sütunun varsayılanı yoktur (00012_tickets.sql):
// parametreyi unutan bir çağrı derlenmez ya da veritabanında düşer, sessizce
// "kullanıcı yazdı" diye kaydedilmez (KK-600).
func (q *Queries) CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (TicketMessage, error) {
	row := q.db.QueryRow(ctx, createTicketMessage,
		arg.TicketID,
		arg.UserID,
		arg.IsStaff,
		arg.Body,
	)
	var i TicketMessage
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TicketID,
		&i.UserID,
		&i.IsStaff,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getTicketForAdmin = `-- name: GetTicketForAdmin :one
SELECT t.id, t.public_id, t.user_id, t.subject, t.priority, t.status, t.last_reply_at, t.closed_at, t.created_at, t.updated_at,
       u.public_id AS user_public_id,
       u.email     AS user_email,
       u.username  AS user_username
FROM tickets t
JOIN users u ON u.id = t.user_id
WHERE t.public_id = $1
`

type GetTicketForAdminRow struct {
	ID           int64
	PublicID     uuid.UUID
	UserID       int64
	Subject      string
	Priority     TicketPriority
	Status       TicketStatus
	LastReplyAt  time.Time
	ClosedAt     *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserPublicID uuid.UUID
	UserEmail    string
	UserUsername string
}

// Sayısal id dışarı verilmez: kullanıcı users.public_id ile gösterilir.
func (q *Queries) GetTicketForAdmin(ctx context.Context, publicID uuid.UUID) (GetTicketForAdminRow, error) {
	row := q.db.QueryRow(ctx, getTicketForAdmin, publicID)
	var i GetTicketForAdminRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Subject,
		&i.Priority,
		&i.Status,
		&i.LastReplyAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserPublicID,
		&i.UserEmail,
		&i.UserUsername,
	)
	return i, err
}

const getTicketForUser = `-- name: GetTicketForUser :one
SELECT id, public_id, user_id, subject, priority, status, last_reply_at, closed_at, created_at, updated_at FROM tickets WHERE public_id = $1 AND user_id = $2
`

type GetTicketForUserParams struct {
	PublicID uuid.UUID
	UserID   int64
}

// SAHİPLİK SORGUNUN PARÇASIDIR (CLAUDE.md değişmez #7). Başkasının talebi ile
// var olmayan talep AYNI sonucu (sıfır satır) verir; servis ikisini de
// ErrNotFound'a çevirir.
func (q *Queries) GetTicketForUser(ctx context.Context, arg GetTicketForUserParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketForUser, arg.PublicID, arg.UserID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Subject,
		&i.Priority,
		&i.Status,
		&i.LastReplyAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketMessagesForAdmin = `-- name: ListTicketMessagesForAdmin :many
SELECT m.public_id, m.is_staff, m.body, m.created_at,
       COALESCE(u.username, '') AS author_username
FROM ticket_messages m
LEFT JOIN users u ON u.id = m.user_id
WHERE m.ticket_id = $1
ORDER BY m.created_at, m.id
`

type ListTicketMessagesForAdminRow struct {
	PublicID       uuid.UUID
	IsStaff        bool
	Body           string
	CreatedAt      time.Time
	AuthorUsername string
}

// YÖNETİM GÖRÜNÜMÜ: yazarın kullanıcı adı da gelir — kim yanıtladı sorusu
// destek ekibinin iç sorusudur.
func (q *Queries) ListTicketMessagesForAdmin(ctx context.Context, ticketID int64) ([]ListTicketMessagesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listTicketMessagesForAdmin, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketMessagesForAdminRow{}
	for rows.Next() {
		var i ListTicketMessagesForAdminRow
		if err := rows.Scan(
			&i.PublicID,
			&i.IsStaff,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketMessagesForUser = `-- name: ListTicketMessagesForUser :many
SELECT m.public_id, m.is_staff, m.body, m.created_at
FROM ticket_messages m
WHERE m.ticket_id = $1
ORDER BY m.created_at, m.id
`

type ListTicketMessagesForUserRow struct {
	PublicID  uuid.UUID
	IsStaff   bool
	Body      string
	CreatedAt time.Time
}

// KULLANICI GÖRÜNÜMÜ: personelin kullanıcı adı SEÇİLMEZ.
//
// Personelin kimliği kullanıcıya gösterilmez; yazar etiketi is_staff'tan
// türetilir ("Destek ekibi"). Sütunu getirip DTO'da atmak, bir gün birinin
// onu yanıta koymasını bir satır uzaklığa indirirdi.
// test: internal/transport/http/handler/ticket_integration_test.go#TestStaffUsernameNeverLeaksToUser
func (q *Queries) ListTicketMessagesForUser(ctx context.Context, ticketID int64) ([]ListTicketMessagesForUserRow, error) {
	rows, err := q.db.Query(ctx, listTicketMessagesForUser, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketMessagesForUserRow{}
	for rows.Next() {
		var i ListTicketMessagesForUserRow
		if err := rows.Scan(
			&i.PublicID,
			&i.IsStaff,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsForAdmin = `-- name: ListTicketsForAdmin :many
SELECT t.id, t.public_id, t.user_id, t.subject, t.priority, t.status, t.last_reply_at, t.closed_at, t.created_at, t.updated_at,
       u.public_id AS user_public_id,
       u.email     AS user_email,
       u.username  AS user_username,
       (SELECT count(*) FROM ticket_messages m WHERE m.ticket_id = t.id) AS message_count
FROM tickets t
JOIN users u ON u.id = t.user_id
WHERE ($1::ticket_status IS NULL
       OR t.status = $1::ticket_status)
  AND (NOT $2::boolean
       OR t.status IN ('OPEN', 'USER_REPLIED'))
ORDER BY t.last_reply_at DESC
LIMIT $4 OFFSET $3
`

type ListTicketsForAdminParams struct {
	Status      *TicketStatus
	OnlyPending bool
	Off         int32
	Lim         int32
}

type ListTicketsForAdminRow struct {
	ID           int64
	PublicID     uuid.UUID
	UserID       int64
	Subject      string
	Priority     TicketPriority
	Status       TicketStatus
	LastReplyAt  time.Time
	ClosedAt     *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserPublicID uuid.UUID
	UserEmail    string
	UserUsername string
	MessageCount int64
}

// Dinamik süzgeç sqlc.narg deseniyle; Go'da string birleştirilmez.
//
// İKİ AYRI SÜZGEÇ vardır ve ikisi de gereklidir:
//
//	status      → tam durum eşleşmesi ("Kapatılanları göster")
//	only_pending→ YÖNETİCİNİN KUYRUĞU: OPEN **ve** USER_REPLIED birlikte
//
// "Açık talepler" TEK BİR DURUM DEĞİLDİR. Yalnız OPEN süzmek, kullanıcının
// yanıt yazdığı (USER_REPLIED) talepleri varsayılan ekrandan gizler — yani
// yanıt bekleyen müşteri görünmez olur.
func (q *Queries) ListTicketsForAdmin(ctx context.Context, arg ListTicketsForAdminParams) ([]ListTicketsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listTicketsForAdmin,
		arg.Status,
		arg.OnlyPending,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsForAdminRow{}
	for rows.Next() {
		var i ListTicketsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Subject,
			&i.Priority,
			&i.Status,
			&i.LastReplyAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserPublicID,
			&i.UserEmail,
			&i.UserUsername,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTickets = `-- name: ListUserTickets :many
SELECT t.id, t.public_id, t.user_id, t.subject, t.priority, t.status, t.last_reply_at, t.closed_at, t.created_at, t.updated_at,
       (SELECT count(*) FROM ticket_messages m WHERE m.ticket_id = t.id) AS message_count
FROM tickets t
WHERE t.user_id = $1
ORDER BY t.last_reply_at DESC
LIMIT $3 OFFSET $2
`

type ListUserTicketsParams struct {
	UserID int64
	Off    int32
	Lim    int32
}

type ListUserTicketsRow struct {
	ID           int64
	PublicID     uuid.UUID
	UserID       int64
	Subject      string
	Priority     TicketPriority
	Status       TicketStatus
	LastReplyAt  time.Time
	ClosedAt     *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	MessageCount int64
}

// tickets_user_idx (user_id, last_reply_at DESC) tam olarak bu sıralamayı kullanır.
func (q *Queries) ListUserTickets(ctx context.Context, arg ListUserTicketsParams) ([]ListUserTicketsRow, error) {
	rows, err := q.db.Query(ctx, listUserTickets, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTicketsRow{}
	for rows.Next() {
		var i ListUserTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Subject,
			&i.Priority,
			&i.Status,
			&i.LastReplyAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTicket = `-- name: LockTicket :one
SELECT id, public_id, user_id, subject, priority, status, last_reply_at, closed_at, created_at, updated_at FROM tickets WHERE public_id = $1 FOR UPDATE
`

// Yönetim yolu: sahiplik kısıtı YOKTUR, izin kontrolü middleware'dedir
// (tickets:reply).
func (q *Queries) LockTicket(ctx context.Context, publicID uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, lockTicket, publicID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Subject,
		&i.Priority,
		&i.Status,
		&i.LastReplyAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockTicketForUser = `-- name: LockTicketForUser :one
SELECT id, public_id, user_id, subject, priority, status, last_reply_at, closed_at, created_at, updated_at FROM tickets WHERE public_id = $1 AND user_id = $2 FOR UPDATE
`

type LockTicketForUserParams struct {
	PublicID uuid.UUID
	UserID   int64
}

// ÇAĞIRANIN TRANSACTION'I İÇİNDE çağrılır. Kilit, aynı talebe iki mesajın
// eşzamanlı yazılıp durumun ikisinden yalnız birine göre hesaplanmasını
// engeller. Sahiplik yine SORGUDADIR — kilit almak yetki vermez.
// test: internal/service/ticket/ticket_integration_test.go#TestUserCannotWriteToOthersTicket
func (q *Queries) LockTicketForUser(ctx context.Context, arg LockTicketForUserParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, lockTicketForUser, arg.PublicID, arg.UserID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Subject,
		&i.Priority,
		&i.Status,
		&i.LastReplyAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTicketStatus = `-- name: SetTicketStatus :one
UPDATE tickets SET status = $1, closed_at = $2
WHERE public_id = $3
RETURNING id, public_id, user_id, subject, priority, status, last_reply_at, closed_at, created_at, updated_at
`

type SetTicketStatusParams struct {
	Status   TicketStatus
	ClosedAt *time.Time
	PublicID uuid.UUID
}

// 🔴 closed_at, status ile AYNI ifadede yazılır: ticket_closed_has_time
// CHECK'i (00012_tickets.sql) iki adımlı yazımda 23514 ile düşer.
// Talep yeniden açılırken closed_at NULL'a döner.
func (q *Queries) SetTicketStatus(ctx context.Context, arg SetTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, setTicketStatus, arg.Status, arg.ClosedAt, arg.PublicID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Subject,
		&i.Priority,
		&i.Status,
		&i.LastReplyAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchTicketAfterMessage = `-- name: TouchTicketAfterMessage :one
UPDATE tickets SET status = $1, last_reply_at = $2
WHERE id = $3
RETURNING id, public_id, user_id, subject, priority, status, last_reply_at, closed_at, created_at, updated_at
`

type TouchTicketAfterMessageParams struct {
	Status      TicketStatus
	LastReplyAt time.Time
	ID          int64
}

// Mesaj eklendikten SONRA durumu ve son yanıt zamanını yazar.
//
// Yeni durum SERVİSTE domain/ticket ile hesaplanır (değişmez #13): bu sorgu
// karar vermez, kararı yazar.
func (q *Queries) TouchTicketAfterMessage(ctx context.Context, arg TouchTicketAfterMessageParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, touchTicketAfterMessage, arg.Status, arg.LastReplyAt, arg.ID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Subject,
		&i.Priority,
		&i.Status,
		&i.LastReplyAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
