// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, status)
VALUES ($1, $2, $3, $4)
RETURNING id, public_id, email, email_verified_at, username, password_hash, balance_minor, status, referral_code, referred_by_user_id, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash string
	Status       UserStatus
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.PasswordHash,
		&i.BalanceMinor,
		&i.Status,
		&i.ReferralCode,
		&i.ReferredByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE email = $1 AND deleted_at IS NULL)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, public_id, email, email_verified_at, username, password_hash, balance_minor, status, referral_code, referred_by_user_id, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.PasswordHash,
		&i.BalanceMinor,
		&i.Status,
		&i.ReferralCode,
		&i.ReferredByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, email, email_verified_at, username, password_hash, balance_minor, status, referral_code, referred_by_user_id, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.PasswordHash,
		&i.BalanceMinor,
		&i.Status,
		&i.ReferralCode,
		&i.ReferredByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT id, public_id, email, email_verified_at, username, password_hash, balance_minor, status, referral_code, referred_by_user_id, created_at, updated_at, deleted_at FROM users WHERE public_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByPublicID(ctx context.Context, publicID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPublicID, publicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Username,
		&i.PasswordHash,
		&i.BalanceMinor,
		&i.Status,
		&i.ReferralCode,
		&i.ReferredByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, public_id, email, email_verified_at, username, password_hash, balance_minor, status, referral_code, referred_by_user_id, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
  AND ($1::user_status IS NULL OR status = $1::user_status)
  AND ($2::text IS NULL
       OR email::text ILIKE '%' || $2::text || '%'
       OR username::text ILIKE '%' || $2::text || '%')
ORDER BY id DESC
LIMIT $4 OFFSET $3
`

type ListUsersParams struct {
	Status *UserStatus
	Search *string
	Off    int32
	Lim    int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Status,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.Username,
			&i.PasswordHash,
			&i.BalanceMinor,
			&i.Status,
			&i.ReferralCode,
			&i.ReferredByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET email_verified_at = now(),
    status = CASE WHEN status = 'PENDING_VERIFICATION' THEN 'ACTIVE'::user_status ELSE status END
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setUserStatus = `-- name: SetUserStatus :exec
UPDATE users SET status = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetUserStatusParams struct {
	ID     int64
	Status UserStatus
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus, arg.ID, arg.Status)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1 AND deleted_at IS NULL
`

type UpdatePasswordHashParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE username = $1 AND deleted_at IS NULL)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
