// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package db

import (
	"context"
	"time"
)

const countLedgerEntries = `-- name: CountLedgerEntries :one
SELECT count(*) FROM ledger_entries
WHERE user_id = $1
  AND ($2::ledger_type IS NULL OR entry_type = $2::ledger_type)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz   IS NULL OR created_at <= $4::timestamptz)
  AND ($5::text IS NULL
       OR coalesce(note, '')::text ILIKE '%' || $5::text || '%'
       OR coalesce(reference_id, '')::text ILIKE '%' || $5::text || '%')
`

type CountLedgerEntriesParams struct {
	UserID    int64
	EntryType *LedgerType
	FromTs    *time.Time
	ToTs      *time.Time
	Q         *string
}

// 🔴 SÜZGEÇLER `ListLedgerEntries` İLE BİREBİR AYNI.
//
// ÖNCEDEN DEĞİLDİ: liste `from_ts`/`to_ts` süzerken sayım SÜZMÜYORDU. Tarih
// aralığı arayüzde henüz açılmamıştı, yani hata gizli kalmıştı; açıldığı gün
// sayfalama "1–25 / 412" derken liste 3 satır gösterecekti. `q` eklenirken
// ikisi tek elden yazıldı.
// test: wallet_integration_test.go#TestListLedgerEntriesSuzgecleri
func (q *Queries) CountLedgerEntries(ctx context.Context, arg CountLedgerEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerEntries,
		arg.UserID,
		arg.EntryType,
		arg.FromTs,
		arg.ToTs,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findLedgerEntriesByReference = `-- name: FindLedgerEntriesByReference :many
SELECT id, user_id, amount_minor, currency, entry_type, reference_type, reference_id, balance_after_minor, idempotency_key, created_by_user_id, note, created_at FROM ledger_entries
WHERE reference_type = $1 AND reference_id = $2
ORDER BY id
`

type FindLedgerEntriesByReferenceParams struct {
	ReferenceType *string
	ReferenceID   *string
}

func (q *Queries) FindLedgerEntriesByReference(ctx context.Context, arg FindLedgerEntriesByReferenceParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, findLedgerEntriesByReference, arg.ReferenceType, arg.ReferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountMinor,
			&i.Currency,
			&i.EntryType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.BalanceAfterMinor,
			&i.IdempotencyKey,
			&i.CreatedByUserID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLedgerEntryByKey = `-- name: FindLedgerEntryByKey :one

SELECT id, user_id, amount_minor, currency, entry_type, reference_type, reference_id, balance_after_minor, idempotency_key, created_by_user_id, note, created_at FROM ledger_entries WHERE idempotency_key = $1
`

// Cüzdan sorguları.
//
// BU DOSYADAKİ SIRALAMA KRİTİKTİR ve wallet servisinde birebir uygulanır:
//  1. idempotency kontrolü  →  2) satır KİLİDİ  →  3) yeterlilik  →  4) yazım
//
// Kilitsiz bir okuma-değiştir-yazma döngüsü eşzamanlı isteklerde bakiyeyi bozar
// (docs/memory.md §3.6 — eski prototipin hatası).
// İdempotency: bu anahtarla daha önce işlem yapıldıysa sonucu döner.
func (q *Queries) FindLedgerEntryByKey(ctx context.Context, idempotencyKey string) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, findLedgerEntryByKey, idempotencyKey)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountMinor,
		&i.Currency,
		&i.EntryType,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.BalanceAfterMinor,
		&i.IdempotencyKey,
		&i.CreatedByUserID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBalance = `-- name: GetUserBalance :one
SELECT balance_minor FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserBalance(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getUserBalance, id)
	var balance_minor int64
	err := row.Scan(&balance_minor)
	return balance_minor, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (
    user_id, amount_minor, currency, entry_type,
    reference_type, reference_id, balance_after_minor,
    idempotency_key, created_by_user_id, note
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, user_id, amount_minor, currency, entry_type, reference_type, reference_id, balance_after_minor, idempotency_key, created_by_user_id, note, created_at
`

type InsertLedgerEntryParams struct {
	UserID            int64
	AmountMinor       int64
	Currency          CurrencyCode
	EntryType         LedgerType
	ReferenceType     *string
	ReferenceID       *string
	BalanceAfterMinor int64
	IdempotencyKey    string
	CreatedByUserID   *int64
	Note              *string
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.UserID,
		arg.AmountMinor,
		arg.Currency,
		arg.EntryType,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.BalanceAfterMinor,
		arg.IdempotencyKey,
		arg.CreatedByUserID,
		arg.Note,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountMinor,
		&i.Currency,
		&i.EntryType,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.BalanceAfterMinor,
		&i.IdempotencyKey,
		&i.CreatedByUserID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, user_id, amount_minor, currency, entry_type, reference_type, reference_id, balance_after_minor, idempotency_key, created_by_user_id, note, created_at FROM ledger_entries
WHERE user_id = $1
  AND ($2::ledger_type IS NULL OR entry_type = $2::ledger_type)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz   IS NULL OR created_at <= $4::timestamptz)
  AND ($5::text IS NULL
       OR coalesce(note, '')::text ILIKE '%' || $5::text || '%'
       OR coalesce(reference_id, '')::text ILIKE '%' || $5::text || '%')
ORDER BY created_at DESC, id DESC
LIMIT $7 OFFSET $6
`

type ListLedgerEntriesParams struct {
	UserID    int64
	EntryType *LedgerType
	FromTs    *time.Time
	ToTs      *time.Time
	Q         *string
	Off       int32
	Lim       int32
}

// Kullanıcının hareket dökümü. SAHİPLİK sorgunun parçasıdır: user_id ayrı bir
// if kontrolü değil, WHERE koşuludur (docs/design.md §10).
//
// `q` SERBEST METİN: not ve referans kimliği. Tür adı ARANMAZ — "iade" yazan
// kullanıcı REFUND satırlarını beklerdi ama tür adı veritabanında DURMAZ,
// sunucuda enum'dan üretilir (`ledgerTypeLabel`). O iş tür süzgecinindir.
func (q *Queries) ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries,
		arg.UserID,
		arg.EntryType,
		arg.FromTs,
		arg.ToTs,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountMinor,
			&i.Currency,
			&i.EntryType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.BalanceAfterMinor,
			&i.IdempotencyKey,
			&i.CreatedByUserID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationDrift = `-- name: ListReconciliationDrift :many
SELECT user_id, email, cached_balance::bigint AS cached_balance,
       ledger_balance::bigint AS ledger_balance, drift::bigint AS drift
FROM ledger_reconciliation
WHERE drift <> 0
ORDER BY abs(drift) DESC
LIMIT $1
`

type ListReconciliationDriftRow struct {
	UserID        int64
	Email         string
	CachedBalance int64
	LedgerBalance int64
	Drift         int64
}

// Mutabakat: defter toplamı ile önbelleklenmiş bakiyenin uyuşmadığı kullanıcılar.
// Boş dönmesi beklenir; dönmezse ALARM üretilir (docs/trd.md FR-205).
func (q *Queries) ListReconciliationDrift(ctx context.Context, limit int32) ([]ListReconciliationDriftRow, error) {
	rows, err := q.db.Query(ctx, listReconciliationDrift, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReconciliationDriftRow{}
	for rows.Next() {
		var i ListReconciliationDriftRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.CachedBalance,
			&i.LedgerBalance,
			&i.Drift,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForUpdate = `-- name: LockUserForUpdate :one
SELECT id, balance_minor, status FROM users
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

type LockUserForUpdateRow struct {
	ID           int64
	BalanceMinor int64
	Status       UserStatus
}

// Kullanıcı satırını KİLİTLER. Bu satır olmadan çift harcama mümkündür:
// iki eşzamanlı istek aynı bakiyeyi okuyup ikisi de yeterli sanabilir.
// Kilit, transaction bitene kadar tutulur.
func (q *Queries) LockUserForUpdate(ctx context.Context, id int64) (LockUserForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockUserForUpdate, id)
	var i LockUserForUpdateRow
	err := row.Scan(&i.ID, &i.BalanceMinor, &i.Status)
	return i, err
}

const setUserBalance = `-- name: SetUserBalance :exec
UPDATE users SET balance_minor = $2 WHERE id = $1
`

type SetUserBalanceParams struct {
	ID           int64
	BalanceMinor int64
}

func (q *Queries) SetUserBalance(ctx context.Context, arg SetUserBalanceParams) error {
	_, err := q.db.Exec(ctx, setUserBalance, arg.ID, arg.BalanceMinor)
	return err
}

const sumLedgerByType = `-- name: SumLedgerByType :many
SELECT entry_type, count(*)::bigint AS entry_count, sum(amount_minor)::bigint AS total_minor
FROM ledger_entries
WHERE created_at >= $1 AND created_at < $2
GROUP BY entry_type
ORDER BY entry_type
`

type SumLedgerByTypeParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type SumLedgerByTypeRow struct {
	EntryType  LedgerType
	EntryCount int64
	TotalMinor int64
}

// Kâr raporu ve muhasebe özeti girdisi.
func (q *Queries) SumLedgerByType(ctx context.Context, arg SumLedgerByTypeParams) ([]SumLedgerByTypeRow, error) {
	rows, err := q.db.Query(ctx, sumLedgerByType, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumLedgerByTypeRow{}
	for rows.Next() {
		var i SumLedgerByTypeRow
		if err := rows.Scan(&i.EntryType, &i.EntryCount, &i.TotalMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
