// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/blog" | "/blog/[slug]" | "/dogrula" | "/fiyatlar" | "/giris" | "/gizlilik" | "/hakkimizda" | "/iletisim" | "/kayit" | "/kiralama" | "/kullanim-sartlari" | "/panel" | "/panel/bakiye-yukle" | "/panel/cuzdan" | "/panel/destek" | "/panel/hesap" | "/panel/numara-al" | "/panel/siparisler" | "/sifre-sifirla" | "/sifremi-unuttum" | "/sss" | "/yonetim" | "/yonetim/bakiye" | "/yonetim/denetim" | "/yonetim/destek" | "/yonetim/fiyatlar" | "/yonetim/kullanicilar" | "/yonetim/odeme-yontemleri" | "/yonetim/saglayicilar" | "/yonetim/talepler"
type PageRoutes = never
type LayoutRoutes = "/" | "/panel" | "/yonetim"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/dogrula": {}
  "/fiyatlar": {}
  "/giris": {}
  "/gizlilik": {}
  "/hakkimizda": {}
  "/iletisim": {}
  "/kayit": {}
  "/kiralama": {}
  "/kullanim-sartlari": {}
  "/panel": {}
  "/panel/bakiye-yukle": {}
  "/panel/cuzdan": {}
  "/panel/destek": {}
  "/panel/hesap": {}
  "/panel/numara-al": {}
  "/panel/siparisler": {}
  "/sifre-sifirla": {}
  "/sifremi-unuttum": {}
  "/sss": {}
  "/yonetim": {}
  "/yonetim/bakiye": {}
  "/yonetim/denetim": {}
  "/yonetim/destek": {}
  "/yonetim/fiyatlar": {}
  "/yonetim/kullanicilar": {}
  "/yonetim/odeme-yontemleri": {}
  "/yonetim/saglayicilar": {}
  "/yonetim/talepler": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/panel": never
  "/yonetim": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
