// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(genel)/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(genel)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(genel)/fiyatlar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fiyatlar">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/fiyatlar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(genel)/gizlilik/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gizlilik">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/gizlilik/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(genel)/hakkimizda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hakkimizda">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/hakkimizda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(genel)/iletisim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/iletisim">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/iletisim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(genel)/kiralama/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kiralama">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/kiralama/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(genel)/kullanim-sartlari/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kullanim-sartlari">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/kullanim-sartlari/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(genel)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(genel)/sss/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sss">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/sss/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(kimlik)/dogrula/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dogrula">> = Specific
  const handler = {} as typeof import("../../src/app/(kimlik)/dogrula/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(kimlik)/giris/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/giris">> = Specific
  const handler = {} as typeof import("../../src/app/(kimlik)/giris/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(kimlik)/kayit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kayit">> = Specific
  const handler = {} as typeof import("../../src/app/(kimlik)/kayit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(kimlik)/sifre-sifirla/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sifre-sifirla">> = Specific
  const handler = {} as typeof import("../../src/app/(kimlik)/sifre-sifirla/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(kimlik)/sifremi-unuttum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sifremi-unuttum">> = Specific
  const handler = {} as typeof import("../../src/app/(kimlik)/sifremi-unuttum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/bakiye-yukle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/bakiye-yukle">> = Specific
  const handler = {} as typeof import("../../src/app/panel/bakiye-yukle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/cuzdan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/cuzdan">> = Specific
  const handler = {} as typeof import("../../src/app/panel/cuzdan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/destek/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/destek">> = Specific
  const handler = {} as typeof import("../../src/app/panel/destek/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/hesap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/hesap">> = Specific
  const handler = {} as typeof import("../../src/app/panel/hesap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/numara-al/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/numara-al">> = Specific
  const handler = {} as typeof import("../../src/app/panel/numara-al/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel">> = Specific
  const handler = {} as typeof import("../../src/app/panel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/siparisler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/siparisler">> = Specific
  const handler = {} as typeof import("../../src/app/panel/siparisler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yonetim/bakiye/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yonetim/bakiye">> = Specific
  const handler = {} as typeof import("../../src/app/yonetim/bakiye/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yonetim/denetim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yonetim/denetim">> = Specific
  const handler = {} as typeof import("../../src/app/yonetim/denetim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yonetim/destek/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yonetim/destek">> = Specific
  const handler = {} as typeof import("../../src/app/yonetim/destek/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yonetim/fiyatlar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yonetim/fiyatlar">> = Specific
  const handler = {} as typeof import("../../src/app/yonetim/fiyatlar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yonetim/kullanicilar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yonetim/kullanicilar">> = Specific
  const handler = {} as typeof import("../../src/app/yonetim/kullanicilar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yonetim/odeme-yontemleri/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yonetim/odeme-yontemleri">> = Specific
  const handler = {} as typeof import("../../src/app/yonetim/odeme-yontemleri/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yonetim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yonetim">> = Specific
  const handler = {} as typeof import("../../src/app/yonetim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yonetim/saglayicilar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yonetim/saglayicilar">> = Specific
  const handler = {} as typeof import("../../src/app/yonetim/saglayicilar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yonetim/talepler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yonetim/talepler">> = Specific
  const handler = {} as typeof import("../../src/app/yonetim/talepler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/(genel)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(genel)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(kimlik)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(kimlik)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/panel">> = Specific
  const handler = {} as typeof import("../../src/app/panel/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/yonetim/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/yonetim">> = Specific
  const handler = {} as typeof import("../../src/app/yonetim/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
